### PR TITLE
Use CFFI-1.0 methods

### PR DESCRIPTION
**Pull request by flacjacket**
Cairocffi has been bumped with the cffi 1.0 stuff in place, so now we can finally do so as well. The standard batch of cffi 1.0 fixes, basically the same as the xcffib changes.

Also one more commit to fix dependency checking for Python 3.0 and 3.1, hopefully nobody is using those any more, but since it's in setup.py, I figured it should be corrected.

### CODE REVIEW

**Comment by cjbarnes18** [comment]
In Debian Jessie I am not able to get qtile back up and running at the moment :-(

```
craig@delli:~/qtile$ venv3/bin/python setup.py develop
Traceback (most recent call last):
  File "setup.py", line 120, in <module>
    **cffi_args
  File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/craig/qtile/venv3/lib/python3.4/site-packages/setuptools/dist.py", line 262, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/home/craig/qtile/venv3/lib/python3.4/site-packages/setuptools/dist.py", line 287, in fetch_build_eggs
    replace_conflicting=True,
  File "/home/craig/qtile/venv3/lib/python3.4/site-packages/pkg_resources.py", line 603, in resolve
    requirements = list(requirements)[::-1]
  File "/home/craig/qtile/venv3/lib/python3.4/site-packages/pkg_resources.py", line 2721, in parse_requirements
    "version spec")
  File "/home/craig/qtile/venv3/lib/python3.4/site-packages/pkg_resources.py", line 2697, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ("Expected ',' or end-of-list in", 'cairocffi>=0.7[xcb]', 'at', '[xcb]')
```

**Comment by tych0** [comment]
On Sat, Jun 06, 2015 at 12:38:31PM -0700, Craig Barnes wrote:
> In Debian Jessie I am not able to get qtile back up and running at the moment :-(

What if you take out the [xcb] from setup.py in the dependencies? That
looks like a typo to me.

**Comment by cjbarnes18** [comment]
I though that might be the case too.  Setup completes, but then when I run qtile.

```
2015-06-06 20:51:46,584 qtile make_qtile:124  Qtile crashed during startup
Traceback (most recent call last):
  File "/home/craig/qtile/bin/qtile", line 121, in make_qtile
    state=options.state,
  File "/home/craig/qtile/libqtile/manager.py", line 159, in __init__
    self._process_screens()
  File "/home/craig/qtile/libqtile/manager.py", line 317, in _process_screens
    self.groups[i],
  File "/home/craig/qtile/libqtile/config.py", line 262, in _configure
    i._configure(qtile, self)
  File "/home/craig/qtile/libqtile/bar.py", line 184, in _configure
    self.height
  File "/home/craig/qtile/libqtile/drawer.py", line 226, in __init__
    self.height,
  File "/home/craig/qtile/venv3/lib/python3.4/site-packages/cairocffi/xcb.py", line 37, in __init__
    p = cairo.cairo_xcb_surface_create(
AttributeError: cffi library 'libcairo.so.2' has no function, constant or global variable named 'cairo_xcb_surface_create'
Traceback (most recent call last):
  File "//home/craig/qtile/venv3/bin/qtile", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/craig/qtile/bin/qtile", line 130, in <module>
    q = make_qtile()
  File "/home/craig/qtile/bin/qtile", line 121, in make_qtile
    state=options.state,
  File "/home/craig/qtile/libqtile/manager.py", line 159, in __init__
    self._process_screens()
  File "/home/craig/qtile/libqtile/manager.py", line 317, in _process_screens
    self.groups[i],
  File "/home/craig/qtile/libqtile/config.py", line 262, in _configure
    i._configure(qtile, self)
  File "/home/craig/qtile/libqtile/bar.py", line 184, in _configure
    self.height
  File "/home/craig/qtile/libqtile/drawer.py", line 226, in __init__
    self.height,
  File "/home/craig/qtile/venv3/lib/python3.4/site-packages/cairocffi/xcb.py", line 37, in __init__
    p = cairo.cairo_xcb_surface_create(
AttributeError: cffi library 'libcairo.so.2' has no function, constant or global variable named 'cairo_xcb_surface_create'
```

**Comment by tych0** [comment]
On Sat, Jun 06, 2015 at 12:53:07PM -0700, Craig Barnes wrote:
> I though that might be the case too.  Setup completes, but then when I run qtile.

Looks like your cairo may not be built with xcb support. What does:

readelf -Ws /path/to/libcairo.so.2 | grep xcb_surface_create

show?

**Comment by cjbarnes18** [comment]
LGTM

```
craig@delli:~/qtile$ readelf -Ws /gnu/store/j3kc593vkmhij4icbj8ii5wzhg3hnqp0-cairo-1.14.2/lib/libcairo.so.2 | grep xcb_surface_create
   353: 00000000000a2190   698 FUNC    GLOBAL DEFAULT   10 cairo_xcb_surface_create
   573: 00000000000a2450   159 FUNC    GLOBAL DEFAULT   10 cairo_xcb_surface_create_for_bitmap
   589: 00000000000a24f0   393 FUNC    GLOBAL DEFAULT   10 cairo_xcb_surface_create_with_xrender_format
  2082: 00000000000a1dc0   435 FUNC    LOCAL  DEFAULT   10 _cairo_xcb_surface_create_internal
  2404: 00000000000a1f80   525 FUNC    LOCAL  DEFAULT   10 _cairo_xcb_surface_create_similar
  2724: 00000000000a0b80   157 FUNC    LOCAL  DEFAULT   10 _cairo_xcb_surface_create_similar_image
  3450: 00000000000a2190   698 FUNC    GLOBAL DEFAULT   10 cairo_xcb_surface_create
  3670: 00000000000a2450   159 FUNC    GLOBAL DEFAULT   10 cairo_xcb_surface_create_for_bitmap
  3686: 00000000000a24f0   393 FUNC    GLOBAL DEFAULT   10 cairo_xcb_surface_create_with_xrender_format
craig@delli:~/qtile$ readelf -Ws /usr/lib/x86_64-linux-gnu/libcairo.so.2 | grep xcb_surface_create
   377: 00000000000a7b00   167 FUNC    GLOBAL DEFAULT   11 cairo_xcb_surface_create_for_bitmap
   391: 00000000000a7bb0   435 FUNC    GLOBAL DEFAULT   11 cairo_xcb_surface_create_with_xrender_format
   396: 00000000000a7810   752 FUNC    GLOBAL DEFAULT   11 cairo_xcb_surface_create
```

**Comment by cjbarnes18** [comment]
how do I tell which lib actually gets used?

**Comment by tych0** [comment]
On Sat, Jun 06, 2015 at 01:44:29PM -0700, Craig Barnes wrote:
> how do I tell which lib actually gets used?

You could strace it and see, at least.

**Comment by flacjacket** [comment]
So one thing you may want to check is if cairocffi is actually build with xcb support. If the line were `cairocffi[xcb]>=0.7`, it parses correctly, but the point is to try and ensure xcffib is installed before cairocffi, but even then it doesn't seem to guarantee it works right. To check, whereever your packages are installed, open `cairocffi/_ffi.py`, if it is built with xcffib support, it will include the line: `from xcffib._ffi import ffi as _ffi0` as the third line. Other than first installing xcffib and then installing cairocffi, I'm having problems getting this to work right, but clearing my pip cache and running `pip --no-deps --ignore-installed cairocffi` gets it working right.

**Comment by flacjacket** [comment]
This is actually one big down side to the new cffi packaging, if ffi objects are only generated at install time, there is no way to install an `ffi.include()`'d package and get the first one to work correctly without re-installing it.

**Comment by cjbarnes18** [comment]
```
$ strace qtile 2>&1 | grep libgobject 
open("/usr/lib/x86_64-linux-gnu/libgobject-2.0.so", O_RDONLY|O_CLOEXEC) = 6
```
so now I am stuck for ideas :-(

**Comment by cjbarnes18** [comment]
```venv3/bin/pip install --no-deps --ignore-installed cairocff```
did the trick for me, thanks @flacjacket.

changing setup.py as suggested also stops the error.  Is there any value adding that to requirements.txt too?

**Comment by tych0** [comment]
Ok, I pushed this with the syntax fix and a little check to make sure that cairocffi is built correctly. Thanks!

**Comment by apinsard** [comment]
Hi. As a package maintainer, may I use this pull request to patch qtile 0.9.1 or am I better to keep xcffib <0.3.0 and wait for next qtile release ? Thanks.

**Comment by flacjacket** [comment]
@apinsard We can cut a 0.10 release soon, we've been meaning to do it to bring everything back in sync. @Roger and I were just put in charge of maintenance, this would be a good first task.

**Comment by apinsard** [comment]
OK. I used your pull request to make [a patch for 0.9.1](https://raw.githubusercontent.com/apinsard/sapher-overlay/05fb917cec2966e39a6a71360e84340b7188b8e4/x11-wm/qtile/files/0.9.1-use-cffi-1.0-methods.patch). Hope it may be useful to somebody else. :)

**Pull request merged**
