### PR TITLE
Fix Locale Setting

### PR DESCRIPTION
**Pull request by parham-dev27**
Check Issue #4353 and PR #4354

Note: Used try/except every time, so if one fails, the other can continue.

### CODE REVIEW

**Comment by parham-dev27** [comment]
@elParaguayo will you please check this out :) thank you

**Review by ramnes — APPROVED** [review]
LGTM

**Comment by elParaguayo** [comment]
Do we need all of this?

Looking at python's docs, they say:

> Applications typically start with a call of

``` python
import locale
locale.setlocale(locale.LC_ALL, '')
```
> This sets the locale for all categories to the user’s default setting (typically specified in the LANG environment variable). If the locale is not changed thereafter, using multithreading should not cause problems.

Would it be sufficient to change the existing `setlocale` line with this?

**Comment by parham-dev27** [comment]
I read the docs for the locale module and did some testing. You can achieve the same with what the docs recommend. So I changed the code. Thank you for your suggestion!

**Comment by elParaguayo** [comment]
I'll run the tests but I expect them to fail as there seems to be an unrelated issue at the moment which we may need to look into.

**Comment by elParaguayo** [comment]
Unrelated to your PR. If you rebase onto latest master they should pass OK.

**Comment by parham-dev27** [comment]
still failed

**Comment by elParaguayo** [comment]
You need to run `black` on the code to format it.  I'm pretty sure it will change `''` to `""`.

**Comment by parham-dev27** [comment]
yeah I read why the tests were failing and saw that is was because of PEP8 Standards. I went to the docs and figured out that was the problem. Thanks now the tests pass

**Pull request merged**
