### PR TITLE
Window: Add handling of _NET_CLOSE_WINDOW event

### PR DESCRIPTION
**Pull request by MrEaten**
Added handling of _NET_CLOSE_WINDOW in function
handle_ClientMessage, so that third-party panels
and others can close windows.

### CODE REVIEW

**Comment by tych0** [comment]
Can you add a test for this?

**Comment by MrEaten** [comment]
I could try, but to be honest I have no experience with python outside of hacking on my qtile config.py,
so it's not something I've ever done.

**Comment by tych0** [comment]
Without at test it's really hard for us to guarantee that this keeps working, so I'd write a test :)

**Comment by MrEaten** [comment]
I had a look at writing a test and have to admit that it's waaaay beyond me.
I'd be happy if you could do that :)

**Comment by tych0** [comment]
Sounds like a good challenge!

**Comment by m-col** [comment]
I think it's important that qtile handles this. As for testing, I'm not exactly sure how to generate a client message from a fake test window. Maybe create and map one, then just manually add the _NET_CLOSE_WINDOW flag? I have no idea!

**Comment by m-col** [comment]
I had a play around and this is the point I decided it is bed time (added to test_manager.py):

```
@manager_config
def test_net_close_window(qtile):
    w = None
    conn = xcbq.Connection(qtile.display)

    def will_close():
        nonlocal w
        w = conn.create_window(0, 0, 10, 10)
        w.map()
        conn.conn.flush()

    try:
        qtile.test_xcalc()
        assert len(qtile.c.windows()) == 1
        qtile.create_window(will_close)
        assert len(qtile.c.windows()) == 2
       w.set_property("_NET_CLOSE_WINDOW", w.wid, type="WINDOW", format=32)
        assert len(qtile.c.windows()) == 1

    finally:
        w.kill_client()
        conn.finalize()
```

but this doesn't seem to be enough. Might be a starting point.

**Comment by m-col** [comment]
Hmm I made the error of doing git stuff through the github UI and it came out messy. @MrEaten I wrote this test, and it works perfectly. Please could you rebase your commit on top of the current master? You can then apply this patch to add the test, and I can merge it.

```
diff --git a/test/test_manager.py b/test/test_manager.py
index 5b6796f1..a5d5e5f5 100644
--- a/test/test_manager.py
+++ b/test/test_manager.py
@@ -389,6 +389,24 @@ def test_kill_other(qtile):
     self.kill_window(two)
 
 
+@manager_config
+@no_xinerama
+def test_kill_via_message(qtile):
+    self = qtile
+
+    self.test_window("one")
+    window_info = self.c.window.info()
+    conn = xcbq.Connection(self.display)
+    data = xcffib.xproto.ClientMessageData.synthetic([0, 0, 0, 0, 0], "IIIII")
+    ev = xcffib.xproto.ClientMessageEvent.synthetic(
+        32, window_info["id"], conn.atoms['_NET_CLOSE_WINDOW'], data
+    )
+    conn.default_screen.root.send_event(ev, mask=xcffib.xproto.EventMask.SubstructureRedirect)
+    conn.xsync()
+    conn.finalize()
+    assert_window_died(self.c, window_info)
+
+
 @manager_config
 @no_xinerama
 def test_regression_groupswitch(qtile):
```

**Comment by ramnes** [comment]
Merged in b7d1910892e0d424bfcdd6f0576c3d9d96aaeff5. Thank you both!

**Pull request closed without merging**
