### PR TITLE
Fix pytest deprecation of pytest.config global.

### PR DESCRIPTION
**Pull request by whatacold**
Per https://docs.pytest.org/en/latest/deprecations.html#pytest-config-global

> pytest.config global
> Removed in version 5.0.
> 
> The pytest.config global object is deprecated. Instead use request.config (via the request fixture) or if you are a plugin author use the pytest_configure(config) hook. Note that many hooks can also access the config object indirectly, through session.config or item.config for example.

It prevents the WM process to be forked in the subprocess in conftest.py, so I fixed it, and all the tests passed on my side.

Hopefully it won't break the CI.

### CODE REVIEW

**Comment by flacjacket** [comment]
Have you tried running the tests with the latest pytest version? There are some places we limit that which would be nice to roll back.

**Comment by whatacold** [comment]
I'm sorry, but I don't think I get the point as my English is not very good.

Do you mean that this will fail with the lastest pytest, or that I should run it with the lastest to ensure nothing is break?

**Comment by pawamoy** [comment]
I ran it with latest pytest (5.1.2) and everything passes except for `test_svg_scaling`, but I don't think it's related to this PR.

```
    def assert_distortion_less_than(distortion, bad_distortion, factor=0.3):
        for test_val, bad_val in zip(distortion, bad_distortion):
>           assert test_val < (bad_val * factor)
E           assert inf < (22.414 * 0.3)

test/test_images2.py:112: AssertionError
```

**Comment by whatacold** [comment]
Thanks for running the tests.

And I also encountered this `test/test_images2.py:112: AssertionError` failure before,
I found that it was because the output of below command was `inf` :

    cmd ['convert', '/tmp/pytest-of-root/pytest-0/audio-volume-muted.png', '/qtile/test/data/comparison_images/audio-volume-muted_good.png', '-metric', 'PSNR', '-compare', '-format', '%[distortion]\n', 'info:']

but I failed to fix it as I'm not familiar with image processing :(

**Comment by flacjacket** [comment]
Sorry for the confusion! In c29dfb5714eb7ac794f4938edef9653da3d18d24 we pinned the pytest version used to be `< 5.0.0`, if this change allows us to revert that, that'd be great! Also, yes, I think there is other problems with that svg test, that we just don't ever hit on travis....

**Comment by whatacold** [comment]
All test suites except two (they are already reported as issues) are passed with pytest 4.6.5.

> In [c29dfb5](https://github.com/qtile/qtile/commit/c29dfb5714eb7ac794f4938edef9653da3d18d24) we pinned the pytest version used to be `< 5.0.0`

What's the reason for this limit?

**Comment by flacjacket** [comment]
> All test suites except two (they are already reported as issues) are passed with pytest 4.6.5.
> 
> > In [c29dfb5](https://github.com/qtile/qtile/commit/c29dfb5714eb7ac794f4938edef9653da3d18d24) we pinned the pytest version used to be `< 5.0.0`
> 
> What's the reason for this limit?

Some of the tests stopped passing, I'd have to go back to check which ones, but limiting the pytest version kept the tests green.

**Pull request merged**
