### PR TITLE
Add idle-notify-v1 protocol support

### LINKED ISSUE #4820: Wayland: Implement Idle notify v1 protocol
### Issue description

Is this good enough? Which applications support it? Need to investigate, for now qtile has no idle protocol implementation as the KDE one was deprecated

### Version

git

### Backend

Wayland (experimental)

### Config

_No response_

### Logs

_No response_

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

### PR DESCRIPTION
**Pull request by arjanoosting**
As I upgraded to the latest version of qtile on wayland I saw that swayidle did not work any more as the KDE idle protocol support is dropped and the idle notify v1 protocol was not added.

I think I have added the necessary code by reverting the  "(wlroots a289f81) drop KDE idle protocol support"  change and then adjusting the code to use to the IdleNotifierV1 of the idle notify v1 protocol.

At least swayidle will start for me, still need to test whether it will now lock my screen again if I am away from my keyboard :-)

I hope this fixes #4820

### CODE REVIEW

**Comment by arjanoosting** [comment]
btw, my screen got locked when I went away from my keyboard for some time :)

**Comment by tych0** [comment]
cc @jwijenbergh do you have any thoughts on this?

**Comment by jwijenbergh** [comment]
Hi, sorry. Will take a look later this week

**Comment by arjanoosting** [comment]
Noticed that er was still in issue with the set_inhited call thus fixed that and did another force push

**Comment by phragment** [comment]
I'm very interested in this, because my use of swayidle with wlr-dpms to lock and then turn off the displays on my main desktop broke in the last qtile release.
I just tested @arjanoosting version d0e6412 (adapted aur/qtile-git to use their branch) and it works for me.
Thank you for your efforts!

**Comment by jwijenbergh** [comment]
Works fine for me and code looks good. Can you add this feature to the changelog? Then ready to merge from my side

**Comment by arjanoosting** [comment]
Added the requested Changelog message

**Comment by jwijenbergh** [comment]
Thanks! Enabled auto merge

**Pull request merged**
