### PR TITLE
Add icon for MonadThreeCol

### PR DESCRIPTION
**Pull request by elParaguayo**
Looks like this:
layout-monadthreecol

### CODE REVIEW

**Comment by elParaguayo** [comment]
@mbenford @m-col 

Happy with this? Merge it?

**Comment by m-col** [comment]
LGTM - but @mbenford can have the final say on his creation :smiley:

**Comment by mbenford** [comment]
I'm flattered, but I've simply ported from XMonad.

Having said that, LGTM as well. :)

**Comment by elParaguayo** [comment]
Yeah, but when you use the layout, I wouldn't want you to see the icon out of the corner of your eye and think, "damn, that's an ugly icon for my layout!"

**Pull request merged**
