### PR TITLE
Added available parameter to memory widget

### PR DESCRIPTION
**Pull request by sohanglal**

### CODE REVIEW

**Comment by tych0** [comment]
Seems like this is causing some test failure, can you take a look?

**Comment by elParaguayo** [comment]
We mock the psutil output so you just need to add a line to include a value for the available amount. Ideally, you should add a test to check this output works too.

**Comment by sohanglal** [comment]
I accidently disabled auto merge

**Comment by tych0** [comment]
CI failure is not related to your PR (it's a hang we're investigating, but it looks like my recent code didn't work...). I will send a PR for that and re-run.

**Pull request merged**
