### PR TITLE
Handle WM_CHANGE_STATE client messages asking to minimize/unminimize

### LINKED ISSUE #1974: The "Hide" button of Chrome's screen sharing sticky window doesn't work
This window won't go away:

image

xprop:

```
_NET_WM_DESKTOP(CARDINAL) = 1
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_WINDOW_OPACITY(CARDINAL) = 4109694196
_NET_WM_STATE(ATOM) = _NET_WM_STATE_STICKY, _NET_WM_STATE_ABOVE
_NET_WM_USER_TIME(CARDINAL) = 495685613
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 1041, 1384
		program specified minimum size: 478 by 56
		program specified maximum size: 478 by 56
WM_NAME(UTF8_STRING) = "meet.google.com is sharing your screen."
_NET_WM_NAME(UTF8_STRING) = "meet.google.com is sharing your screen."
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
XdndAware(ATOM) = BITMAP
_NET_WM_ICON(CARDINAL) = 	Icon (128 x 128): ...
_NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 2
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 20979044, 20979045
_GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED(CARDINAL) = 1
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_PID(CARDINAL) = 26321
WM_CLIENT_MACHINE(STRING) = "saiga"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING, _NET_WM_SYNC_REQUEST
```

### PR DESCRIPTION
**Pull request by m-col**
Fixes #1974.

### CODE REVIEW

**Comment by m-col** [comment]
Oh hold on, the minimized window re-appears when I click or spawn another window. I exclusively use the Columns layout so never minimize windows. Could someone who is more familiar with how we should minimise windows check that I'm doing it right?

**Comment by m-col** [comment]
It's actually working perfectly now. Not sure what was going on. But anyway, should be good for merging, if anyone wants to give it a test drive to confirm :)

**Comment by m-col** [comment]
Confirmed by @DorianGray to fix.

**Comment by ramnes** [comment]
Yep, it works, thanks!

**Pull request merged**
