### PR TITLE
Vertical textboxes

### PR DESCRIPTION
**Pull request by elParaguayo**
First attempt at vertical textboxes. Will keep as draft for now.

NB rotation is currently automatic i.e. you can't force the direction.

This is what the PR can do:

### CODE REVIEW

**Comment by m-col** [comment]
I did something similar but it didn't work :(

Looks awesome, you really are the MVP

**Comment by m-col** [comment]
FWIW I don't think we need to make rotation direction configurable.... maybe we can if somebody asks for it but I can't imagine anybody would want anything other than what you've done

**Comment by elParaguayo** [comment]
> I did something similar but it didn't work :(

I thought I was going crazy for a while. Went through so many failed attempts. Hilarious that the actual code need ended up being so short!

**Comment by elParaguayo** [comment]
Let me add a test for some text widgets in a vertical bar (including import and config error widgets).

**Comment by elParaguayo** [comment]
> FWIW I don't think we need to make rotation direction configurable.... maybe we can if somebody asks for it but I can't imagine anybody would want anything other than what you've done

I think that's right. The only scenario I wondered about was if someone had a very wide vertical bar, they might want horizontal text. Feels like an edge case so I didn't implement it.

**Comment by elParaguayo** [comment]
If you're happy with the changes to the widgets (I removed the `orientations` line completely as this is inherited from the base classes) then I'll squash this into a single commit.

**Comment by m-col** [comment]
Just given it a test drive and it works great! Feel free to squash-merge in the UI if that's easier :)

**Comment by elParaguayo** [comment]
Needed to change commit message and add changelog entry.

Queued for auto-merge now.

**Comment by gustavosbarreto** [comment]
> > FWIW I don't think we need to make rotation direction configurable.... maybe we can if somebody asks for it but I can't imagine anybody would want anything other than what you've done
> 
> I think that's right. The only scenario I wondered about was if someone had a very wide vertical bar, they might want horizontal text. Feels like an edge case so I didn't implement it.

That would be awesome, I could finally have the clock widget in the left sidebar without having to twist my head to look at it 🤣 

@elParaguayo Is there any possibility of this being implemented?

**Comment by elParaguayo** [comment]
@gustavosbarreto are you asking about having a horizontal widget in a vertical bar?

**Comment by gustavosbarreto** [comment]
> @gustavosbarreto are you asking about having a horizontal widget in a vertical bar?

Yes

**Comment by elParaguayo** [comment]
Ok. I don't know about this one. There's a fair bit of work to implement this as this changes the logic that's used to layout widgets.

I suspect this won't be something that I work on at the moment.

**Pull request merged**
