### PR TITLE
Floating windows snap to windows/screens borders option

### PR DESCRIPTION
**Pull request by yobleck**
Similar to the KDE and Gnome (and other WM/DEs I assume) feature.
Intended to be enable in the config via:
```
mouse = [
    Drag([mod], "Button1", lazy.window.set_position_floating(border_snapping=True, snap_dist=10),
         start=lazy.window.get_position()),
]
```
disabled by default.

Notice how the mouse keeps moving while the window pauses on the border.
border_snapping

some squashed commit stuff:
Add test for window border snapping
Add changes to docs and changelog
Fix pep8 issues

### CODE REVIEW

**Comment by m-col** [comment]
Sorry, looks like this PR flew under the rader a bit. This looks cool. My first thought is that as this is a nicety that it might be better to add it to qtile-examples, which we are now also using for small plugin-type snippets. For this it might need to be made into its own command, rather than an argument for the existing one. While it isn't so big and would benefit from being integrated directly, I'm concerned that it will directly lead to the need for more work, such as snapping window edges during resizing, which from what I can tell follows naturally from this. @elParaguayo what do you think?

**Comment by elParaguayo** [comment]
Tricky one. 

My initial reaction (although I've given it very little thought) is that it may be a bit harder to have this as a separate piece of code because it's changing `Window` code. While I could do code injection to change widgets in `qtile-extras`, that only worked because those objects were being created in the user's config. The problem here is that the creation of `Window` objects is being created by the `Qtile` object which is a bit harder to patch with plugins.

However, I do share the concerns about the impact on managing the code and the impact on other areas which may or may not be immediately foreseeable.

It is a nice piece of work so I'd like to find some solution here!

**Comment by m-col** [comment]
It doesn't necessarily need injection - it can be a `lazy.function` and get the current window from `qtile.current_window`.

**Comment by elParaguayo** [comment]
Nice, if it can be extracted into standalone code (which, now that you said it, seems obvious) then I agree qtile-examples would be a good spot for this.

You could even do `lazy.window.function` to get the window passed as the first argument, rather than qtile, which may make it a bit easier too.

**Comment by m-col** [comment]
> You could even do lazy.window.function to get the window passed as the first argument, rather than qtile, which may make it a bit easier too.

Brilliant - much better. I always forget about `lazy.<path>.function`.

How does that sound @yobleck?

**Comment by yobleck** [comment]
I agree that it would make more sense/require less maintenance to have it in qtile-examples.
Conveniently I already have a config code injection version [here](https://github.com/yobleck/configs/blob/41dc2fa4014a4fd937a7931f3ff82f015a85ea5f/qtile/internal_modifications.py#L45-L104)
which is added to the config in the `@hook.subscribe.client_managed` [here](https://github.com/yobleck/configs/blob/41dc2fa4014a4fd937a7931f3ff82f015a85ea5f/qtile/config.py#L178) (`int_mod.` is just because I have the code in a separate file for readability) 

However the way I wrote my code injection still requires adding options to `lazy.window.set_position_floating()`. Would It make sense to just eliminate that (or move it to the hook?) since the user would be explicitly installing the plugin? And since the code's being injected at the hook would `lazy.window.function` still be necessary?

**Comment by elParaguayo** [comment]
You don't need code injection. You can actually just do it like this: https://gist.github.com/elParaguayo/05dd342326a106ebe45c20d0ff309a47

Basically, `lazy.window.function` calls a function with the window as the first argument. This gives you access to the window object so you can just replace `self` with `window` and get the same result. I've just tested it and it seems to work.

Feel free to tweak as you see fit but would be great if this could be submitted to qtile-examples.

**Comment by yobleck** [comment]
submitted to qtile-examples, so I'll close this PR.

**Comment by nonetrix** [comment]
> submitted to qtile-examples, so I'll close this PR.

Doesn't work for me but thanks

**Pull request closed without merging**
