### PR TITLE
Wayland: Opacity, shadows and corner radius with scenefx

### PR DESCRIPTION
**Pull request by jwijenbergh**
Draft. Depends on https://github.com/jwijenbergh/pywlroots/tree/scenefx (make sure to fetch submodules!) and https://github.com/wlrfx/scenefx

TODO:
- [ ]: Only unset shadow when needed for efficiency
- [ ]: Create a better Qtile API than setting window properties (maybe global config settings like bordercolor with wl_ prefixes?)
- [ ]: Make scenefx optional (detect that it is installed somehow), NO-OP opacity, shadows, corner radius if not
- [ ]: Align borders with corner radius
- [ ]: Is the xwayland implementation correct?

Opacity is now in wlroots too so in the future we wont need scenefx for this

Usage is setting the relevant properties, E.g. I just used this for testing:

```python
# add to keys
Key([mod, "control"], "x", lazy.function(set_eye_candy))

def set_eye_candy(qtile):
    curr = qtile.current_window
    if curr.opacity < 1:
        curr.opacity = 1
        curr.shadow = None
        curr.shadowblur = 20
        curr.corner_radius = 0
    else:
        curr.opacity = 0.7
        curr.shadow = "#ff0000"
        curr.shadowblur = 500
        curr.corner_radius = 10
```

To set the setting globally right now you can e.g. use a hook:

```python
@hook.subscribe.client_new
def new_win(win):
    win.opacity = 0.9
    win.shadow = "#000000aa"
    win.shadowblur = 40
    win.corner_radius = 10
```

Much love to the Scenefx team!

Using this branch in nix: https://gist.github.com/jwijenbergh/9d5de199f5ff8cda9b5439308032251b

### CODE REVIEW

**Comment by WillPower3309** [comment]
I'll work on the border impl on scenefx :)

**Comment by jwijenbergh** [comment]
> I'll work on the border impl on scenefx :)

Thanks for your hard work!

**Comment by QBobWatson** [comment]
Thank you for this!

I just started a discussion that might be relevant: https://github.com/qtile/qtile/discussions/4553 .

**Comment by WillPower3309** [comment]
We're hoping to get a stable release of scenefx out within the next week or two, we'll have SwayFX switch to the scenefx renderer in that time so will have feature parity soon

**Comment by WillPower3309** [comment]
SceneFX 0.1 released. We have a few tasks left before a 1.0 release: https://github.com/wlrfx/scenefx/milestone/2

**Comment by jwijenbergh** [comment]
This will be re-opened/rebased/redone when I implement wlroots 0.18 support

**Comment by dreamer-120** [comment]
status?

**Comment by tych0** [comment]
This depends on pywayland, so it's not compatible with the rewrite.

**Comment by elParaguayo** [comment]
It's also not clear how close scenefx is to a 1.0 release.

**Pull request closed without merging**
