### PR TITLE
Added active_label parameter to GroupBox

### PR DESCRIPTION
**Pull request by kritdass**
If you want me to do additional changes to GroupBox, I can help.

### CODE REVIEW

**Comment by elParaguayo** [comment]
Is this needed? Groups have a `label` attribute already.

**Comment by kritdass** [comment]
It is specifically for the current group and will provide another way for highlighting it. I think `focused_label` would be a better name after looking at some of the wording.

**Comment by kritdass** [comment]
Actually, I suppose that `lazy.group.set_label` can be used in a keybind. Do you think this is worth it to add for ease?

**Comment by elParaguayo** [comment]
I don't like the idea of getting a group label in the widget. You could use a hook to change the group label when focus changes.

**Comment by kritdass** [comment]
It doesn't change the group label itself, just what is displayed in the GroupBox if that is what you're thinking. I do agree this is possible otherwise, should I close this PR?

**Comment by elParaguayo** [comment]
I don't think it makes sense for the `Group` to set the `label` but have the widget set an `active_label` value. Also, having it in the widget means it's the same for every group. I'm inclined to close this.

**Comment by kritdass** [comment]
I'll close it, thanks for clarifying!

**Pull request closed without merging**
