### PR TITLE
Openweather icon fix.

### PR DESCRIPTION
**Pull request by krive001**
Added icon format openweather widget.

### CODE REVIEW

**Comment by krive001** [comment]
It works like the volume icon. You don't need to load a font, just have the marked ttf installed. @elParaguayo

**Comment by krive001** [comment]
{main_temp:.0f} @hamensman .

**Comment by hamensman** [comment]
> {main_temp:.0f} @hamensman .

Thanks, @krive001

**Comment by elParaguayo** [comment]
@krive001 I'm happy to fix the outstanding issues in this PR by pushing to your repo but it's in your `master` branch. Do you mind?

**Comment by krive001** [comment]
No problem.

**Comment by elParaguayo** [comment]
No idea what happened there - the commit's disappeared. I've got it locally so I'll submit as a new PR.

Sorry about that.

**Pull request closed without merging**
