### PR TITLE
Increase coverage

### PR DESCRIPTION
**Pull request by elParaguayo**
As I've been looking at Coveralls/CodeCov I noticed lots of red highlighting where we don't have test coverage so I thought I'd fill in a few gaps!

### CODE REVIEW

**Comment by elParaguayo** [comment]
Hmm. So...
- All tests pass when I run `pytest` locally but not in a virtual environment
- Running on CI I get failures (which I suspect is because `extension_defaults` is somehow being picked up by these tests
- Running `tox` locally gives me different errors

:angry:

**Comment by elParaguayo** [comment]
I'm inclined to go back to coveralls. While CodeCov looks nice, there are some weird issues which don't seem right to me and, unfortunately, I've not had an answer to my query in their forums.

I'm using coveralls for my qtile-extras now. Admittedly, I won't get much in the way of PRs but it's really useful for helping me check my own coverage.

**Comment by elParaguayo** [comment]
Should me merged after #2978 (and once I've resolved the conflict!)

**Comment by m-col** [comment]
Very nice, guess you want to rebase with coveralls enabled so you can see some nice big :heavy_check_mark: s ;)

**Review by m-col — APPROVED** [review]

**Comment by m-col** [comment]
Do you want to merge this now or rebase and see what the increase in coverage is?

**Comment by elParaguayo** [comment]
It'd be fun to see what the increase is!

**Pull request merged**
