### PR TITLE
Add wm_class to Window.info()

### PR DESCRIPTION
**Pull request by m-col**
This can be useful for scripting.

A test is added to ensure backends implement required cmd_info() values.

### CODE REVIEW

**Review by elParaguayo — APPROVED** [review]

**Comment by elParaguayo** [comment]
LGTM

**Comment by elParaguayo** [comment]
Why is this stalling the tests?

**Comment by elParaguayo** [comment]
I don't know if this is related but I came across a weird issue when looking at the `Systray` icon ordering that may or may not be related. Basically, my first attempt had `get_wm_name` in the `key` function when I was trying to sort the icons. This didn't seem to work and, instead, I had to set the name when the window was created.

Is there a way the `wm_class` could be loaded when the window is created, rather than having to call `get_wm_class` each time there's an `info` call?

It may make no difference as the tests are timing out, whereas my subsequent calls to get the window name just ended up returning `None`.

**Comment by m-col** [comment]
Interesting, that does sound like the same thing.

> Is there a way the wm_class could be loaded when the window is created, rather than having to call get_wm_class each time there's an info call?

I think this might be possible, yes. The window class/app_id can change at any point but I believe we can listen for changes via `PropertyNotify`. The wayland class already does listen for changes. I'll add a change for this.

**Comment by m-col** [comment]
I've added a new commit to do the above. The new test failure is a legit failure which I need to fix, so the hanging is gone :D

**Comment by elParaguayo** [comment]
Great. Although I have no idea what's causing that issue... Good that we can get round it.

**Comment by elParaguayo** [comment]
Ha. This breaks `Systray. I *love* that widget!

**Comment by elParaguayo** [comment]
It's working!

**Comment by m-col** [comment]
About time!

**Pull request merged**
