### PR TITLE
Move border painting with X pixel cache into X backend

### PR DESCRIPTION
**Pull request by m-col**

### CODE REVIEW

**Comment by tych0** [comment]
Doesn't the client return false or something if the call fails? Perhaps we should just check the return value?

**Comment by m-col** [comment]
You're absolutely right. Changed it so that it will fail if `color_pixel()` fails.

**Comment by ramnes** [comment]
I just reverted this in d50bfde012f0d9182f5b00e1e3938d17a64959d4, as it completely breaks Qtile when making any window fullscreen. See the traceback in the commit message.

**Comment by m-col** [comment]
Sad times. It looks like the problem was more X-specific code outside of the X backend so I can submit a new PR and hunt around for some other bits that could be moved there too.

**Comment by m-col** [comment]
It's strange the tests didn't catch it... it isn't clear to me why it passed test_toggle_fullscreen

**Pull request merged**
