### PR TITLE
mashed clipboard notify for utf8

### PR DESCRIPTION
**Pull request by zordsdavini**
same thing as windows title. Try to copy "ĄČĘĖ" - should show same in clipboard widget.

I don't know is it good place to fix

### CODE REVIEW

**Comment by zordsdavini** [comment]
I'm not sure about py2, but it looks same problem as here https://github.com/qtile/qtile/pull/584

**Comment by tych0** [comment]
What if we just do it at the source, something like this:

https://github.com/tych0/qtile/commit/7850bae38078d7b1f362b536e1f88ae4cc0f3af4

does that work for you?

**Comment by zordsdavini** [comment]
to_utf8() is not in range of methods here. This would be nice choice, but there to put this method as it could be used globally?

**Comment by tych0** [comment]
Hm, I think it should be if you've got xcffib 0.1.10?

**Comment by zordsdavini** [comment]
​I have it, but may be I don't know how to use it here​

On 22 January 2015 at 06:58, Tycho Andersen <notifications@github.com>
wrote:

> Hm, I think it should be if you've got xcffib 0.1.10?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qtile/qtile/pull/582#issuecomment-70971649>.
>



-- 
Arns Udovīčė

**Comment by tych0** [comment]
Ok, I can play around with the patch myself in a bit. Can you post the stack trace you get when you try this?

**Comment by zordsdavini** [comment]
for the test of to_utf8()?

2015-01-22 07:04:40,171 ERROR fire:243 Error in hook selection_change
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/libqtile/hook.py", line 241, in fire
    i(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/libqtile/widget/clipboard.py", line 69, in hook_change
    self.text = text.to_utf8()#six.b(text).decode('utf-8')#text
AttributeError: 'str' object has no attribute 'to_utf8'
2015-01-22 07:04:59,089 ERROR fire:243 Error in hook selection_change
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/libqtile/hook.py", line 241, in fire
    i(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/libqtile/widget/clipboard.py", line 69, in hook_change
    self.text = text.to_utf8()#six.b(text).decode('utf-8')#text
AttributeError: 'str' object has no attribute 'to_utf8'

**Comment by tych0** [comment]
On Wed, Jan 21, 2015 at 09:12:26PM -0800, zordsdavini wrote:
> for the test of to_utf8()?
> 
> 2015-01-22 07:04:40,171 ERROR fire:243 Error in hook selection_change
> Traceback (most recent call last):
>   File "/usr/lib/python3.4/site-packages/libqtile/hook.py", line 241, in fire
>     i(*args, **kwargs)
>   File "/usr/lib/python3.4/site-packages/libqtile/widget/clipboard.py", line 69, in hook_change
>     self.text = text.to_utf8()#six.b(text).decode('utf-8')#text
> AttributeError: 'str' object has no attribute 'to_utf8'
> 2015-01-22 07:04:59,089 ERROR fire:243 Error in hook selection_change
> Traceback (most recent call last):
>   File "/usr/lib/python3.4/site-packages/libqtile/hook.py", line 241, in fire
>     i(*args, **kwargs)
>   File "/usr/lib/python3.4/site-packages/libqtile/widget/clipboard.py", line 69, in hook_change
>     self.text = text.to_utf8()#six.b(text).decode('utf-8')#text
> AttributeError: 'str' object has no attribute 'to_utf8'

Ah, I meant with my patch applied. At that point it's already too
late. to_utf8 is defined in xcffib.

**Comment by zordsdavini** [comment]
I added same logic as https://github.com/qtile/qtile/pull/584, because I remember what in py2 everything was ok

**Comment by tych0** [comment]
Can you try the patch above?

**Comment by zordsdavini** [comment]
I tried this patch and it worked for me (py3)

**Comment by zordsdavini** [comment]
Sorry, @tych0, I didn't understand about what patch you are speaking :) I thought you gave example how to fix. Next time I'll read twice. Everything works perfectly.

**Pull request closed without merging**
