### PR TITLE
Highlight urgent windows

### PR DESCRIPTION
**Pull request by Etn40ff**
Highlight urgent windows in the TreeTab layout.

### CODE REVIEW

**Comment by tych0** [comment]
Can you add a test for this? Patch itself lgtm. (I wonder if we shouldn't have a more layout-generic way to do this...)

**Comment by Etn40ff** [comment]
I am not sure which one is the right way to add tests in qtile. Can you point me to an example?

**Comment by tych0** [comment]
I'd put it in test/layouts/test_treetab.py along side the other tests for this layout.

**Comment by ramnes** [comment]
LGTM

> I wonder if we shouldn't have a more layout-generic way to do this...

So many things that should be more layout-generic... :)

**Review by ramnes — APPROVED** [review]

**Comment by Etn40ff** [comment]
I had a look at  test/layouts/test_treetab.py but I did not find a way to test colors in a sensible way: there no property of the layout that one can look at easily. Any suggestion?

**Comment by tych0** [comment]
Yeah, it doesn't look like it's super well organized for testing right
now.

It seems like we could take all the text/border color/format
calculation stuff and turn it into its own function, and then test
various arguments to that. That's not exactly a refactoring we should
ask you to do in this patch though. Unless you're interested of course
:)

**Comment by Etn40ff** [comment]
In normal circumstances I would take care of it but right now there is way too much on my plate. Feel free to ignore my pull request if testing is a blocker.

**Comment by tych0** [comment]
Nah, that's ok. We should really reorganize this code if we want people to test it. Thanks for the patch!

**Pull request merged**
