### PR TITLE
Add option to build docs without screenshots

### PR DESCRIPTION
**Pull request by elParaguayo**
Added a `make quick` target to build docs without screenshots.

Speeds up build times which is useful when debugging docs locally.

### CODE REVIEW

**Review by SweepingBishops — APPROVED** [review]
Thanks!

**Comment by m-col** [comment]
For the makefile, how about something like this?:
```diff
diff --git a/docs/Makefile b/docs/Makefile
index 4d793021..330c1a82 100644
--- a/docs/Makefile
+++ b/docs/Makefile
@@ -2,8 +2,9 @@
 #
 
 # You can set these variables from the command line.
+DOCS_NO_SCREENSHOTS ?= 0
 SPHINXOPTS    =
-SPHINXBUILD   = sphinx-build -E -W
+SPHINXBUILD   = DOCS_NO_SCREENSHOTS=${DOCS_NO_SCREENSHOTS} sphinx-build -E -W
 PAPER         =
 BUILDDIR      = _build
 
```
This lets one disable screenshots for all commands by exporting the env var in their shell or sticking it before the make command.

**Comment by elParaguayo** [comment]
> Thanks! Could you also remove the commit fixing the documentation bug, I've fixed it here #3512.

Let's see which one gets merged first! :wink:

**Comment by elParaguayo** [comment]
> For the makefile, how about something like this?:
> 
> ```diff
> diff --git a/docs/Makefile b/docs/Makefile
> index 4d793021..330c1a82 100644
> --- a/docs/Makefile
> +++ b/docs/Makefile
> @@ -2,8 +2,9 @@
>  #
>  
>  # You can set these variables from the command line.
> +DOCS_NO_SCREENSHOTS ?= 0
>  SPHINXOPTS    =
> -SPHINXBUILD   = sphinx-build -E -W
> +SPHINXBUILD   = DOCS_NO_SCREENSHOTS=${DOCS_NO_SCREENSHOTS} sphinx-build -E -W
>  PAPER         =
>  BUILDDIR      = _build
>  
> ```
> 
> This lets one disable screenshots for all commands by exporting the env var in their shell or sticking it before the make command.

I see what you're saying. It's more work for the user though.

**Comment by elParaguayo** [comment]
> It looks like there is already a command to generate screenshots, so maybe we just shouldn't do that in the main build? Similarly the make command `genkeyimg` which is currently a dependency of the `html` command but there is no need for that -- we'll just need to run make a few times during deployment.

Not entirely sure what you're suggesting here. I think I tried making `genwidgetscreenshots` as a dependency of `make html` but it didn't stop the build on an error which I wanted it to do (so readthedocs would show an error).

**Comment by m-col** [comment]
I'm suggesting we separate out `genwidgetscreenshots`, `genkeyimg` and `html` as completely different make commands. Then for CI and RTD, we just call `make` multiple times. Is that possible?

**Comment by elParaguayo** [comment]
> I'm suggesting we separate out `genwidgetscreenshots`, `genkeyimg` and `html` as completely different make commands. Then for CI and RTD, we just call `make` multiple times. Is that possible?

Ah. Understood. Let me investigate...

**Comment by elParaguayo** [comment]
Readthedocs does not use the makefile. They rely on extensions to customise the build so we do need to trigger the build of those images from within our `sphinx_qtile.py` extension.

**Comment by m-col** [comment]
Maybe the extension can detect that it's in a RTD environment and act accordingly? They might export an environmental variable we can detect

**Comment by elParaguayo** [comment]
I think I can set environmental variables as part of the build process so that would do it.

**Comment by elParaguayo** [comment]
Funnily enough, I think my original approach was ok. I've removed the `make quick` target but that was just a shortcut to setting the environmental variable which is what determines whether screenshots are built.

The variable is unset by default which will result in screenshots being built. Setting the variable to any value will disable the docs.

I've added a note to the hacking page to clarify.

**Comment by m-col** [comment]
> The variable is unset by default which will result in screenshots being built. Setting the variable to any value will disable the docs.

Can we invert this logic so that they don't get built by default, then set the variable in the RTD build process so that it does? Sorry if I've misunderstood something above!

**Comment by elParaguayo** [comment]
> > The variable is unset by default which will result in screenshots being built. Setting the variable to any value will disable the docs.
> 
> Can we invert this logic so that they don't get built by default, then set the variable in the RTD build process so that it does? Sorry if I've misunderstood something above!

I think the answer to that is "yes" but it's a bit messy. We can't set the environmental variable in the configuration file. We set it in ReadTheDocs settings.

Happy to give that a try if you'd prefer it that way round.

**Comment by m-col** [comment]
I think that would be preferable if it's not too much trouble. Anything to minimise friction for users who might want to contribute (especially to the docs!)

**Comment by elParaguayo** [comment]
This should be working as you want it now. Screenshots are generated on readthedocs (you can check by clicking on the details link next the docs status message).

**Comment by m-col** [comment]
Perfect! Thanks again.

**Pull request merged**
