### PR TITLE
CommandSet inside another CommandSet

### PR DESCRIPTION
**Pull request by body20002**
add the ability to execute multiple CommandSet inside a CommandSet

```python
CommandSet(
    commands={
        "Hello": CommandSet(
             commands={
                 "World": "echo 'Hello, World!'"
              },
        )
    },
)
```

### CODE REVIEW

**Comment by elParaguayo** [comment]
Seems reasonable. Is it possible to add something to the test for this?

**Comment by body20002** [comment]
I hope these 2 tests are good

**Comment by anas-elgarhy** [comment]
nice feature

**Comment by elParaguayo** [comment]
I've pushed some changes to the test. If this works we need to squash into a single commit before i merge (although I can take care of that for you)

**Comment by body20002** [comment]
@elParaguayo is this good?

**Comment by elParaguayo** [comment]
Yes. That looks good. Will set it to merge after the tests complete.

**Comment by body20002** [comment]
There's a problem with ci/python 3.11 `Error: ERROR:   pep8: commands failed` pep8 doesn't seem to be installed
and someone cancelled the 3.9 tests

**Comment by elParaguayo** [comment]
The pep8 failure will be fixed if you run `black` on your code.

The other tests are cancelled automatically as soon as one test fails.

**Pull request merged**
