### PR TITLE
Move state.py to core

### PR DESCRIPTION
**Pull request by DorianGray**
QtileState is only used by Qtile and Qtile is in core. I don't see a
reason why a normal user would want to tinker with QtileState.

### CODE REVIEW

**Comment by tych0** [comment]
Can you describe why this is a good move?

Also - I see some other refactoring PRs. What's the state of your CI stuff? I'd really like to get back to reliable CI before we embark on many more refactorings.

**Comment by DorianGray** [comment]
https://github.com/qtile/qtile/pull/2072 - fixes CI

**Comment by DorianGray** [comment]
added a small comment to the commit message explaining why this is a good move.

**Comment by ramnes** [comment]
Seems kinda obvious to me. Thanks!

**Comment by ramnes** [comment]
Just for information, this will break Qtile when restarting from a previous commit to upgrade:

```
2021-01-13 17:05:44,293 WARNING libqtile manager.py:maybe_restart():L273 Restarting Qtile with os.execv(...)
2021-01-13 17:05:45,163 ERROR libqtile manager.py:_configure():L183 failed restoring state
Traceback (most recent call last):
  File "qtile/libqtile/core/manager.py", line 180, in _configure
    st = pickle.load(f)
ModuleNotFoundError: No module named 'libqtile.state'
```

This was to be expected, but maybe we should add a note in the changelog for the next release.

**Pull request merged**
