### PR TITLE
Fixes failing unittest

### PR DESCRIPTION
**Pull request by AartGoossens**
Fixes typo introduced in https://github.com/qtile/qtile/pull/1212.

### CODE REVIEW

**Comment by flacjacket** [comment]
It looks like the tests are still complaining about `ValueError: No such layout: xmonadtall`

**Comment by flacjacket** [comment]
You would have been correct before with `monadtall`, but there is no `MonadTall` layout in the chosen configuration, see the `ManagerConfig` at the top of the file.

**Comment by ramnes** [comment]
Still failing. :disappointed:

I guess it's because MonadTall is not in the list of layouts of the config in use here. Try with `tile`.

**Comment by ramnes** [comment]
That works also!

**Pull request merged**
