### PR TITLE
add ci for pypy3

### PR DESCRIPTION
**Pull request by DorianGray**
This adds(readds?) testing of qtile with pypy3

### CODE REVIEW

**Comment by DorianGray** [comment]
It looks like github actions does not support pypy3.7 (7.3.3) yet. This will have to hold until it does.

**Comment by ramnes** [comment]
Looks like they heard you! This PR got merged a few hours ago: https://github.com/actions/setup-python/pull/168

`pypy-3.7` should work now, if I understand correctly.

**Comment by DorianGray** [comment]
Lets see if it works!

**Comment by tych0** [comment]
Most of these failures look "legit" (aka someone needs to spend some time with the test suite & pypy3 and figure them all out). Given that it works in cpython, I can't imagine there's anything too awful, just a bunch of fiddly stuff.

This matches my understanding of the state of affairs: we had "allowed failure" testing of pypy3 in travis-ci, which basically meant it always failed and nobody paid attention to it :)

**Comment by DorianGray** [comment]
oof, ok. I'll take a look at these as I go and fix what I can then.

**Comment by ramnes** [comment]
Can we close this PR meanwhile?

**Pull request closed without merging**
