### PR TITLE
Add layout screenshots - test rebase

### PR DESCRIPTION
**Pull request by ervinpopescu**
Similar to the widget screenshots, this PR adds (animated) screenshots for our layouts. It also adds a very simple framework for generating more screenshots for new layouts and configuration examples.

This is based on #3460. I am testing the weird fontsize issue I have on my local build.

#### Original from @elParaguayo:
image

#### My local build:
image

### CODE REVIEW

**Comment by ervinpopescu** [comment]
The font size is fine on [RTD](https://qtile--4616.org.readthedocs.build/en/4616/manual/ref/layouts.html), this is interesting...

**Comment by elParaguayo** [comment]
I reopened the old PR. Do we need both?

**Comment by ervinpopescu** [comment]
IDK. If you would like to follow up on that one and rebase it, I'll go ahead and close this one.

**Comment by elParaguayo** [comment]
Yeah. It's fine to close this. However, as per my comment in the other thread, there are some larger changes to the docs in the pipeline. I'd prefer to get that finished first before completing this one.

**Pull request closed without merging**
