### PR TITLE
Migrate to dbus-fast

### PR DESCRIPTION
**Pull request by elParaguayo**
Draft for now.

This PR removes support for `dbus-next` which appears to be unmaintained and replaces it with `dbus-fast`.

This needs a bit of testing and will also break some things in qtile-extras so I'd like to get that ready too before merging this.

### CODE REVIEW

**Comment by tych0** [comment]
Seems fairly straightforward to me, thanks for doing this. (Though should those two things really be the same patch since it's all part of the migration?)

**Review by tych0 — APPROVED** [review]

**Comment by elParaguayo** [comment]
I'll squash them soon. Just need to make sure qtile-extras is also compatible with this.

**Comment by tych0** [comment]
Yep, also, if it's convenient to have a release for that, I can do one.

**Comment by elParaguayo** [comment]
I've tidied this up and qtile-extras looks ready to go too.

I have posted a message on Discord to see if we can get some people to test the PR before we merge it. So, let's give this a few more days.

**Comment by ervinpopescu** [comment]
@elParaguayo @tych0 I've been running this branch for some time now and I don't see any issues. Feel free to merge it.

**Comment by elParaguayo** [comment]
> @elParaguayo @tych0 I've been running this branch for some time now and I don't see any issues. Feel free to merge it.

Thanks for testing. Merged.

**Pull request merged**
