### PR TITLE
[todo-cleanup]: bar.Bar.fake_button_press

### PR DESCRIPTION
**Pull request by ervinpopescu**
`bar.Bar.fake_button_press` had extra arguments `screen` and `position` which were unused. 

I also updated relevant tests.

### CODE REVIEW

**Comment by elParaguayo** [comment]
Amazing. That had been annoying me for a while but I never got round to changing it.

**Comment by ervinpopescu** [comment]
> Amazing. That had been annoying me for a while but I never got round to changing it.

Heh. I still need to update docs to point to the [mouse events](https://docs.qtile.org/en/stable/manual/howto/widget.html#mouse-events) 😁

**Comment by ervinpopescu** [comment]
Whelp, let's stop there. The rest of the TODO's are either too niche or on `wayland` territory.

**Comment by elParaguayo** [comment]
Oh. Do you think people are using this code in the wild? I'd assumed it's only in tests.

**Comment by ervinpopescu** [comment]
> Oh. Do you think people are using this code in the wild? I'd assumed it's only in tests.

Same. TBH, I would have done it myself, if I knew that was the case. 

@elParaguayo I can write one possibly today, most likely tomorrow, if you wanna do it, go ahead. It'd be my first migration so it's gonna take some time to look at the existing examples.

**Pull request merged**
