### PR TITLE
Add `VerticalClock` widget.

### PR DESCRIPTION
**Pull request by elParaguayo**
The `VerticalClock` widget displays text horizontally in vertical bars.

Draft for now. Would be good to have some people test this. I also need to write some tests.

### CODE REVIEW

**Comment by elParaguayo** [comment]
I'd like to add a screenshot for the docs but that needs a little more work as all screenshots are with horizontal bars.

**Review by tych0 — APPROVED** [review]

**Comment by elParaguayo** [comment]
Screenshot is working but I need to rebase this to split out the screenshot manager changes from the widget.

**Comment by ervinpopescu** [comment]
Looks fine to me.

**Comment by elParaguayo** [comment]
> Although, you sure default needs to be `%H %M %S`?
> 
> I for one only use `HH:MM` in my bar.

Good point. Will change that.

**Pull request merged**
