### PR TITLE
Fix test hangs. Improve test resource management. Parallelize tests.

### PR DESCRIPTION
**Pull request by DorianGray**
This should fix our hanging tests as documented in https://github.com/qtile/qtile/issues/2068

While refactoring tests to allow `multiprocess.set_start_method("spawn")`, I realized why we had sporadic failures and were unable to run our tests in parallel. By changing some finalization procedures, we now no longer leak resources between tests.

### CODE REVIEW

**Comment by ramnes** [comment]
Why switching to `multiprocess` if the only thing we need is `multiprocessing.set_start_method('spawn')`?

**Comment by DorianGray** [comment]
that's not the only thing we need, we also need `dill` instead of `pickle`, which multiprocess provides.

**Comment by DorianGray** [comment]
Anyways this is a draft, not even sure this approach is going to work until I work through some of the remaining pickling errors.

**Comment by DorianGray** [comment]
We might be able to get by without dill, will test once I get things passing with(it's much more robust than pickle)

**Comment by DorianGray** [comment]
Definitely cannot get away with not using multiprocess/dill...would require significant gymnastics to get it to pickle a bunch of things that should be simple...it's just a test dependency anyways :/

**Comment by DorianGray** [comment]
https://github.com/qtile/qtile/pull/2119/checks?check_run_id=1724637109 is an example of the hangs that this PR fixes.

**Comment by DorianGray** [comment]
So, this successfully parallelizes tests but I can't seem to get much above 2 workers. Things start timing out and causing problems.

**Comment by DorianGray** [comment]
now depends on https://github.com/qtile/qtile/pull/2142

**Pull request closed without merging**
