### PR TITLE
TreeTab 'sections' variable

### PR DESCRIPTION
**Pull request by ZizouHuweidi**
Corrected a duplicate description inside TreeTab docs #3453

### CODE REVIEW

**Comment by elParaguayo** [comment]
Can you rebase this commit onto the latest master so the CI fixes are in your branch? Then force push this branch again.

**Comment by ZizouHuweidi** [comment]
> Can you rebase this commit onto the latest master so the CI fixes are in your branch? Then force push this branch again.

Can I do that straight from Github? I fetched from upstream and pushed but I am not sure how I rebase the initial commit or if that is what you are asking. Sorry, I am new to all of this

**Comment by elParaguayo** [comment]
No worries. I've fixed it for you.

**Comment by ZizouHuweidi** [comment]
> No worries. I've fixed it for you.

I am now learning about git rebase because of this, thanks a lot XD

**Pull request merged**
