### PR TITLE
Fix #626(Segmentation fault from xcffib when quitting)

### LINKED ISSUE #626: Segmentation fault from xcffib when quitting
Tested with qtile 3eadbbf20adf975ed2ac502f59a6a7d854b7de91 (latest commit while I'm writing) on Python3 with python-xcffib 0.2.0 in Arch Linux.
When exiting qtile, a segfault happens systematically if the screen has a Bar, regardless of the added widgets:

```
Segmentation fault (core dumped)
```

Sometimes, more or less randomly, better tracebacks are output:

```
Exception ignored in: <bound method Drawer.__del__ of <libqtile.drawer.Drawer object at 0x7ff5757b0358>>
Traceback (most recent call last):
  File "/mnt/archive/Development/qtile/bin/libqtile/drawer.py", line 233, in __del__
  File "/usr/lib/python3.4/site-packages/xcffib/xproto.py", line 2052, in FreeGC
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 355, in send_request
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 516, in wrapper
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 506, in invalid
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
Exception ignored in: <bound method Drawer.__del__ of <libqtile.drawer.Drawer object at 0x7ff576165940>>
Traceback (most recent call last):
  File "/mnt/archive/Development/qtile/bin/libqtile/drawer.py", line 233, in __del__
  File "/usr/lib/python3.4/site-packages/xcffib/xproto.py", line 2052, in FreeGC
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 355, in send_request
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 516, in wrapper
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 506, in invalid
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
Exception ignored in: <bound method Drawer.__del__ of <libqtile.drawer.Drawer object at 0x7ff576165f60>>
Traceback (most recent call last):
  File "/mnt/archive/Development/qtile/bin/libqtile/drawer.py", line 233, in __del__
  File "/usr/lib/python3.4/site-packages/xcffib/xproto.py", line 2052, in FreeGC
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 355, in send_request
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 516, in wrapper
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 506, in invalid
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
Segmentation fault (core dumped)
```

```
Exception ignored in: <bound method Drawer.__del__ of <libqtile.drawer.Drawer object at 0x7f17fd2f9128>>
Traceback (most recent call last):
  File "/mnt/archive/Development/qtile/bin/libqtile/drawer.py", line 235, in __del__
  File "/usr/lib/python3.4/site-packages/xcffib/xproto.py", line 2052, in FreeGC
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 355, in send_request
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 516, in wrapper
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 506, in invalid
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
Segmentation fault (core dumped)
```

```
Exception ignored in: <bound method Drawer.__del__ of <libqtile.drawer.Drawer object at 0x7fb5057aeac8>>
Traceback (most recent call last):
  File "/mnt/archive/Development/qtile/bin/libqtile/drawer.py", line 235, in __del__
  File "/usr/lib/python3.4/site-packages/xcffib/xproto.py", line 2052, in FreeGC
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 355, in send_request
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 516, in wrapper
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 506, in invalid
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
Exception ignored in: <bound method Drawer.__del__ of <libqtile.drawer.Drawer object at 0x7fb5057ace80>>
Traceback (most recent call last):
  File "/mnt/archive/Development/qtile/bin/libqtile/drawer.py", line 235, in __del__
  File "/usr/lib/python3.4/site-packages/xcffib/xproto.py", line 2052, in FreeGC
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 355, in send_request
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 516, in wrapper
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 506, in invalid
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
Segmentation fault (core dumped)
```

No segfaults happen if the screen doesn't have a Bar or if it only has a Gap.

### PR DESCRIPTION
**Pull request by luxrck**
Well...... This is worked for me......

### CODE REVIEW

**Comment by tych0** [comment]
Hi, does this not cause qtile to hang when it exits, since there is no way for the daemon thread to exit? The docs say:

```
The entire Python program exits when no alive non-daemon threads are left.
```

**Comment by luxrck** [comment]
MainThread will not wait daemon threads, and daemon threads will exits after MainThread exits. So......  I think we don't need to care about it.

**Comment by luxrck** [comment]
And I think the problem is thread exit-order, not gobject_thread, mainly...dbus. I think if gobject_thread exits after mainthread then this bug will not happen. BTW:
```
#in Drawer.__del__
self.qtile.conn.conn.core.FreeGC(self.gc)
self.qtile.conn.conn.core.FreePixmap(self.pixmap)
```
does this will cause some dbus-related calls ?

**Comment by tych0** [comment]
Does that mean the documentation is wrong, then? Looking at the sentence from the docs I quoted, I would expect it to hang until all the threads exit. Does this fix it for you? https://github.com/tych0/qtile/commit/d33b200992ec11913695b524a0ac5840ad23a014

**Comment by luxrck** [comment]
The doc  is not wrong, main thread will wait all non-daemon threads but it won't wait for any daemon threads. And you could not just join the gobject thread because...... it hangs on my computer......

**Comment by tych0** [comment]
Oh whoops, I totally spaced the non-daemon bit, my apologies. @kynikos, since you can reproduce the issue, can you verify that the above fixes it for you too? Thanks!

**Comment by kynikos** [comment]
Um... tl;dr it doesn't... ^^'
What I've done is:
1) fetch and checkout your "fix-segfault" branch
2) open a second tty
3) run `startx test_xinitrc` with the minimal xinitrc as in https://github.com/qtile/qtile/issues/626#issuecomment-80564386
4) once X is started, cd into qtile's repo directory
5) run `./bin/qtile -c test.conf` with the minimal configuration from https://github.com/qtile/qtile/issues/626#issuecomment-77109820
6) once qtile is started, quit with "Super+Ctrl+q"
This raises a segfault:
```
2015-04-14 20:39:12,755 qtile init_log:100  Starting Qtile
2015-04-14 20:39:14,149 qtile safe_import:49  Can't Import Widget: '.mpriswidget.Mpris', No module named 'dbus'
2015-04-14 20:39:14,152 qtile safe_import:49  Can't Import Widget: '.mpris2widget.Mpris2', No module named 'dbus'
2015-04-14 20:39:14,155 qtile safe_import:49  Can't Import Widget: '.mpdwidget.Mpd', No module named 'mpd'
2015-04-14 20:39:14,169 qtile safe_import:49  Can't Import Widget: '.wlan.Wlan', No module named 'pythonwifi'
2015-04-14 20:39:14,172 qtile safe_import:49  Can't Import Widget: '.google_calendar.GoogleCalendar', No module named 'httplib2'
2015-04-14 20:39:14,174 qtile safe_import:49  Can't Import Widget: '.imapwidget.ImapWidget', No module named 'keyring'
2015-04-14 20:39:14,178 qtile safe_import:49  Can't Import Widget: '.keyboardkbdd.KeyboardKbdd', No module named 'dbus'
2015-04-14 20:39:14,394 qtile setup_python_dbus:266  importing dbus/gobject failed, dbus will not work.
Exception ignored in: <bound method Drawer.__del__ of <libqtile.drawer.Drawer object at 0x7fabe084abe0>>
Traceback (most recent call last):
  File "/mnt/archive/Development/qtile/bin/libqtile/drawer.py", line 232, in __del__
  File "/usr/lib/python3.4/site-packages/xcffib/xproto.py", line 2052, in FreeGC
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 355, in send_request
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 518, in wrapper
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 508, in invalid
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
Segmentation fault (core dumped)
```
7) to get a backtrace I run `gdb -ex r --args python ./bin/qtile -c test.conf`, quit again and run `bt` in gdb's interface, which gives:
```
#0  0x00007ffff11f9c90 in ?? ()
#1  0x00007ffff20ee1f0 in ffi_call_unix64 () from /usr/lib/libffi.so.6
#2  0x00007ffff20edc58 in ffi_call () from /usr/lib/libffi.so.6
#3  0x00007ffff22fcfc2 in ?? () from /usr/lib/python3.4/site-packages/_cffi_backend.cpython-34m.so
#4  0x00007ffff79a9528 in PyObject_Call (func=func@entry=0x7fffeb319df0, arg=arg@entry=0x7ffff3ffc908, kw=kw@entry=0x0) at Objects/abstract.c:2040
#5  0x00007ffff7a5b4ea in do_call (nk=<optimized out>, na=<optimized out>, pp_stack=0x7fffffffdc50, func=<optimized out>) at Python/ceval.c:4466
#6  call_function (oparg=<optimized out>, pp_stack=0x7fffffffdc50) at Python/ceval.c:4264
#7  PyEval_EvalFrameEx (f=0x555555b57298, throwflag=<optimized out>) at Python/ceval.c:2838
#8  0x00007ffff7a5e947 in PyEval_EvalCodeEx (_co=0x555555d953f0, globals=0x1000100010001, locals=0x1000100010001, locals@entry=0x0, args=0x7ffff4010648, argcount=65537, kws=0x1000100010001, 
    kws@entry=0x0, kwcount=-349045616, defs=0x0, defcount=0, kwdefs=0x0, closure=0x7ffff2074860) at Python/ceval.c:3588
#9  0x00007ffff79d1ad9 in function_call (func=0x7fffec46e488, arg=0x7ffff4010630, kw=0x0) at Objects/funcobject.c:632
#10 0x00007ffff79a9528 in PyObject_Call (func=func@entry=0x7fffec46e488, arg=arg@entry=0x7ffff4010630, kw=kw@entry=0x0) at Objects/abstract.c:2040
#11 0x00007ffff79aa0bc in PyObject_CallFunctionObjArgs (callable=callable@entry=0x7fffec46e488) at Objects/abstract.c:2332
#12 0x00007ffff7a369b3 in handle_callback (ref=ref@entry=0x7ffff15177c8, callback=callback@entry=0x7fffec46e488) at Objects/weakrefobject.c:868
#13 0x00007ffff7a39930 in PyObject_ClearWeakRefs (object=<optimized out>) at Objects/weakrefobject.c:915
#14 0x00007ffff22f7720 in ?? () from /usr/lib/python3.4/site-packages/_cffi_backend.cpython-34m.so
#15 0x00007ffff79e1927 in dict_dealloc (mp=0x7ffff2073e48) at Objects/dictobject.c:1383
#16 0x00007ffff79fa9b4 in subtype_dealloc (self=0x7ffff16b4630) at Objects/typeobject.c:1186
#17 0x00007ffff79e1927 in dict_dealloc (mp=0x7ffff16d9c08) at Objects/dictobject.c:1383
#18 0x00007ffff79fa9b4 in subtype_dealloc (self=0x7ffff36b91d0) at Objects/typeobject.c:1186
#19 0x00007ffff79e1927 in dict_dealloc (mp=0x7fffeb30d508) at Objects/dictobject.c:1383
#20 0x00007ffff79fa402 in subtype_clear (self=0x7fffeb30c7f0) at Objects/typeobject.c:1047
#21 0x00007ffff7a94872 in delete_garbage (old=<optimized out>, collectable=<optimized out>) at Modules/gcmodule.c:866
#22 collect (generation=generation@entry=2, n_collected=n_collected@entry=0x0, n_uncollectable=n_uncollectable@entry=0x0, nofail=nofail@entry=1) at Modules/gcmodule.c:1032
#23 0x00007ffff7a954f1 in _PyGC_CollectNoFail () at Modules/gcmodule.c:1638
#24 0x00007ffff7a6fa99 in PyImport_Cleanup () at Python/import.c:483
#25 0x00007ffff7a7bf54 in Py_Finalize () at Python/pythonrun.c:616
#26 0x00007ffff7a93404 in Py_Main (argc=0, argv=0x0) at Modules/main.c:771
#27 0x0000555555554c06 in main ()
```
At this stage, maybe you could try to do the same and see if you can reproduce it, otherwise maybe it's something on my system...

**Comment by kynikos** [comment]
PS, using the default header commands from `/etx/X11/xinit/xinitrc` doesn't change the result.

**Comment by luxrck** [comment]
What ?
```
$ Xephyr -ac -br -noreset -screen 800x600 :1
$ DISPLAY=:1.0 qtile -c test.py
```
does this works ? BTW, could you tell me your sysinfo ? eg: `xorg version`, `xcffib version`

**Comment by luxrck** [comment]
I use archlinux, too. but I can't reproduce it. my sysinfo:
```
xorg-server: 1.17.1
python-xcffib: 0.2.2
xorg-xinit(startx): 1.3.4
dbus: 1.8.16
python-dbus: 1.2.0
```

**Comment by luxrck** [comment]
Hi @kynikos are you still get segfault ?

**Comment by kynikos** [comment]
I have exactly the same sysinfo. As I said, I segfault only with the above procedure.
Do you always install qtile system-wide for testing it, or do you just run the executable in the bin directory like I do?

**Comment by luxrck** [comment]
I run from source bin directory, too. ...... This is wired.

**Comment by kynikos** [comment]
But... reading your command above `DISPLAY=:1.0 qtile -c test.py` it looked like you were running a system-wide command... Can you post the exact procedure that you're using for testing, like I've done with mine?

**Comment by luxrck** [comment]
```
$ export PATH=$PATH:~/bin:~/src/qtile/bin
$ alias xnest="Xephyr -ac -br -noreset -screen 800x600 :1"
$ xnes &
$ DISPLAY=:1.0 qtile -c test.py
```

**Comment by kynikos** [comment]
What config do you use? How exactly do you quit the qtile in Xephyr to test this bug?

**Comment by luxrck** [comment]
I use your config file
```python
from libqtile.config import Key, Screen, Group, Drag, Click
from libqtile.command import lazy
from libqtile import layout, bar, widget, hook

keys = [Key(["mod4", "control"], "q", lazy.shutdown())]
groups = [Group("a")]
layouts = [layout.Max()]
screens = [Screen(
    bottom=bar.Bar([], 32),
)] 
```
and of course Ctrl-Meta-q to quit.

**Comment by kynikos** [comment]
I see, I can't really get the qtile in Xephyr to quit with Ctrl-Meta-q or any other combination, I don't know what we're doing different... Meanwhile have you tried my procedure instead?

**Comment by luxrck** [comment]
@kartoch  Sorry, my fault. Super+Ctrl+q to quit. I always consider that 'windows flag' key as meta key.

**Comment by kynikos** [comment]
No worries, it's just that I can't make the qtile in Xephyr get my keyboard shortcuts... However I can quit qtile with `DISPLAY=:1.0 qsh` and then issuing `shutdown()`: this still raises the exception I reported in https://github.com/qtile/qtile/pull/658#issuecomment-92813029 but without the segfault. Note that, as I said in #626, commenting the `bottom=bar.Bar([], 32),` line changes the behavior, in this case avoiding the exception but outputting `Exception ignored in:` without anything after that... All this is still in @tych0's "fix-sefgault" branch.

**Comment by luxrck** [comment]
you fetch from tych0's 'fix-segfault' branch?  that is not my code. please use my branch i626. >_<!!!

**Comment by kynikos** [comment]
Uh sorry, I misinterpreted what tych0 meant with "the above" in https://github.com/qtile/qtile/pull/658#issuecomment-92548234
Ok, https://github.com/luxrck/qtile/commit/e80de1ad6eab8279753bfa5a904d264b6eaef60d prevents the segfault in your test procedure, but still outputting that weird `Exception ignored in:` at the end.
With my testing procedure, the exception and the segfault are still there unfortunately...
(Now I've also run out of time here, I'll be back in half a day or so I guess)

**Comment by luxrck** [comment]
Thanks for your reply !

**Comment by kynikos** [comment]
I'm back with a possibly useful hint: https://github.com/kynikos/qtile/commit/db70c5927d8a3df70b022f3686df2d47e4cdfb79 fixes the bug for me, does anyone know what that destructor is doing exactly, and why it segfaults?

**Comment by luxrck** [comment]
Hi @kynikos , what's your irc nick name on ```irc://irc.oftc.net:6667/qtile``` ?

**Comment by kynikos** [comment]
I'm in as kynikos now

**Comment by kynikos** [comment]
@tych0 we fixed it in IRC, the patch works for me too, I was missing a new dependency on my system ^^'

**Comment by tych0** [comment]
Hi, sorry, what's the final verdict? Does the patch in this PR fix it?

**Comment by kynikos** [comment]
Yes, it was just me who missed http://qtile.readthedocs.org/en/latest/manual/install/index.html#dbus-gobject

**Comment by tych0** [comment]
So you've been able to reproduce this crash without gobject installed? Installing gobject certainly shouldn't fix it. Actually, I think after talking through this I may understand what's going on here...

**Comment by kynikos** [comment]
Yes, to avoid segfaults I have to have 1) python-gobject and 2) python-dbus installed, plus 3) @luxrck's patch: if any of these 3 elements is missing, a segfault is raised when quitting for me in the testing scenario I described above.

**Comment by tych0** [comment]
How about this instead? https://github.com/tych0/qtile/commit/aff959d0181f40f79e71af6bad54509448c3d21b

(if that doens't work, I promise I'll try to find some time to reproduce it myself :)

**Comment by kynikos** [comment]
Sorry, still same exception with segfault... (tested with python-{dbus,gobject} installed)

**Comment by tych0** [comment]
Ok, hmm. I don't think this patch is right, though, I'd say it just causes the race to go favorably if gobject happens to be installed. I'd really like to know what's going on vs. just merging a bandaid, though.

**Comment by kynikos** [comment]
Of course, if you think this is a band-aid it's better if we investigate it better and find the real cause of the race: take your time and ask any more info/help you will need! After all, this bug is not creating any problems in practice, so there's no hurry ;)

**Comment by tych0** [comment]
On Wed, Apr 15, 2015 at 08:56:04AM -0700, Dario Giovannetti wrote:
> Of course, if you think this is a band-aid it's better if we investigate it better and find the real cause of the race: take your time and ask any more info/help you will need! After all, this bug is not creating any problems in practice, so there's no hurry ;)

I have another 15 hours or so on planes coming this weekend, so I hope
to investigate more then :)

**Comment by w1ndy** [comment]
hi @kynikos , you may try w1ndy/qtile@4932f4f5b727a53423e76a92b2996389fff4ede1 and see if segfault still there

**Comment by kynikos** [comment]
Hey w1ndy, I'm sorry, your branch is still segfaulting... On the other hand, it prevents the following exception that is instead occurring in the current develop branch (a51189ab2c299b568a1715068fa835fd278b08eb), before the segfault:
```
Exception ignored in: <bound method Drawer.__del__ of <libqtile.drawer.Drawer object at 0x7ff5e8d73358>>
Traceback (most recent call last):
  File "/mnt/archive/Development/qtile/bin/libqtile/drawer.py", line 232, in __del__
/usr/lib/python3.4/importlib/_bootstrap.py:2150: ImportWarning: sys.meta_path is empty
...
/usr/lib/python3.4/importlib/_bootstrap.py:2150: ImportWarning: sys.meta_path is empty
  File "/usr/lib/python3.4/site-packages/xcffib/xproto.py", line 2052, in FreeGC
/usr/lib/python3.4/importlib/_bootstrap.py:2150: ImportWarning: sys.meta_path is empty
...
/usr/lib/python3.4/importlib/_bootstrap.py:2150: ImportWarning: sys.meta_path is empty
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 355, in send_request
/usr/lib/python3.4/importlib/_bootstrap.py:2150: ImportWarning: sys.meta_path is empty
...
/usr/lib/python3.4/importlib/_bootstrap.py:2150: ImportWarning: sys.meta_path is empty
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 518, in wrapper
/usr/lib/python3.4/importlib/_bootstrap.py:2150: ImportWarning: sys.meta_path is empty
...
/usr/lib/python3.4/importlib/_bootstrap.py:2150: ImportWarning: sys.meta_path is empty
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 508, in invalid
/usr/lib/python3.4/importlib/_bootstrap.py:2150: ImportWarning: sys.meta_path is empty
...
/usr/lib/python3.4/importlib/_bootstrap.py:2150: ImportWarning: sys.meta_path is empty
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
Segmentation fault (core dumped)
```

The ellipses represent many repeated `/usr/lib/python3.4/importlib/_bootstrap.py:2150: ImportWarning: sys.meta_path is empty` lines.

**Comment by w1ndy** [comment]
hi @kynikos , I reproduced segfault with your configuration when closing qtile before Xephyr. Could you please try again with w1ndy/qtile#a72aa3efd6aecddf2873b8b546e0303e62a46f56 and see if segfault goes away and dbus works normally?

**Comment by w1ndy** [comment]
Also you could try w1ndy/qtile@416e14b05dfdcbd07834db379fee83cbeea760ee . GObject thread in this commit uses event loop.

**Comment by kynikos** [comment]
Yep, both commits seem to exit cleanly for me too! What do you mean by "see if [...] dbus works normally"?

**Comment by w1ndy** [comment]
I'm not familiar with dbus and this piece of code uses the suggested method mentioned in [GObject reference manual](http://www.pygtk.org/pygtk2reference/class-gobjectmainloop.html). I don't know whether it will work perfectly, but I guess so ;)

**Comment by tych0** [comment]
Ok, I forgot that I had this finalizer commit laying around from a plane ride a while ago. I think (?) this should fix the problem, and it's the right way to do it anyway. Can someone test this? :D

**Comment by kynikos** [comment]
Sorry tych0, your branch still segfaulting for me... ^^

**Comment by flacjacket** [comment]
I was playing around with @tych0 's finalizers and I realized I'm getting the segfaults _without_ pygobject installed, so there is at least one problem with our cffi handling. I get a backtrace very similar to @kynikos:

```
2015-07-15 21:11:35,632 qtile init_log:105  Starting Qtile
2015-07-15 21:11:35,889 qtile safe_import:49  Can't Import Widget: '.launchbar.LaunchBar', No module named 'xdg'
2015-07-15 21:11:35,891 qtile safe_import:49  Can't Import Widget: '.mpdwidget.Mpd', No module named 'mpd'
2015-07-15 21:11:35,896 qtile safe_import:49  Can't Import Widget: '.wlan.Wlan', No module named 'pythonwifi'
2015-07-15 21:11:35,896 qtile safe_import:49  Can't Import Widget: '.google_calendar.GoogleCalendar', No module named 'httplib2'
2015-07-15 21:11:35,897 qtile safe_import:49  Can't Import Widget: '.imapwidget.ImapWidget', No module named 'keyring'
2015-07-15 21:11:35,902 py.warnings <module>:32  /usr/lib64/python3.4/imp.py:32: PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  PendingDeprecationWarning)

2015-07-15 21:11:36,054 qtile setup_python_dbus:268  importing dbus/gobject failed, dbus will not work.

Program received signal SIGTERM, Terminated.
0x00007ffff7478533 in __epoll_wait_nocancel () at ../sysdeps/unix/syscall-template.S:81
81      ../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) c
Continuing.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff17680e0 in ?? ()
(gdb) bt
#0  0x00007ffff17680e0 in ?? ()
#1  0x00007ffff21a4010 in ffi_call_unix64 () at /var/tmp/portage/dev-libs/libffi-3.2.1/work/libffi-3.2.1/src/x86/unix64.S:76
#2  0x00007ffff21a3a78 in ffi_call (cif=<optimized out>, fn=<optimized out>, rvalue=0x7ffff6c0bfb0, avalue=0x7ffff6c0bfa8)
    at /var/tmp/portage/dev-libs/libffi-3.2.1/work/libffi-3.2.1/src/x86/ffi64.c:525
#3  0x00007ffff2493952 in ?? () from /usr/lib64/python3.4/site-packages/_cffi_backend.cpython-34.so
#4  0x00007ffff79a85e8 in PyObject_Call (func=func@entry=<_cffi_backend.CData at remote 0x7fffead4f670>, 
    arg=arg@entry=(<_cffi_backend.CData at remote 0x7fffead4f3f0>,), kw=kw@entry=0x0)
    at /var/tmp/portage/dev-lang/python-3.4.3/work/Python-3.4.3/Objects/abstract.c:2040
#5  0x00007ffff79a917c in PyObject_CallFunctionObjArgs (callable=<_cffi_backend.CData at remote 0x7fffead4f670>)
    at /var/tmp/portage/dev-lang/python-3.4.3/work/Python-3.4.3/Objects/abstract.c:2332
#6  0x00007ffff248a1ce in ?? () from /usr/lib64/python3.4/site-packages/_cffi_backend.cpython-34.so
#7  0x00007ffff79a85e8 in PyObject_Call (func=func@entry=<built-in method gc_wref_remove of tuple object at remote 0x7fffead61cc8>, 
    arg=arg@entry=(<weakref at remote 0x7fffeacefea8>,), kw=kw@entry=0x0) at /var/tmp/portage/dev-lang/python-3.4.3/work/Python-3.4.3/Objects/abstract.c:2040
#8  0x00007ffff79a917c in PyObject_CallFunctionObjArgs (callable=callable@entry=<built-in method gc_wref_remove of tuple object at remote 0x7fffead61cc8>)
    at /var/tmp/portage/dev-lang/python-3.4.3/work/Python-3.4.3/Objects/abstract.c:2332
#9  0x00007ffff7a362e3 in handle_callback (ref=ref@entry=0x7fffeacefea8, 
    callback=callback@entry=<built-in method gc_wref_remove of tuple object at remote 0x7fffead61cc8>)
    at /var/tmp/portage/dev-lang/python-3.4.3/work/Python-3.4.3/Objects/weakrefobject.c:868
#10 0x00007ffff7a39250 in PyObject_ClearWeakRefs (object=<optimized out>)
    at /var/tmp/portage/dev-lang/python-3.4.3/work/Python-3.4.3/Objects/weakrefobject.c:915
#11 0x00007ffff2488a40 in ?? () from /usr/lib64/python3.4/site-packages/_cffi_backend.cpython-34.so
#12 0x00007ffff79e1377 in dict_dealloc (mp=0x7fffead1f8c8) at /var/tmp/portage/dev-lang/python-3.4.3/work/Python-3.4.3/Objects/dictobject.c:1383
#13 0x00007ffff79f9d82 in subtype_clear (self=<Context at remote 0x7fffeacf4588>)
    at /var/tmp/portage/dev-lang/python-3.4.3/work/Python-3.4.3/Objects/typeobject.c:1047
#14 0x00007ffff7a94482 in delete_garbage (old=<optimized out>, collectable=<optimized out>)
    at /var/tmp/portage/dev-lang/python-3.4.3/work/Python-3.4.3/Modules/gcmodule.c:866
#15 collect (generation=generation@entry=2, n_collected=n_collected@entry=0x0, n_uncollectable=n_uncollectable@entry=0x0, nofail=nofail@entry=1)
    at /var/tmp/portage/dev-lang/python-3.4.3/work/Python-3.4.3/Modules/gcmodule.c:1032
#16 0x00007ffff7a95101 in _PyGC_CollectNoFail () at /var/tmp/portage/dev-lang/python-3.4.3/work/Python-3.4.3/Modules/gcmodule.c:1638
#17 0x00007ffff7a6f4a0 in PyImport_Cleanup () at /var/tmp/portage/dev-lang/python-3.4.3/work/Python-3.4.3/Python/import.c:536
#18 0x00007ffff7a7bb64 in Py_Finalize () at /var/tmp/portage/dev-lang/python-3.4.3/work/Python-3.4.3/Python/pythonrun.c:616
#19 0x00007ffff7a93014 in Py_Main (argc=0, argv=0x0) at /var/tmp/portage/dev-lang/python-3.4.3/work/Python-3.4.3/Modules/main.c:771
#20 0x0000000000400b06 in main (argc=4, argv=<optimized out>) at /var/tmp/portage/dev-lang/python-3.4.3/work/Python-3.4.3/Modules/python.c:69
(gdb) py-bt-full 
#15 Garbage-collecting
(gdb) 
```

**Comment by flacjacket** [comment]
See if #702 does the trick, I was able to get it working for me, so at least one of the segfaults should be cleared up. I tried to make the GObject stuff finalize nicely, but I don't know if I got it right, and I don't have it installed right now to check.

**Comment by flacjacket** [comment]
I don't think daemonizing the gobject thread is the right thing to do here, it should be shut down properly. The changes I just pushed were able to clear up the segfault with the back trace posted above, though I haven't yet tried to reproduce the xcffib segfault

**Pull request closed without merging**
