### PR TITLE
Pin pywlroots to 0.16.4 and skip StatusNotifier tests

### PR DESCRIPTION
**Pull request by jwijenbergh**
title

### CODE REVIEW

**Comment by elParaguayo** [comment]
@m-col @flacjacket Do either of you know why we're getting segfaults with latest pywlroots update?

**Comment by elParaguayo** [comment]
If this passes then this should be squashed and merged.

@jwijenbergh if the Statusnotifier tests keep failing then just disable them in tox and I'll fix them later (if we get a coverage failure because coverage has dropped too much as a result then that can be ignored too.)

**Comment by elParaguayo** [comment]
Ok Statusnotifier failed again. Let's just disable that test.

I've been working on a replacement test but let's not hold things up for that.

**Comment by jwijenbergh** [comment]
I have also pinned it in setup.cfg but maybe that's not needed. But maybe good that we're consistent

**Comment by jwijenbergh** [comment]
> Ok Statusnotifier failed again. Let's just disable that test.
> 
> I've been working on a replacement test but let's not hold things up for that.

I removed the whole file

**Comment by elParaguayo** [comment]
That will break the docs as the screenshot imports some parts from the test.

You might be better skipping the test.

**Comment by jwijenbergh** [comment]
> That will break the docs as the screenshot imports some parts from the test.
> 
> You might be better skipping the test.

Oh I now removed the wait for icon, not good like this?

**Comment by jwijenbergh** [comment]
Okay nvm they're now skipped, thanks

**Comment by m-col** [comment]
Probably worth updating the docs too, where we have the supported pywlroots version range listed?

**Comment by elParaguayo** [comment]
Ok. So I need to unpin this in the packaging PR.

**Pull request merged**
