### PR TITLE
Set group.current_window to self in Window.focus

### LINKED ISSUE #2495: window.focus() does not necessarily update focus_history
# Issue description

When using `qtile.current_window.focus(warp=False)` (or `warp=True`), the `current_group.focus_history` list is not necessarily updated, particularly in the case of floating windows. 

This is particularly important as the definition of `current_window` gets defined by the `focus_history` list.

# Qtile version

0.17.0

To demonstrate, I have a function that switches between "normal" windows and floating windows (akin to i3's `focus mode_toggle` command).

## Using `group.focus(window)`:
The following works as expected
```python
def toggle_focus_floating():
    '''Toggle focus between floating window and other windows in group'''

    @lazy.function
    def _toggle_focus_floating(qtile):
        group = qtile.current_group
        switch = 'non-float' if qtile.current_window.floating else 'float'
        logger.warning(f'toggle_focus_floating: switch = {switch}\t current_window: {qtile.current_window}')
        logger.warning(f'focus_history: {group.focus_history}')

        for win in reversed(group.focus_history):
            logger.warning(f'{win}: {win.floating}')
            if switch=='float' and win.floating:
                group.focus(win)
                return
            if switch=='non-float' and not win.floating:
                group.focus(win)
                return
    return _toggle_focus_floating
```
20210601_qtile_toggle_floating_correct

<details>
<summary>Log Output</summary>

```log
2021-06-01 10:09:44,012 WARNING libqtile lifecycle.py:_atexit():L34 Restarting Qtile with os.execv(...)
2021-06-01 10:09:44,503 WARNING libqtile config.py:<module>():L28 Number of monitors: 2
2021-06-01 10:10:02,099 WARNING libqtile functions.py:_toggle_focus_floating():L119 toggle_focus_floating: switch = float        current_window: Window('Terminal - ')
2021-06-01 10:10:02,100 WARNING libqtile functions.py:_toggle_focus_floating():L120 focus_history: [Window('Peek'), Window('KCharSelect'), Window('Terminal - ')]
2021-06-01 10:10:02,100 WARNING libqtile functions.py:_toggle_focus_floating():L124 Window('Terminal - '): False
2021-06-01 10:10:02,100 WARNING libqtile functions.py:_toggle_focus_floating():L124 Window('KCharSelect'): True
2021-06-01 10:10:03,568 WARNING libqtile functions.py:_toggle_focus_floating():L119 toggle_focus_floating: switch = non-float    current_window: Window('KCharSelect')
2021-06-01 10:10:03,568 WARNING libqtile functions.py:_toggle_focus_floating():L120 focus_history: [Window('Peek'), Window('Terminal - '), Window('KCharSelect')]
2021-06-01 10:10:03,568 WARNING libqtile functions.py:_toggle_focus_floating():L124 Window('KCharSelect'): True
2021-06-01 10:10:03,568 WARNING libqtile functions.py:_toggle_focus_floating():L124 Window('Terminal - '): False
2021-06-01 10:10:04,924 WARNING libqtile functions.py:_toggle_focus_floating():L119 toggle_focus_floating: switch = float        current_window: Window('Terminal - ')
2021-06-01 10:10:04,924 WARNING libqtile functions.py:_toggle_focus_floating():L120 focus_history: [Window('Peek'), Window('KCharSelect'), Window('Terminal - ')]
2021-06-01 10:10:04,924 WARNING libqtile functions.py:_toggle_focus_floating():L124 Window('Terminal - '): False
2021-06-01 10:10:04,925 WARNING libqtile functions.py:_toggle_focus_floating():L124 Window('KCharSelect'): True
2021-06-01 10:10:06,294 WARNING libqtile functions.py:_toggle_focus_floating():L119 toggle_focus_floating: switch = non-float    current_window: Window('KCharSelect')
2021-06-01 10:10:06,295 WARNING libqtile functions.py:_toggle_focus_floating():L120 focus_history: [Window('Peek'), Window('Terminal - '), Window('KCharSelect')]
2021-06-01 10:10:06,295 WARNING libqtile functions.py:_toggle_focus_floating():L124 Window('KCharSelect'): True
2021-06-01 10:10:06,295 WARNING libqtile functions.py:_toggle_focus_floating():L124 Window('Terminal - '): False
```

</details>

## Using `window.focus(warp)`
The following does not work as expected:
```python
def toggle_focus_floating():
    '''Toggle focus between floating window and other windows in group'''

    @lazy.function
    def _toggle_focus_floating(qtile):
        group = qtile.current_group
        switch = 'non-float' if qtile.current_window.floating else 'float'
        logger.warning(f'toggle_focus_floating: switch = {switch}\t current_window: {qtile.current_window}')
        logger.warning(f'focus_history: {group.focus_history}')

        for win in reversed(group.focus_history):
            logger.warning(f'{win}: {win.floating}')
            if switch=='float' and win.floating:
                win.focus(warp=False)
                return
            if switch=='non-float' and not win.floating:
                win.focus(warp=False)
                return
    return _toggle_focus_floating
```

Here, the focus does successfully change to the floating window, but `current_window` does not change since `focus_history` is not updated.
20210601_qtile_toggle_floating_incorrect

<details>
<summary>Log Output</summary>

```log
2021-06-01 10:14:50,048 WARNING libqtile functions.py:_toggle_focus_floating():L119 toggle_focus_floating: switch = float        current_window: Window('Terminal - ')
2021-06-01 10:14:50,049 WARNING libqtile functions.py:_toggle_focus_floating():L120 focus_history: [Window('Peek'), Window('KCharSelect'), Window('Terminal - ')]
2021-06-01 10:14:50,049 WARNING libqtile functions.py:_toggle_focus_floating():L124 Window('Terminal - '): False
2021-06-01 10:14:50,049 WARNING libqtile functions.py:_toggle_focus_floating():L124 Window('KCharSelect'): True
2021-06-01 10:14:51,777 WARNING libqtile functions.py:_toggle_focus_floating():L119 toggle_focus_floating: switch = float        current_window: Window('Terminal - ')
2021-06-01 10:14:51,777 WARNING libqtile functions.py:_toggle_focus_floating():L120 focus_history: [Window('Peek'), Window('KCharSelect'), Window('Terminal - ')]
2021-06-01 10:14:51,778 WARNING libqtile functions.py:_toggle_focus_floating():L124 Window('Terminal - '): False
2021-06-01 10:14:51,778 WARNING libqtile functions.py:_toggle_focus_floating():L124 Window('KCharSelect'): True
2021-06-01 10:14:53,367 WARNING libqtile functions.py:_toggle_focus_floating():L119 toggle_focus_floating: switch = float        current_window: Window('Terminal - ')
2021-06-01 10:14:53,367 WARNING libqtile functions.py:_toggle_focus_floating():L120 focus_history: [Window('Peek'), Window('KCharSelect'), Window('Terminal - ')]
2021-06-01 10:14:53,367 WARNING libqtile functions.py:_toggle_focus_floating():L124 Window('Terminal - '): False
2021-06-01 10:14:53,368 WARNING libqtile functions.py:_toggle_focus_floating():L124 Window('KCharSelect'): True
```

</details>

# Other things to note
Note that for the above GIFs, `cursor_warp = False` in my `config.py`. So for the `window.focus()` example, the cursor warps to the _previously_ focused window instead of the new one, while the `group.focus(window)` warps the cursor to the newly focused window. The warping is desired (I was planning on manually implementing it), but I'm not sure why it's happening.

### PR DESCRIPTION
**Pull request by m-col**
This lets the group update its focus history.

Fixes #2495

### CODE REVIEW

**Review by ramnes — APPROVED** [review]

**Comment by m-col** [comment]
@cnekmp I can't see your comment, so did you delete it? In which case, did you find the issue?

**Comment by cnekmp** [comment]
> @cnekmp I can't see your comment, so did you delete it? In which case, did you find the issue?

Yeah sorry about that. I have a strange issues with latest update on Arch (and qtile-git). My keyboard stops responding, while no logs are produced. But I can switch to another tty and keyboard works there. I don't know if it's related to this qtile upgrade, so I'm investigating the issue. I'll inform if I'll find the source of issue

**Comment by m-col** [comment]
When did you update? What commit are you on?

**Comment by cnekmp** [comment]
On this one. (qtile-git). Updated about hour ago

**Comment by m-col** [comment]
Do you know which commit you were on before / when you updated last?

**Comment by cnekmp** [comment]
[2021-07-16T13:07:21+0400] [ALPM] upgraded qtile-git (4252.dff41d7d-1 -> 4255.02348906-1)

**Comment by cnekmp** [comment]
I don't know what causes this issue. Keyboard just stops working and there is no logs generated in journald, Xorg, qtile.log, dmesg. While I can log into tty2 (ctrl+alt+f2) and type normally.

**Comment by m-col** [comment]
Any chance you could run qtile from commit 620d12d2d9189e2f76c21a697cd0e1ac60a1dc64 and see if it persists? It does make a change with some of the handling of X keyboard events so it's the most likely cause here I think.

**Comment by cnekmp** [comment]
I've downgraded to `dff41d7d` and it works normally. How can I test exactly `620d12d` commit via PKGBUILD? When I change version, it automatically downloads the latest commit.
```
Jul 15 21:10 qtile-git-4252.dff41d7d-1-any.pkg.tar.zst
Jul 16 13:07 PKGBUILD
Jul 16 13:07 qtile-git-4255.02348906-1-any.pkg.tar.zst
```

```
# Maintainer: roger <roger@rogerpc.com.ar>

pkgname=qtile-git
pkgver=4255.02348906
pkgrel=1
pkgdesc="A full-featured, pure-Python tiling window manager. (git version)"
arch=('any')
url="http://www.qtile.org"
license=('MIT')
depends=('python' 'pango' 'python-xcffib' 'python-cairocffi')
makedepends=('python-setuptools' 'git')
optdepends=('python-setproctitle: change the process name to qtile')
provides=('qtile')
conflicts=('qtile')
install=${pkgname}.install
source=('git://github.com/qtile/qtile.git')
md5sums=('SKIP')

_gitname="qtile"

pkgver() {
  cd $_gitname
  echo $(git rev-list --count HEAD).$(git rev-parse --short HEAD)
}

package() {
  cd $_gitname
  # license
  msg "Copying license..."
  install -D -m 644 LICENSE $pkgdir/usr/share/licenses/$pkgname/LICENSE

  msg "Copying default config..."
  install -D -m 644 $srcdir/$_gitname/libqtile/resources/default_config.py $pkgdir/usr/share/doc/$pkgname/default_config.py

  msg "Copying desktop file..."
  install -D -m 644 $srcdir/$_gitname/resources/qtile.desktop $pkgdir/usr/share/xsessions/qtile.desktop

  # install
  msg "Running setup.py"
  python setup.py install --root=${pkgdir} --prefix=/usr
}
```

**Comment by tych0** [comment]
You might try just `pip install .` on a checked out repo, and not use
the arch stuff to install it.

**Comment by cnekmp** [comment]
Ok, I've tested build [620d12d](https://github.com/qtile/qtile/commit/620d12d2d9189e2f76c21a697cd0e1ac60a1dc64) and can confirm that keyboard inputs stops working exactly at this commit.

P.S. PKGBUILD line should be changed to this for building that commit:
```
source='git://github.com/qtile/qtile.git#commit=620d12d2d9189e2f76c21a697cd0e1ac60a1dc64')

```

**Comment by tych0** [comment]
Sounds like we should just revert it; do you want to send the revert?

**Comment by m-col** [comment]
https://github.com/qtile/qtile/pull/2625

**Pull request merged**
