### PR TITLE
check_update widget uses a FreeBSD deprecated command

### PR DESCRIPTION
**Pull request by fjpavon**
To fix the issue #4907 the check command it's changed
the widget use the new command and the output is filtered using awk to get a line for each packates. This lines begin with a tab

### CODE REVIEW

**Comment by elParaguayo** [comment]
Thanks.

Will this break anything for users on an earlier version of FreeBSD or has this command been available for a while?

**Comment by fjpavon** [comment]
Yes, we are changing the command used to check the updates but the previous command was deprecated in FreeBSD 10.0 and it was published in January 20, 2014 [FreeBSD Releases](https://www.freebsd.org/releases/).

**Comment by tych0** [comment]
These xkbcommon build failures are not your fault, I will try to take a look soon. Looks like maybe a new constant, and our CI version of libxkb is too old.

**Comment by elParaguayo** [comment]
Need to pin xkbcommon version in CI.

https://github.com/sde1000/python-xkbcommon/issues/23

**Comment by tych0** [comment]
It looks like we can also move to 24.04 and make it work? I am trying that here: https://github.com/tych0/qtile/tree/ci-ubuntu-2404

**Comment by elParaguayo** [comment]
That would be better!

**Pull request merged**
