### PR TITLE
camelCase removal + pep8-naming

### LINKED ISSUE #1233: camelCase removal
Before anything, sorry for being "that guy". :smile: 

To be honest I don't like camelCase, but what I don't like even more is inconsistency. I've always had the feeling that there was a lot of camelCase names in Qtile codebase, which annoyed me, but I also had the feeling that there was even more snake_case, and thus that we should agree on a coding style once for all.

So I conducted a brief analysis of `libqtile`, and it showed me that there are 95 unique names (54 functions and 41 variable) that are written in camelCase. Those 95 names are used 669 times. Here they are:

`addGroup`, `addHandler`, `appendHead`, `archivedInput`, `backupCount`, `borderWidth`, `captureWarnings`, `clientFromWID`, `colorPixel`, `columnHeight`, `columnWidth`, `curGroup`, `currentGroup`, `currentLayout`, `currentOffset`, `currentScreen`, `currentStack`, `currentStackOffset`, `currentWindow`, `cursorId`, `customLayout`, `deleteCurrentStack`, `delGroup`, `disableMask`, `displayName`, `displayNum`, `docSig`, `docText`, `eventEvents`, `focusHistory`, `formatSelector`, `funcName`, `getAttribute`, `getElementsByTagNameNS`, `getEssid`, `getIconPath`, `getLogger`, `getOpacity`, `grabKeys`, `grabMouse`, `groupMap`, `groupName`, `ignoreEvents`, `iTouch`, `keyMap`, `layoutAll`, `layoutChanged`, `listWID`, `maildirPath`, `mapKey`, `masterWindows`, `maxBytes`, `mouseMap`, `moveToGroup`, `nextGroup`, `nextLayout`, `nextSelector`, `nextStack`, `nodeIdx`, `numlockMask`, `parseString`, `prevGroup`, `previousStack`, `prevLayout`, `registerWidget`, `removeHandler`, `resetMaster`, `rRmazA`, `screenHeight`, `screenWidth`, `sectionIdx`, `setFormatter`, `setGroup`, `setLevel`, `setOpacity`, `shuffleDown`, `shuffleUp`, `stackOffset`, `startInput`, `subFolder`, `subFolders`, `terminalWidth`, `toggleSplit`, `toLayoutIndex`, `toScreen`, `unmapKey`, `updateHints`, `updateName`, `updateState`, `userInput`, `validMask`, `widgetMap`, `windowMap`, `winHeight`

To get the list: `grep -Rh -Po '[^A-z]\K[a-z]+[A-Z][A-Za-z]+' | sort -u`.

In comparison, there are 1590 names in snake_case, which are used 5923 times (`grep -Rh -Po '[^A-z]\K[a-z]+[_][a-z_]+'`.

What is annoying here is that those 95 camelCase names are pretty important, and that a lot of them might be used in config files hacks or other user scripts, even if none of them actually is something publicly exposed by `libqtile` modules. So basically, renaming all those wouldn't be a `!!! config breakage !!!` per se, but still might end up breaking a lot of stuff on the user side.

The other annoying thing is that I don't feel like adding a deprecation warning for those 54 functions.

And yet, I really want to make the codebase cleaner, easier to maintain, make the coding style enforceable, all of that so that it's overall more welcoming to new contributors.

So how should we proceed to do that renaming, if we want to?

*Edit:* if we decide to move forward on this, should we also rename stuff like `togroup` into `to_group`, or `cw` to `current_window`? It's much less important as it doesn't directly break the PEP 8, but still, I'd love this.

### PR DESCRIPTION
**Pull request by ramnes**
Fixes #1233 

Stuff I did not modify on purpose:

```bash
./libqtile/config.py:groupName # argument of cmd_toggle_group
./libqtile/layout/tile.py:masterWindows # argument of Tile
./libqtile/log_utils.py:addHandler # logging stuff
[...]
./libqtile/widget/keyboardkbdd.py:layoutChanged # dbus signal name
./libqtile/widget/launchbar.py:getIconPath # xdg stuff
./libqtile/widget/maildir.py:maildirPath # argument of Maildir
[...]
./libqtile/widget/wlan.py:getEssid # python-wifi stuff
./libqtile/widget/yahoo_weather.py:getAttribute # xml stuff
[...]
./libqtile/window.py:groupName # argument of cmd_togroup
./libqtile/xkeysyms.py:iTouch # actual xkeysim
```

I'd like to keep the commits separated (i.e. not squash them) on this one so that we can revert a single one if we bisect a problem.

### CODE REVIEW

**Comment by tych0** [comment]
+1 on keeping them separated. Is there some automatic checking we can do too?

Thanks for doing this!

**Comment by ramnes** [comment]
https://github.com/PyCQA/pep8-naming seems to work pretty well and gave me more things to change, so I'll change them and add the plugin into the tox environment.

**Comment by Ryuno-Ki** [comment]
@ramnes Wow, that touches really a lot of places. But there's a merge conflict :-(

**Comment by ramnes** [comment]
@Ryuno-Ki: I guess that pretty much any commit that we'll add to the develop branch before merging this will create a conflict. :smile: 

@tych0: done, `pep8-naming` has been added to tox, and thus enforcing the rules. :+1:

**Comment by tych0** [comment]
+1 on this, thanks! Did you guys want to tag a release before we merged this?

**Comment by ramnes** [comment]
We discussed about it with @flacjacket and decided to merge as much of the open pull requests as possible, make a release, and then merge this.

**Comment by cortesi** [comment]
The ghost of Christmas past has rebased and pushed for you. Thanks!

**Comment by ramnes** [comment]
Wow, thanks a bunch @cortesi!

**Pull request closed without merging**
