### PR TITLE
Gentoo installation docs

### PR DESCRIPTION
**Pull request by buzz**
Proposing to reintroduce updated Gentoo install docs removed in e7aeaf71ba0ee442417fbe4de8d5883650dd8e36

### CODE REVIEW

**Comment by ramnes** [comment]
We have qtile-9999 on portage, so getting qtile-0.9.1 from a layman seems a bit useless to me. Though, it could be interesting to have qtile-0.9.1 on portage. Ping @radhermit.

**Comment by fkmclane** [comment]
The qtile-9999 ebuild is actually out of date and, while I haven't tried it, probably won't work. It still depends on PyGTK, does not depend on an asyncio implementation for Python <3.4 (such as trollius which is also not in portage), and does not mark support for Python 3.

**Comment by buzz** [comment]
I agree that having qtile-0.9.1 in portage would be optimal. Until that happens people can use the overlay. qtile-9999 didn't work for me. Anyway I'd prefer to use the latest stable release not the dev branch.

**Comment by ramnes** [comment]
Well, I'm using this ebuild actually. But yeah, now I remember that I had to install one or two dependencies myself.

**Comment by radhermit** [comment]
Or you could try this in about an hour or so, emerge --sync && emerge qtile ;)

For future reference, it can be helpful to attach ebuilds or patches to bugs.gentoo.org if you want to speed things up.

**Comment by ramnes** [comment]
Awesome, thanks @radhermit!

**Comment by tych0** [comment]
Going to close this in favor of the ebuild. Thanks!

**Pull request closed without merging**
