### PR TITLE
Decode to utf-8 only in py3 to fix a py2 UnicodeDecodeError

### PR DESCRIPTION
**Pull request by flacjacket**
This addresses a problem reported by kiiruchu on IRC:

    15:51:05 <kiiruchu> On a different note, I had to revert https://github.com/qtile/qtile/commit/eb2ebb9b3b3d32e6ab03a7be2c26497199b7b3b1#diff-2 to get the thermal sensor-widget working.
    15:51:52 <kiiruchu> Otherwise I would get a UnicodeDecodeError. http://pastebin.com/JGqDTvfV

### CODE REVIEW

**Comment by flacjacket** [comment]
We may or may not want to do this for the other places subprocess output is processed.

**Comment by tych0** [comment]
Yeah, maybe we should just write our own subprocess wrapper and just use that everywhere? I can either merge this, or if you're willing to do that I can wait and merge that instead.

**Comment by flacjacket** [comment]
I can look and try to change what I think could be offending cases

**Comment by flacjacket** [comment]
Alright, this should be good to go.

**Comment by flacjacket** [comment]
Just pushed it

**Pull request merged**
