### PR TITLE
x11: use either WM_TAKE_FOCUS or SetInputFocus(), not both

### PR DESCRIPTION
**Pull request by tych0**
Idea for the fix stolen from:

https://github.com/i3/i3/commit/21a2971b2442ab0881cf79553cc6b65bbb44afa7

Hopefully this fixes the last of the java focus issues.

Signed-off-by: Tycho Andersen <tycho@tycho.ws>

### CODE REVIEW

**Comment by pawamoy** [comment]
TAKE MY MONEY! Thank you so much @tych0, it makes JetBrains product usable again :sob:

**Comment by tych0** [comment]
I wonder if this isn't also related to #1735, which seems like it's a race of some kind as well.

**Comment by pawamoy** [comment]
There's always a price to pay... I cannot focus this little `gmrun` window:

```
_NET_WM_USER_TIME(CARDINAL) = 5511537
_NET_WM_DESKTOP(CARDINAL) = 1
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		window id # of group leader: 0x1c00001
XdndAware(ATOM) = BITMAP
_MOTIF_DRAG_RECEIVER_INFO(_MOTIF_DRAG_RECEIVER_INFO) = 0x6c, 0x0, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x10, 0x0, 0x0, 0x0
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x2, 0x0, 0x0
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 29360133
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x1c00004
WM_CLIENT_LEADER(WINDOW): window id # 0x1c00001
_NET_WM_PID(CARDINAL) = 64030
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "corsair"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 0
		program specified minimum size: 412 by 75
		program specified maximum size: 412 by 75
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "gmrun", "Gmrun"
WM_ICON_NAME(STRING) = "Execute program feat. completion"
_NET_WM_ICON_NAME(UTF8_STRING) = "Execute program feat. completion"
WM_NAME(STRING) = "Execute program feat. completion"
_NET_WM_NAME(UTF8_STRING) = "Execute program feat. completion"
```

**Comment by tych0** [comment]
Looks like the i3 code only does a _NET_ACTIVE_WINDOW update when in WM_TAKE_FOCUS mode, does this help? https://github.com/tych0/qtile/commit/b3e255ee78975878f56a9bfbef9088a9cacd2b94

**Comment by pawamoy** [comment]
No :confused:

**Comment by tych0** [comment]
Is it floating by default? I wonder if the `if not hidden` is causing problems.

**Comment by pawamoy** [comment]
It's floating by default, yes, and I tried everything to prevent floating it, but nothing worked. I disabled every `float_rules` in the floating layout, and even forced `window.floating = False` in a `client_new` hook, but it still floats when I launch it.

**Comment by ramnes** [comment]
@pawamoy are you sure that your floating window input problems are related to this PR specifically? I think I had the same problem today but I wasn't using this branch (I was on ae354a27eafda53316973f35db0363eaec686c38).

**Comment by pawamoy** [comment]
Ah, maybe indeed. I thought gmrun was working fine before I tried the PR, but I was not using master before, so it might have been introduced in another commit. I'll try to bisect this.

**Comment by pawamoy** [comment]
Bisected to 0f886606e1f35226b325f5405d43946976eae831 :slightly_smiling_face:

**Comment by zordsdavini** [comment]
Thank you @tych0 for this job. All comunity that use Jetbrains products does crazy :tada:

**Comment by zordsdavini** [comment]
@tych0 it looks like I merged it in wrong way - I've stolen your authority :-/ sorry

**Comment by tych0** [comment]
Ha, no worries. I'd just switch to using a rebase for qtile, it makes the history cleaner.

**Comment by flacjacket** [comment]
So it looks like this breaks the qt pinentry program, when it launches it does not take input if there is another window running, but if it is the only window running on a layout, then it does take input. So when I gpg sign something from my terminal and the window launches, even when the pinentry window is focused, typing will go to the terminal, if i then move the terminal off the screen, the popup will take input.

xprop:
```
_NET_WM_USER_TIME(CARDINAL) = 8641295
_NET_WM_DESKTOP(CARDINAL) = 1
WM_STATE(WM_STATE):
                window state: Normal
                icon window: 0x0
_NET_WM_STATE(ATOM) = _NET_WM_STATE_ABOVE, _NET_WM_STATE_MODAL, _NET_WM_STATE_STAYS_ON_TOP
WM_TRANSIENT_FOR(WINDOW): window id # 0x2400008
_NET_WM_ICON_NAME(UTF8_STRING) =
_NET_WM_ICON(CARDINAL) =        Icon (48 x 48):


                             ░░   ░░
                          ░          ░
                         ░  ░░░░░░▒░░
                        ░ ░░░░░░░░░░░▒
                       ░ ░░░░      ░░░▒
                      ░ ░░░         ░░░▒
                     ░░░░░            ░░░
                     ░░░░░            ░░░
                      ░░░              ░░░
                    ░ ░░░              ░░░
                    ░ ░░░              ░░░
                    ░ ░░                ░░
                    ░ ░░                ░░
                    ░ ░░                ░░
                    ░ ░░                ░░
                    ░ ░░                ░░
                    ░ ░░                ░░
                    ░ ░░                ░░
                    ░ ░░                ░░
                 ░  ░░░░░░░░░▒▒▒▒▒▒▒░░░░░░░░  ░
                 ░   ░░░░░░░░░▒▒▒▒░░░░░░░░    ░
                 ░    ░░░░░░░░░░░░░░░░░░░     ░
                 ░   ░░░░░░░░░░░░░░░░░░░░     ░
                 ░    ░░░░░░░░░░░░░░░░░░░     ░
                 ░    ░░░░░░░░░░░░░░░░░░░     ░
                 ░   ░░░░░░░░░░░░░░░░░░░░     ░
                 ░   ░░░░░░░░░░░░░░░░░░░░     ░
                 ░    ░░░░░░░░░░░░░░░░░░░     ░
                 ░    ░░░░░░░░░░░░░░░░░░░     ░
                 ░    ░░░░░░░░░░░░░░░░░░░     ░
                 ░   ░░░░░░░░░░░░░░░░░░░░     ░
                 ░    ░░░░░░░░░░░░░░░░░░░     ░
                 ░    ░░░░░░░░░░░░░░░░░░░     ░
                 ░    ░░░░░░░░░░░░░░░░░░░     ░
                 ░    ░░░░░░░░░░░░░░░░░░      ░
                 ░    ░░░░░░░░░░░░░░░░░░░     ░
                 ░    ░░░░░░░░░░░░░░░░░░░     ░
                 ░    ░░░░░░░░░░░░░░░░░░░     ░
                 ░    ░░░░░░░░░░░░░░░░░░░     ░
                 ░    ░░░░░░░░░░░░░░░░░░░     ░
                 ░    ░░░░░░░░░░░░░░░░░░      ░
                 ░    ░░░░░░░░░░░░░░░░░░      ░
                 ░    ░░░░░░░░░░░░░░░░░░      ░

                        ░░░░░░░░░░░░░░░░░



XdndAware(ATOM) = BITMAP
WM_NAME(STRING) = "[1714]@hera"
_NET_WM_NAME(UTF8_STRING) = "[1714]@hera"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x26, 0x1e, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_NORMAL
_XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
WM_CLIENT_LEADER(WINDOW): window id # 0x2400008
WM_HINTS(WM_HINTS):
                Client accepts input or input focus: True
                window id # of group leader: 0x2400008
WM_CLIENT_MACHINE(STRING) = "hera"
_NET_WM_PID(CARDINAL) = 1716
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 37748743
WM_CLASS(STRING) = "pinentry", "pinentry"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                user specified location: 1060, 589
                user specified size: 420 by 182
                program specified minimum size: 420 by 182
                program specified maximum size: 420 by 182
                window gravity: Static
```

**Comment by tych0** [comment]
Do you have a07667bf8586e642b6b32d34e920a94e417a4aa1 and db0f044f8968f4bccad006fb001a87a98742c9a0 too? Those are both probably/likely necessary.

**Comment by flacjacket** [comment]
Yes, this is off current master.

**Comment by pawamoy** [comment]
For me pinentry-gtk-2 is working fine (correctly focused even when opened above an existing window like a terminal).

**Pull request merged**
