### PR TITLE
Allow resizing of Drawer() internal pixmaps

### PR DESCRIPTION
**Pull request by DorianGray**
drawer.width is set in Popup when the Popup's width changes.
Unfortunately, the underlying drawing surface on X(pixmap) is not
resized. It doesn't seem like they can be resized after reading the x
proto docs. Cairo to the rescue! Cairo implements a RecordingSurface
that we can use locally while the underlying Drawable may not be
accessible. These changes make the Drawer write to a RecordingSurface
and only copy to the pixmap on Drawer.draw.

This also fixes our random segfaults in CI since the XCBSurface is
created on draw instead of on __init__

### CODE REVIEW

**Comment by DorianGray** [comment]
This ended up much more involved than my original PR, but I am confident this is much closer to the right solution.

Turns out that while surfaces and contexts allow changing their drawables, there isn't a way to manage the drawable lifecycle outside of . Luckily I came across RecordingSurface which is meant exactly for this. It stages cairo operations in memory and can be replayed on another surface. This allows us to manage a pixmap(drawable) lifecycle that works for us while maintaing ease of use for clients of Drawer.

**Comment by DorianGray** [comment]
This now also depends on https://github.com/qtile/qtile/pull/2046

**Comment by DorianGray** [comment]
This seems to also fix the random segfaults by proxy, since creating an xcbsurface too early was the problem.

**Review by ramnes — APPROVED** [review]
LGTM

**Comment by ramnes** [comment]
Just reverted it, it breaks my bar:

broken-bar

It should look like this:

normal-bar

@m-col seems to have problems as well:

```
12h05 mcol i think that last commit (the Drawer resize one) might have some problems
12h05 mcol i just had to remove it from my live branch
12h06 mcol completely slowed down everything, and pretty sure it pumped my CPU a lot too for some reason
12h06 mcol could it be blocking qtile at times?
```

**Comment by ramnes** [comment]
```
2021-01-05 15:13:20,236 ERROR libqtile manager.py:handle_exception():L64 'Drawer' object has no attribute 'pixmap'
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "libqtile/core/manager.py", line 905, in f
    logger.error('Switching to ERROR threshold')
  File "libqtile/bar.py", line 376, in _actual_draw
    i.draw()
  File "libqtile/widget/systray.py", line 189, in draw
    icon.window.set_attribute(backpixmap=self.drawer.pixmap)
AttributeError: 'Drawer' object has no attribute 'pixmap'
```

**Pull request merged**
