### PR TITLE
Move command_*.py into new command module

### PR DESCRIPTION
**Pull request by DorianGray**
It kind of defeats the purpose of the module system to prefix module
names.

### CODE REVIEW

**Comment by DorianGray** [comment]
@m-col suggested I add a deprecation warning for the old imports in irc.

**Comment by flacjacket** [comment]
This is a much nicer structure here, thanks!

**Review by flacjacket — APPROVED** [review]

**Comment by tych0** [comment]
Can you also add a note to the CHANGELOG about breakage?

**Comment by DorianGray** [comment]
Done

**Comment by m-col** [comment]
I think only the `command_client` and `command_interface` modules need to continue working, the others are just used internally.

Could you also update the docs? Specifically [this page](http://docs.qtile.org/en/latest/manual/commands/index.html) and [this page](http://docs.qtile.org/en/latest/manual/commands/scripting.html)?

**Comment by DorianGray** [comment]
Done =)

**Review by ramnes — APPROVED** [review]

**Comment by m-col** [comment]
Thanks!

**Pull request merged**
