### PR TITLE
Adds .vscode/ to the .gitignore file.

### PR DESCRIPTION
**Pull request by oboingo**
Adds .vscode/ to the .gitignore file.  This would ignore vscode specific config files (similar to .idea/ for intellij IDEs).

### CODE REVIEW

**Comment by tych0** [comment]
Can you drop the other git merge commits?

**Comment by tych0** [comment]
And FWIW, I would add this type of stuff to your global gitignore: https://gist.github.com/subfuzion/db7f57fff2fb6998a16c

But I'm happy to have it in the tree too.

**Comment by oboingo** [comment]
Oh!  Well you learn something everyday!  I would say that we don't need this PR then!

**Comment by ramnes** [comment]
Merging, it's still great for new contributors that do not have git configured, and also we already have some other editor directories ignored so why not more. :)

**Pull request merged**
