### PR TITLE
Fixed CurrentLayoutIcon to work with Python 3

### PR DESCRIPTION
**Pull request by and3rson**
- [x] `types.ClassType` -> `six.class_types`

### CODE REVIEW

**Comment by and3rson** [comment]
@ramnes Sounds reasonable. I've reverted it back to `map()`.

**Comment by and3rson** [comment]
@ramnes there seems to be some unrelated flake8 validation problem in mpd2widget, thus the build is failing

**Comment by and3rson** [comment]
@flacjacket @ramnes any info?

**Comment by flacjacket** [comment]
It looks like a Travis update of pycodestype from 2.0 to 2.2 broke the master build, I'll fix that and merge this in, thanks!

**Pull request merged**
