### PR TITLE
Added a text-style highlighting current group

### PR DESCRIPTION
**Pull request by alozovskoy**
Added a text-style highlighting current group (like in urgent_alert_method).

Example (green for current group, red for urgent and default in another):
example

### CODE REVIEW

**Comment by alozovskoy** [comment]
A some code in commit 4b768a9, please merge it.

**Comment by tych0** [comment]
On Thu, Mar 26, 2015 at 03:17:43AM -0700, alozovskoy wrote:
> A some code in commit 4b768a9, please merge it.

Sorry, can you make a new PR with the code you want merged?

Thanks.

**Comment by alozovskoy** [comment]
Sorry, i been mistaken when i put previous comment (and i delete it). At this time PR is alright! Thanks!

**Comment by tych0** [comment]
On Thu, Mar 26, 2015 at 07:54:20AM -0700, alozovskoy wrote:
> Sorry, i been mistaken when i put previous comment (and i delete it). At this time PR is alright! Thanks!

No problem.

**Pull request closed without merging**
