### PR TITLE
allow dgroups to persist

### PR DESCRIPTION
**Pull request by phragment**
- allow specifying if added group should be persistent

### CODE REVIEW

**Comment by phragment** [comment]
Thank you for considering this, I'm open to improvements (especially for the test cases).

**Comment by tych0** [comment]
Thanks!

**Comment by elParaguayo** [comment]
@phragment This is throwing up a minor bug - see #4933

It's weird because `client.group` seems to be `None` but the `_del` method can only be called if the client group is not None.

**Comment by phragment** [comment]
@elParaguayo I will take a look, maybe this is an x11/wayland issue.

**Comment by elParaguayo** [comment]
@phragment note, there's some discussion in #4933

**Comment by phragment** [comment]
I went through the mentioned issues discussions, it seems only to happen on x11 with systray (xembed windows).
At last that explains why I completely missed this potential issue. (I'm daily driving this qtile setup, but with the wlroots backend.)
I'm relieved to see the issue solved with https://github.com/qtile/qtile/pull/4941

**Pull request merged**
