### PR TITLE
Merge layouts wmii and columns

### PR DESCRIPTION
**Pull request by heitzmann**
Columns' default parameters are changed to reflect wmii's.
Rename columns to replace wmii.

Motivation: columns presents all features of wmii plus a few others, making wmii redundant. #1096

### CODE REVIEW

**Comment by ramnes** [comment]
Damn. Chances are high that this will break my [config](https://github.com/ramnes/qtile-config/blob/master/config.py), that I changed some days ago to use Columns, and for which I heavily rely on its implementation. :sob: 

From what I seem to see, you're reimplementing Columns inside WMII. What's the point of doing that versus simply removing the WMII layout?

**Comment by heitzmann** [comment]
@ramnes What this PR does is to remove Wmii and rename Columns to Wmii. It also changes the default parameters of Columns to match Wmii.
I chose to leave the Wmii name instead of Columns because it's been around for longer, so I thought it would break fewer configs out there...

If you're using Columns, just change to Wmii (in this PR) and modify any default parameters that might have been changed.

**Comment by flacjacket** [comment]
I haven't yet sat down and looked at the changes here, but my suggestion would be to leave both, and mark one of them as deprecated. For whichever one you choose to remove, you can just subclass the other and set the defaults to match the original behavior.

**Comment by heitzmann** [comment]
Sounds good @flacjacket 
I'll close this PR and open a new one with the deprecation warning.

**Pull request closed without merging**
