### PR TITLE
Fix test suite to not use the deprecated functions that were removed

### PR DESCRIPTION
**Pull request by dequis**

### CODE REVIEW

**Comment by aniruddhkanojia** [comment]
I did that already :stuck_out_tongue: 

Check [this](https://github.com/aniruddhkanojia/qtile/commit/552fcb79294bc494d21dc84991f91ca2eebb96c7#diff-ca32e58dcc959b662e758db399920788L732)

**Comment by dequis** [comment]
Oh. Okay. The title was of the PR was vague and you included two different fixes in the same commit.

**Comment by kynikos** [comment]
Yeah, 552fcb79294bc494d21dc84991f91ca2eebb96c7 should better be repushed in two commits I guess.

**Comment by aniruddhkanojia** [comment]
Creating a new branch and sending a PR from that , is the way to approach this , right ?

**Comment by kynikos** [comment]
Well, not necessarily if it's something *minor* like in this case, but it seems I've replied too late, and anyway, opening another request like you've done doesn't hurt :) Disclaimer: I don't speak ok behalf of the official project's maintainers.

**Pull request closed without merging**
