### PR TITLE
Fix CryptoTicker test

### PR DESCRIPTION
**Pull request by m-col**
83388a6 made some changes to this widget but CI was failing at the time, so this follow-up PR fixes the test for it.

### CODE REVIEW

**Comment by elParaguayo** [comment]
Not sure where all those mypy errors are coming from!

**Comment by m-col** [comment]
Ah yeah don't worry about those, it was an update in pywlroots. They'll be fixed by https://github.com/qtile/qtile/pull/3935, which I can rebase on top of this after merging and hopefully they'll all pass.

**Comment by m-col** [comment]
I merged the other PR that should fix the type checking so rebased this so now CI should pass completely here. If not, I can append more fixes so that when merging this, other PRs will start passing again

**Comment by m-col** [comment]
Nice this has fixed it all :)

**Comment by elParaguayo** [comment]
Thanks.

**Pull request merged**
