### PR TITLE
widget: net: add support for 'total' bandwidth value

### PR DESCRIPTION
**Pull request by ljmf00**
Signed-off-by: Luís Ferreira <contact@lsferreira.net>

---

Some users (like me) would like to have, instead of up and down values separately, sum it up altogether. This PR adds 'total' value for that purpose.

### CODE REVIEW

**Comment by elParaguayo** [comment]
This looks good to me.

Can you add something to the `defaults` section to show that the `total` key is also available for the `format` string:
https://github.com/qtile/qtile/blob/ea7216d9f4bf7dcce111c71d1a254bee7d8cd4ef/libqtile/widget/net.py#L40-L41

Don't change the default value though.

**Comment by ljmf00** [comment]
> This looks good to me.
> 
> Can you add something to the `defaults` section to show that the `total` key is also available for the `format` string:
> https://github.com/qtile/qtile/blob/ea7216d9f4bf7dcce111c71d1a254bee7d8cd4ef/libqtile/widget/net.py#L40-L41
> 
> Don't change the default value though.

I added `/total` to the `format` defaults description :)

**Review by m-col — APPROVED** [review]
Looks great, thanks! Maybe add a line to the changelog so that others might discover your addition? (You may need to add a new section for the next release in the changelog file)

**Comment by ljmf00** [comment]
> Looks great, thanks! Maybe add a line to the changelog so that others might discover your addition? (You may need to add a new section for the next release in the changelog file)

Added.

**Comment by m-col** [comment]
Awesome, thanks for this :smile:

**Pull request merged**
