### PR TITLE
Create a PWVolume widget

### PR DESCRIPTION
**Pull request by flexagoon**
The current Volume widget only works with PulseAudio. This PR adds a
modified version of it which works with Pipewire through pamixer.

### CODE REVIEW

**Comment by ramnes** [comment]
Before anything, please inherit from Volume so that most of the code isn't duplicated, and do that we can see what the difference is. Also, did you try the PulseVolume widget?

**Comment by flexagoon** [comment]
What's PulseVolume? It's not in the documentation

**Comment by ramnes** [comment]
> What's PulseVolume?

https://github.com/qtile/qtile/blob/master/libqtile/widget/pulse_volume.py

> It's not in the documentation

https://github.com/qtile/qtile/pull/2476

**Comment by grtcdr** [comment]
Any progress on this feature? I've had trouble in the past getting pamixer to display volume in the bar.

**Comment by elParaguayo** [comment]
Now in the docs: http://docs.qtile.org/en/latest/manual/ref/widgets.html#pulsevolume

**Comment by grtcdr** [comment]
> Now in the docs: http://docs.qtile.org/en/latest/manual/ref/widgets.html#pulsevolume

Great stuff! 🚀

**Comment by ramnes** [comment]
Alright, I'll go ahead and close this assuming that the PulseVolume widget works with Pipewire. Feel free to comment if it doesn't!

**Pull request closed without merging**
