### PR TITLE
GitHub actions

### PR DESCRIPTION
**Pull request by tych0**
See the second commit, but basically: travis has been painfully slow recently. Let's switch to github actions. A couple other maintenance tasks in here as well.

### CODE REVIEW

**Review by m-col — APPROVED** [review]
Looks good, and the tests were really fast! And having them already run on this PR is a nice test for the tests :-)

**Comment by tych0** [comment]
Yeah, the difference is substantial :)

**Review by ramnes — APPROVED** [review]
RIP Travis

**Comment by tych0** [comment]
Indeed. Travis was great for a long time, seems they abandoned the free version when github released actions. Who can blame them :(.

**Pull request merged**
