### PR TITLE
Floating windows obey wm below

### PR DESCRIPTION
**Pull request by yobleck**
Some floating windows with widget like behavior have the wm property `_NET_WM_STATE_BELOW`. This PR ensure that those windows stay behind other windows unless focused by the mouse or tasklist widget.

Adds `cmd_send_to_back()` to the window class (X only. IDK how wayland handles this).

I'm not sure how to go about testing window stack order. Does `_NET_CLIENT_STACKING_LIST` have anything to do with it?

### CODE REVIEW

**Comment by elParaguayo** [comment]
re CI jobs: there were some issues yesterday downloading wayland but, looking at your logs, you actually seem to be getting test failures and errors so I don't think it's the same issue.

I'm re-running CI to see what happens now but I suspect your changes do result in some wider impacts.

**Comment by m-col** [comment]
Have you looked at https://github.com/qtile/qtile/pull/2194 at all? I'm not sure how much your changes take us in that direction or solve the problem in a different way, but it might be taking a look because it would be awesome if we can use the work done in that PR. It is on the back-burner a bit until someone has some time to work on it, but there is a lot of great work in there to get proper Z-axis control.

**Comment by elParaguayo** [comment]
OK - I think the CI errors are as a result of your commit. Your tests consistently stop at the same point. I've re-run tests on a different PR and they all got past that point.

Looking at your CI logs, there are lots of Wayland failures/errors and the next tests to be run would be wayland ones (`test_manager.py::test_map_request` - the X11 versions of this test pass). I'm guessing they're starting but crashing and pytest can't recover.

**Comment by yobleck** [comment]
> there are lots of Wayland failures/errors

Well I can't get anything wayland related running (even though I'm pretty sure I have all the dependencies) so this PR might be a dud.

<details>
<summary>qtile start -b wayland traceback</summary>

```
Traceback (most recent call last):
  File "/usr/bin/qtile", line 33, in <module>
    sys.exit(load_entry_point('qtile==0.18.1.dev0+g8e7ecc0a.d20210719', 'console_scripts', 'qtile')())
  File "/usr/lib/python3.9/site-packages/libqtile/scripts/main.py", line 55, in main
    options.func(options)
  File "/usr/lib/python3.9/site-packages/libqtile/scripts/start.py", line 87, in start
    q = make_qtile(options)
  File "/usr/lib/python3.9/site-packages/libqtile/scripts/start.py", line 50, in make_qtile
    kore = libqtile.backend.get_core(options.backend)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/__init__.py", line 15, in get_core
    return importlib.import_module(f"libqtile.backend.{backend}.core").Core(*args)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/wayland/core.py", line 94, in __init__
    self.compositor, self.backend = wlroots_helper.build_compositor(self.display)
  File "/usr/lib/python3.9/site-packages/wlroots/helper.py", line 25, in build_compositor
    backend = Backend(display, backend_type=backend_type)
  File "/usr/lib/python3.9/site-packages/wlroots/backend.py", line 41, in __init__
    raise RuntimeError("Failed to create wlroots backend")
RuntimeError: Failed to create wlroots backend

```
</details>

**Pull request closed without merging**
