### PR TITLE
Get all tests to run during Arch packaging

### PR DESCRIPTION
**Pull request by elParaguayo**
These changes result in a clean build and execution of all tests in an Arch chroot [using a systemd-nspawn container](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot)

This has been painful. Main issue was getting `mypy`-related tests to run correctly. I'm not an expert so my "solution" may be totally inappropriate.

This also allowed me to cut down the Arch PKGBUILD too (@dvzrv FYI - you'll see I've cut the `check` section right down) - the `source` below is a branch on my fork which I used to test building/testing based off latest master.

``` shell
pkgname=qtile
pkgver=0.18.0
pkgrel=1
pkgdesc="A full-featured, pure-Python tiling window manager"
arch=('x86_64')
url="http://www.qtile.org"
license=('MIT')
depends=(
  'gdk-pixbuf2'
  'glibc'
  'librsvg'
  'pango'
  'python-cairocffi'
  'python-cffi'
  'python-xcffib'
)
makedepends=(
  'git'
  'libpulse'
  'python-setuptools'
  'python-setuptools-scm'
)
checkdepends=(
  'dbus'
  'graphviz'
  'gtk3'
  'imagemagick'
  'libnotify'
  'python-bowler'
  'python-dbus-next'
  'python-gobject'
  'python-pytest'
  'python-pywlroots'
  'python-xdg'
  'wlroots'
  'xorg-server-xephyr'
  'xorg-server-xvfb'
  'xorg-xrandr'
)
optdepends=(
  'alsa-utils: volume widget'
  'canto-daemon: canto widget'
  'cmus: cmus widget'
  'python-ipykernel: interaction with qtile via Jupyter'
  'jupyter_console: interaction with qtile via Jupyter'
  'khal: khal_calendar widget'
  'libpulse: for pulse_volume and pulseaudio_ffi widget'
  'lm_sensors: sensors widget'
  'moc: moc widget'
  'python-dbus-next: for utils, notifications and several widgets'
  'python-iwlib: wlan widget'
  'python-keyring: imapwidget widget'
  'python-mpd2: mpd2widget widget'
  'python-psutil: graph, net and memory widget'
  'python-pywayland: Wayland backend'
  'python-pywlroots: Wayland backend'
  'python-setproctitle: change process name to qtile'
  'python-xdg: launchbar widget'
  'python-xkbcommon: Wayland backend'
  'wlroots: Wayland backend'
  'xorg-server: X11 backend'
)
source=("git+https://github.com/elparaguayo/qtile#branch=arch-build-test")
md5sums=('SKIP')


build() {
  cd "${pkgname}"
  python setup.py build
  ./scripts/ffibuild
}

check() {
  cd "${pkgname}"

  export LC_TYPE=en_US.UTF-8
  export MYPYPATH="/build/${pkgname}/src/${pkgname}:/build/${pkgname}/src/${pkgname}/stubs"

  pytest -vv --backend x11 --backend wayland
}

package() {
  cd "${pkgname}"
  python setup.py install --skip-build \
    --optimize=1 \
    --root="${pkgdir}"
  # license
  install -vDm 644 LICENSE -t "${pkgdir}/usr/share/licenses/${pkgname}/"
  # config
  install -vDm 644 libqtile/resources/default_config.py \
    -t "${pkgdir}/usr/share/doc/${pkgname}/"
  # desktop file
  install -vDm 644 "resources/${pkgname}.desktop" \
    -t "${pkgdir}/usr/share/xsessions/"
  # docs
  install -vDm 644 {CHANGELOG,README.rst} \
    -t "${pkgdir}/usr/share/doc/${pkgname}/"
}
```

This _should_ still build ok on CI but, given how long this has taken me, I wouldn't be surprised if something broke somewhere! (EDIT: good news: tests still pass on CI)

### CODE REVIEW

**Comment by elParaguayo** [comment]
I've also just realised this isn't running the wayland tests so I need to add that to the PKGBUILD and see if I can get that to run.

**Comment by dvzrv** [comment]
Please note, that we will never run any syntax checker or code linting checks in packaging, as they are not important to the code working.
Moreover, the tests may break due to us updating the tooling being used and becoming e.g. more strict.

**Comment by elParaguayo** [comment]
Ha. Awesome. Good to know.

I'll remove `mypy` from `checkdepends` and those tests will get skipped automatically.

**Comment by elParaguayo** [comment]
Removing `mypy` and testing both backends is still successful on Arch.

**Comment by ramnes** [comment]
So, what's the status here?

**Comment by elParaguayo** [comment]
Well, it works as I can run test suite successfully in an Arch nspawn contained.

However, I'd be interested in your or @m-col's thoughts on the typing additions to `stubs` as I'm not sure why I got typing errors on Arch but we don't in CI.

That said, it sounds like the Arch packagers don't care about typing tests so we could potentially drop those changes as the relevant tests should be skipped if `mypy` isn't installed.

Do you want me to try that?

**Comment by ramnes** [comment]
What typing errors did you get?

Either investigating or removing the changes, both work for me. :)

**Pull request merged**
