### PR TITLE
fix window iteration on config reload to only look at managed windows

### PR DESCRIPTION
**Pull request by aravinda0**
Fixes https://github.com/qtile/qtile/issues/4656

### CODE REVIEW

**Comment by elParaguayo** [comment]
Thanks for this.

Just to make sure I completely understand, is the issue that your layout creates new internal windows during that loop over the windows map?

**Comment by aravinda0** [comment]
> Thanks for this.
> 
> Just to make sure I completely understand, is the issue that your layout creates new internal windows during that loop over the windows map?

Yup, that's right.
I create internal windows under certain conditions inside `Layout.add_client()`. 
During config reload, qtile loops over the windows map and a call chain goes something like `win.set_group() --> group.add(self) --> layout.add_client(win)`,  which creates an internal window, modifying windows map, leading to an exception.

**Comment by elParaguayo** [comment]
Great. There are a couple of tiny fixes you need to resolve the `check` failure here:
```diff
diff --git a/libqtile/backend/x11/core.py b/libqtile/backend/x11/core.py
index 88d52042..391a5215 100644
--- a/libqtile/backend/x11/core.py
+++ b/libqtile/backend/x11/core.py
@@ -242,12 +242,10 @@ class Core(base.Core):
         if not initial:
             # We are just reloading config
             managed_wins = [
-                w
-                for w in self.qtile.windows_map.values()
-                if isinstance(w, window.Window)
+                w for w in self.qtile.windows_map.values() if isinstance(w, window.Window)
             ]
-            for win in managed_wins:
-                win.set_group()
+            for managed_win in managed_wins:
+                managed_win.set_group()
             return
```
If you make those changes, I'm happy to merge this.

**Comment by aravinda0** [comment]
I've made the fixes. My bad - hadn't noticed the formatter failure.

**Pull request merged**
