### PR TITLE
Parse mpris2 text before display

### PR DESCRIPTION
**Pull request by elParaguayo**

### CODE REVIEW

**Comment by tych0** [comment]
I'm beginning to wonder if we should have a more systematic way to do this...

**Comment by elParaguayo** [comment]
> I'm beginning to wonder if we should have a more systematic way to do this...

We should!

The problem is that we can't escape all characters as there may be pango markup there too which needs to be parsed correctly. So we need to escape the text before it's formatted by the widget's format parameter. Very messy!

**Comment by tych0** [comment]
I wonder if python can help us here somehow with a custom formatter? I'll poke around.

**Comment by elParaguayo** [comment]
Probably, yes. I used a custom formatter for the Mpris2 widget already but for a different reason.

**Pull request merged**
