### PR TITLE
gtk window content doesn't rerender

### PR DESCRIPTION
**Pull request by zordsdavini**
reverted https://github.com/qtile/qtile/commit/4e76aa7b677835595def2d8e2d357b9b5466acaa part

fixing ticket https://github.com/qtile/qtile/issues/595

### CODE REVIEW

**Comment by tych0** [comment]
I vaguely remember someone telling me somewhere about weirdness in GTK, but I can't remember why. I know we used to send some updates to windows twice because of GTK (we got rid of that code to without negatively affecting anything), so maybe it was some combination of the two that was actually fixing things?

**Comment by zordsdavini** [comment]
before there was placing twice https://github.com/qtile/qtile/commit/aba161d57637c9aa89ec7bc2cad3fc3dc38fd8b0

**Comment by zordsdavini** [comment]
and this was when send_notify appears https://github.com/qtile/qtile/commit/7fce61d75342ecd7b7a820f642ffa7b4015e3136

**Comment by tych0** [comment]
Any word on this?

**Comment by flacjacket** [comment]
I haven't had time to look at it, we can revert that commit if we want to
fix it for now, since it was marked as a TODO before anyway.

**Comment by zordsdavini** [comment]
We don't need to revert all commit, just this part what this patch do

**Pull request closed without merging**
