### PR TITLE
Make floating, minimized, and maximized window states configurable

### PR DESCRIPTION
**Pull request by frostidaho**
For issue #1035

### CODE REVIEW

**Comment by dhannes** [comment]
It was changed by me in #1019.
I thought of ascii as too much last century. ;)
However, making it configurable is the best way to get around this issue and personal preferences.

**Comment by flacjacket** [comment]
I think it's fine to have this configurable, but it might be good to have the Unicode codes somewhere in the docstring if you have it configurable like this so people know what would be a good set of utf-8 defaults. You might also make it as an `"ascii"`/`"unicode"` toggleable parameter if you think that would be ok.

**Comment by frostidaho** [comment]
Okay sounds good, I updated the docstrings with examples including U0001F5D5..7. I'd prefer to leave it user-configurable as opposed to a switch, but it doesn't really matter to me.

**Comment by flacjacket** [comment]
Thanks for the changes, I'll push this in.

**Pull request merged**
