### PR TITLE
module imp is deprecated as of py3.5.

### PR DESCRIPTION
**Pull request by DorianGray**
This changes libqtile/core/manager.py::_import_module to use a full path
instead of dir path as well as switches from imp to importlib.

### CODE REVIEW

**Comment by m-col** [comment]
Nice, thanks. Pls could you include that message in the commit message?

**Comment by m-col** [comment]
Looks like it is used in one place only, and if it's 3 lines, then those lines may as well just be moved into that method `Qtile.cmd_run_external`.

**Comment by m-col** [comment]
Also, `imp` is deprecated in favour of `importlib`. I'm happy to merge this anyway and change that myself, unless you fancy it?

**Comment by DorianGray** [comment]
will fix!

**Comment by m-col** [comment]
Awesome thanks!

**Comment by m-col** [comment]
I've been trying to create a test for `Qtile.cmd_run_external` but, at least with my python installation, it doesn't work because `sys.exc_clear` isn't a thing. Investigating to see if that means it doesn't work for anything, and therefore nobody is using it, and therefore we could consider just removing it. It was added in 2014 with no meaningful additions since.

**Comment by m-col** [comment]
According to [this](https://docs.python.org/3/whatsnew/3.0.html?highlight=sys%20exc_clear), `sys.exc_clear` was removed in Python 3.0 (!!!) and therefore `Qtile.cmd_run_external` hasn't been used (successfully) since Qtile dropped Python 2 support.

Maybe we should just drop that method altogether @tych0 @ramnes?

**Comment by m-col** [comment]
The qshell appears to use `run_external` when giving a custom file to run, but it gives me an `Invalid command` message when trying to use that argument.

**Comment by m-col** [comment]
This would look like this: https://github.com/qtile/qtile/pull/2064

**Comment by ramnes** [comment]
Yeah I'd rather remove the method completely. @DorianGray, do you have a use case that really needs to revive this command or did you just fix that while looking around the code?

**Comment by DorianGray** [comment]
Just ran across it while refactoring manager init. Will close this

**Pull request closed without merging**
