### PR TITLE
Convert relative imports to absolute imports

### PR DESCRIPTION
**Pull request by pawamoy**
Converted imports in bin, libqtile and tests.

Issue #1618.

### CODE REVIEW

**Comment by tych0** [comment]
Can we enable the flake8 plugin for absolute imports here too?

**Comment by pawamoy** [comment]
Sure, will do!

**Comment by pawamoy** [comment]
Nice, it detected a few more issues that I missed :sweat_smile: 

```
./libqtile/core/session_manager.py:4:1: I250 Unnecessary import alias - rewrite as 'from libqtile.backend import base'.
./libqtile/core/session_manager.py:5:1: I250 Unnecessary import alias - rewrite as 'from libqtile import ipc'.
./test/test_images.py:6:1: I250 Unnecessary import alias - rewrite as 'from libqtile import images'.
./test/test_utils.py:23:1: I250 Unnecessary import alias - rewrite as 'from libqtile import utils'.
./test/test_images2.py:10:1: I250 Unnecessary import alias - rewrite as 'from libqtile import images'.
```

**Comment by pawamoy** [comment]
It seems there's no `flake8` job in Travis, should I add one?

**Comment by tych0** [comment]
Awesome, thank you!

**Pull request merged**
