### PR TITLE
doc: update release process

### PR DESCRIPTION
**Pull request by tych0**
I haven't been sending out e-mails or notifying IRC for the last few releases, and nobody has complained. Let's drop this, since it's one extra step.

I have, however, been updating the website, and I had forgotten to mention that initially, so note that down.

### CODE REVIEW

**Comment by ervinpopescu** [comment]
QQ: is releasing meant to not be shown somewhere in the TOC (or whatever the thing on the left is called by RTD/you guys)?

**Comment by tych0** [comment]
Not secret at all, I just didn't put it in the TOC because I didn't want the noise for all the people who don't release. I'm happy to add it if you think it's useful, I just figured it wouldn't be.

**Comment by elParaguayo** [comment]
While you're doing this, can you fix line 17. I think that `-S` should be lowercase (as per the example in the following line).

**Comment by tych0** [comment]
No, it really is `-S`, `-s` is "add the Signed-off-by for the author's e-mail" flag. Hooray for consistency.

**Pull request merged**
