### PR TITLE
Config type checking

### PR DESCRIPTION
**Pull request by ramnes**
Continuation of #1770 

Check the commits messages. I think the first commit should be merged in master anyway.

@tych0 @pawamoy

### CODE REVIEW

**Comment by tych0** [comment]
All that and we can't use type annotations anyway :). lgtm.

**Comment by ramnes** [comment]
Yeah :(

And I need to fix the tests.

**Comment by tych0** [comment]
So what if we instead made it optional? If one of the things was present, we'd use it to check the type annotations, if not, then we wouldn't do anything.

The reason I ask is because it's part of a larger idea I have, which I'll post about shortly.

**Comment by ramnes** [comment]
Ah, this is why you put that into load() and not validate() in the first place? Sounds good to me, I think I can revert to that or add a few bits to implement that behavior in validate(). What a cliffhanger though!

**Comment by tych0** [comment]
Read the above and see what you think; maybe we can do this with real typing anyway?

**Comment by ramnes** [comment]
I don't really like what I wrote here, let's close in favor of #1773.

**Pull request closed without merging**
