### PR TITLE
fix mute

### LINKED ISSUE #630: sound widget unmute not working
clicking unmute on the sound widget doesn't unmute the sound.

### PR DESCRIPTION
**Pull request by muhammedabuali**
a tiny fix for volume widget as suggested by @zordsdavini fixes #630

### CODE REVIEW

**Comment by zordsdavini** [comment]
I don't know do you need it to hardcode here, because you can simple use like:

            widget.Volume(emoji=True,
                mute_command=[
                    'amixer',
                    '-q',
                    'set',
                    'Master',
                    'toggle'],
                **Theme.widget),

**Comment by muhammedabuali** [comment]
I see what you did there but isn't it better that the widget work correctly by default

**Comment by zordsdavini** [comment]
for others it works. It should have some kind of poll to get most working
value and set it as default

On 23 March 2015 at 13:58, muhammedabuali <notifications@github.com> wrote:

> I see what you did there but isn't it better that the widget work
> correctly by default
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qtile/qtile/pull/639#issuecomment-84964651>.
>



-- 
Arns Udovīčė

**Comment by tych0** [comment]
Sorry, I'm confused about this change. It looks like we're just removing the cardid parameter, is that breaking things?

**Comment by tych0** [comment]
I'll go ahead and close this for now. If you have time to explain the change to me, please re-open.

**Pull request closed without merging**
