### PR TITLE
add generic poll widgets

### PR DESCRIPTION
**Pull request by Roger**
Example of GenPollUrl, it displays a list of the top five qitle contributors
```python
def parse_contrib(body):
    contribs = ["%s(%s)" % (u["login"], u["contributions"]) for u in body[:5]]
    return ", ".join(contribs)

qtile_contrib = widget.GenPollUrl(url='https://api.github.com/qtile/qtile/contributors',
                                  parse=parse_contrib)
```

### CODE REVIEW

**Comment by tych0** [comment]
Can you port the widgets to use this so we can see how it looks? Also, lying about the useragent seems impolite :)

**Comment by Roger** [comment]
About user-agent.. yeah, for apis i don't think it's useful, we should default to urllib's defaults or something like qtile widget user-agent?

About porting, the main idea was having an easy way to write your own functions on your config, so you don't have to write all the boilerplate code of a widget.. but maybe it could be extended to be used for core widgets as well.

For example, i used this to display the tracking location of a package sent using a local courier, something i don't think it's useful enough to be on the main qtile repo, but maybe having this, we can add some kind of snippet section(gists?) and add user examples there.

**Comment by tych0** [comment]
I wouldn't mind a qtile user agent (or maybe just sticking the string "Qtile" in the default urllib user agent).

It would be nice to port the bits of core to it that we can, so that we can get rid of that boilerplate too :)

**Comment by tych0** [comment]
And can you fix the linter too? It is whining in travis.

**Comment by tych0** [comment]
Oh, just kidding. Looks like that's an update to flake8 with new warnings. I'll push a fix in a moment.

**Comment by Roger** [comment]
Looking into the widgets, it seems that only bitcoin_ticker and yahoo_weather could use this

**Pull request closed without merging**
