### PR TITLE
Add toggle argument to Window.togroup

### LINKED ISSUE #3175: [Feature Request] Window.togroup with toggle
The `toscreen` method of `Group` has a `toggle` flag that allows toggling to the previous group if the target group is already shown on screen.

It would be nice to have this flag available on the `togroup` method of `Window` as well (and behaving correctly with the `switch_group` flag).

Use case: I use `mod4 + number` to navigate in groups, with toggling activated. I use `shift + mod4 + number` to move the active window in groups, with group switching activated. I would like window movement to behave consistently with group navigation w.r.t. toggling.

### PR DESCRIPTION
**Pull request by qwenger**
Fix #3175

### CODE REVIEW

**Comment by elParaguayo** [comment]
This looks ok to me.

I've rebased locally but can't push to your fork as you haven't given write access to maintainers.

Can you either give me access or do the rebasing yourself?

**Comment by qwenger** [comment]
Do you still consider this pull request? From what I understood from your colleague @m-col (https://github.com/qtile/qtile/issues/3175#issuecomment-1013914505) they prefer not to integrate it...

**Comment by elParaguayo** [comment]
We've been discussing it some more. While it's not something that I'd want to use, I do see understand your logic for wanting it. So, we're ok to include it.

**Comment by qwenger** [comment]
Alright then.

**Comment by qwenger** [comment]
Thanks!

**Comment by m-col** [comment]
Yeah sorry about that, I should have followed up here following @elParaguayo and I's offline discussion. Happy to have it :)

**Pull request merged**
