### PR TITLE
New layout: columns

### PR DESCRIPTION
**Pull request by heitzmann**
This layout is a mix of what I liked best from stack, wmii and xmonadtall.
I thought about extending one of them, but that felt too invasive, so I've decided to write a new one.

### CODE REVIEW

**Comment by flacjacket** [comment]
The pep8 check is complaining a bit, which is failing the tests, but I'll play with this and check it out and can fix that up if you don't get to it first. Thanks!

**Comment by heitzmann** [comment]
I see... I've just installed flake8 locally and fixed those issues.
The file seems to pass the tests at least here on my machine.

**Comment by flacjacket** [comment]
Cool, thanks for this!

**Comment by heitzmann** [comment]
My pleasure! Thanks for qtile!

**Pull request closed without merging**
