### PR TITLE
Remove ThreadedPollText

### PR DESCRIPTION
**Pull request by elParaguayo**
ThreadedPollText and ThreadPoolText are very similar. The latter
uses asyncio eventloop rather than threading and so is preferred
here.

### CODE REVIEW

**Comment by ramnes** [comment]
Great, thanks!

**Comment by m-col** [comment]
This commit seems to shoot up CPU usage attribute to `qtile`, according to `htop`.

**Comment by elParaguayo** [comment]
That's odd. Not aware of any reason that should be the case. Which widgets (that were updated via this PR) are you running? Will see if I can replicate here.

**Comment by m-col** [comment]
`Maildir`, and `Battery`

**Comment by m-col** [comment]
No sorry, just `Battery` I think

**Comment by m-col** [comment]
`Battery` normally, but I just removed it and the problem persists. `GenPollText`, when removed, appears to be the culprit!

**Comment by m-col** [comment]
lmao i got it. I was using `GenPollText` to check that a server I run is up by making and closing a quick connection. It looks like now `GenPollText` will continuously run the `func` it is given nonstop over and over with no delay. Previously it must have had some update interval, whose default value I was relying. I've added an `update_interval` setting now.

**Comment by elParaguayo** [comment]
OK - sounds like something that should be added as a default... If that's the case, I'll sort in a new PR.

**Comment by m-col** [comment]
Yep just confirming in the code, previously it's superclass had `update_interval` set to `600` by default, and now it is nothing. So if it is possible then it make sense to add that as the default with the new version too

**Comment by elParaguayo** [comment]
OK - will do. Sorry for missing that.

**Comment by elParaguayo** [comment]
See #2105

**Pull request merged**
