### PR TITLE
I stop taking sponsors for Qtile

### PR DESCRIPTION
**Pull request by ramnes**
Life priorities change and I'm not active enough on Qtile to justify receiving any money for my work on the project at the moment.

Big props to @pawamoy, @daroczig, @jagguli, @nazar-pc and @mikelward for their sponsorship!

### CODE REVIEW

**Comment by ramnes** [comment]
@m-col @pawamoy you guys are super active at the moment, I'd be happy to give you money if you'd set up a sponsorship account, and probably others too. :)

**Comment by elParaguayo** [comment]
Not sure I want to merge this one!

Even if you're less active (by your own standards), people are still benefitting from your efforts.

**Comment by pawamoy** [comment]
I agree with @elParaguayo :)
If you can cancel my sponsorship and want to do it, feel free to do so, otherwise I don't mind maintaining it :)

Also, you probably made a mistake mentioning me, saying that I'm really active, because I'm totally not 😅 At least not on Qtile!

**Comment by ramnes** [comment]
Ahah I meant @elParaguayo, yes. Thanks for the kind words. :)

**Comment by elParaguayo** [comment]
And there I was, thinking you'd forgotten about me! :wink:

**Pull request merged**
