### PR TITLE
config: rename and document respect_window_state_requests

### PR DESCRIPTION
**Pull request by tych0**
This isn't just minimization requests, but *all* state changes that people
can optionally ignore.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>

### CODE REVIEW

**Comment by m-col** [comment]
Other than fullscreen and minimisation requests, what other requests do people commonly see that this would block?

**Comment by tych0** [comment]
https://tronche.com/gui/x/xlib/ICC/client-to-window-manager/XIconifyWindow.html says the only valid thing *is* IconicState, so maybe it really is just minimization? Something the X11 people eventually thought would be extended but never was?

**Comment by m-col** [comment]
But more info here too: https://tronche.com/gui/x/icccm/sec-4.html#s-4.1.4

I'm assuming that the mapping which you mention on the original PR https://github.com/qtile/qtile/pull/2382 refers to minimised windows un-minimising to the "normal" state? If so, @ramnes's `auto_minimise` suggestion might be the most appropriate.

**Comment by m-col** [comment]
Or `auto_minimize` for you yanks ;)

**Comment by ramnes** [comment]
Yeah I think auto_minimize is a better one. It may not be the most technically correct name but at least it's understandable. We could also change the code to only drop requests that ask for the iconic state so that there's no surprise at all.

**Comment by tych0** [comment]
> We could also change the code to only drop requests that ask for the iconic state so that there's no surprise at all.

Yeah, I think that's the right move, then the naming makes sense. Take a look at the patch now.

**Review by m-col — APPROVED** [review]
Yep looks good :)

**Comment by ramnes** [comment]
Cool!

**Pull request merged**
