### PR TITLE
README: add a list of active maintainers w/ gpg keys

### LINKED ISSUE #2327: Provide information on release manager(s) and chain of trust
# Issue description

As a packager of qtile for Arch Linux I am happy to see, that you create verifiable releases for qtile by e.g. using signed tags.
Generally, Arch Linux (and other downstreams) try to make use of existing means of source verification to fend off [supply chain attacks](https://en.wikipedia.org/wiki/Supply_chain_attack).
Unfortunately it is not enough for individuals to sign their tags, as this only ensures, that the specific individual used a specific PGP key to sign a tag.
Between v0.12.0 and including v0.14.2 @flacjacket provided signed tags using `4EDAC65FECB64426`, while @tych0 signed the most recent release v0.17.0 using `18D18F1BC464DCA3`.

To provide the means for downstreams to follow up on a [chain of trust](https://en.wikipedia.org/wiki/Chain_of_trust) it is necessary to document who is in charge (can be multiple persons) of the release process of a project and which PGP key IDs are expected to be used for signed tags and/or signed release artifacts. This can happen in a document such as the README of the project. The trust towards the person first adding this information is trusted on first use ([TOFU](https://en.wikipedia.org/wiki/Trust_on_first_use)).

Changes to this document, that e.g. introduce a new key ID should then *always* happen with a signed commit of the person that is already trusted. Cross-signing the respective individual's keys is of course also an (additional) option to provide a chain of trust.

Generally I would be happy to use verifiable source tarballs (e.g. sdist tarballs) or clone from a verifiable tag to build this project.

If you have any questions in regards to best practices, please let me know.

# Qtile version

Any

# Stack traces

n/a

# Configuration

n/a

### PR DESCRIPTION
**Pull request by tych0**
These are the people who are active right now and might conceivably do a
Qtile release.

Closes #2327

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>

### CODE REVIEW

**Review by flacjacket — APPROVED** [review]

**Comment by tych0** [comment]
```
  py39: commands succeeded
  docs: commands succeeded
  pep8: commands succeeded
  codestyle: commands succeeded
  docstyle: commands succeeded
  mypy: commands succeeded
ERROR:   packaging: commands failed
```

Uh, what?

**Comment by flacjacket** [comment]
Ah! Looks like it is checking if the markdown can render:
```
   Checking dist/qtile-0.1.dev1+gb48ef52.tar.gz: FAILED
    `long_description` has syntax errors in markup and would not be rendered on PyPI.
      line 66: Error: Unknown target name: "@tych0 https://github.com/tych0".
  Checking dist/qtile-0.1.dev1+gb48ef52-py3.9-linux-x86_64.egg: FAILED
    `long_description` has syntax errors in markup and would not be rendered on PyPI.
      line 66: Error: Unknown target name: "@tych0 https://github.com/tych0".
```

**Comment by tych0** [comment]
Ah, derp. line 66: Error: Unknown target name: "@tych0 https://github.com/tych0".

**Comment by tych0** [comment]
Man, rst sucks :)

**Pull request merged**
