### PR TITLE
Delete deprecated

### PR DESCRIPTION
**Pull request by tych0**
Let's delete a bunch of deprecated stuff (and in some cases, add type enforcement for things that have been deprecated).

Note that this does not deprecate command_, since that makes the auto-migration tests fail, which means that nobody would ever get the benefit of those migrations (which is maybe ok...). A commit to do that is here, if we want to add it: https://github.com/tych0/qtile/commit/5e058270c4770774240e99022dc0da8432b6760d

### CODE REVIEW

**Comment by m-col** [comment]
Looks like all of the deprecations in the PR commits are older than 0.17, so are all good. Perhaps we should hold on the command_ one for a bit?

**Comment by ramnes** [comment]
No migration for these? :)

**Comment by tych0** [comment]
> No migration for these?

If we want to add a migration, we have to leave them in the tree, because the config files have to parse both ways. See the CI failures on the command_ patch for why. These are all old enough that we can just delete them without a migration IMO.

**Comment by tych0** [comment]
Did we come to a conclusion on whether we want to keep this stuff?

**Comment by m-col** [comment]
Considering we've just released, now might be a good time to tear these things out!

**Pull request merged**
