### PR TITLE
Add groupbox feature: Font colour when box highlighting

### PR DESCRIPTION
**Pull request by baldrianbandit**
This creates a third font colour called "selected", which is set to a groupbox item when highlight method "block" is used.

Background: Usually, the bar is of dark colour while the fonts are of bright colour. When using highlight method "block", the block must be of bright colour, too, to have a contrast to the bar. Then the font inside the block must be dark again, while the (in)active font colour is still bright. Thus, the font clour inside the block - selected - should be configurable.

### CODE REVIEW

**Comment by baldrianbandit** [comment]
For reference: https://github.com/qtile/qtile/issues/1243

**Comment by tych0** [comment]
Any chance we can change the name to reference the fact that this is only relevant in 'block' highlight mode? `block_highlight_text_color` or something?

**Comment by baldrianbandit** [comment]
Agreed.

**Comment by tych0** [comment]
Unfortunately I don't think we can change the other ones without some deprecation warnings and backwards compatibility code. So can you either add that code, or drop the others from the patch and just change the one you're adding?

**Comment by baldrianbandit** [comment]
Yeah sorry, guess you're right.

**Comment by tych0** [comment]
Merged it manually, thanks!

**Comment by m-col** [comment]
I think it would this would be better if this:
```python
text_color = self.block_highlight_text_color
```
was instead this:
```python
if self.block_highlight_text_color:
    text_color = self.block_highlight_text_color
```
and the default value was None or False. This way it can be left and would yield the original result, which was not colouring the text by whether it is on screen, only by active or inactive. (Sorry for being awkward but I liked it the old way!)

**Comment by tych0** [comment]
On Sun, Apr 05, 2020 at 02:01:09PM -0700, m-col wrote:
> I think it would this would be better if this:
> ```python
> text_color = self.block_highlight_text_color
> ```
> was instead this:
> ```python
> if self.block_highlight_text_color:
>     text_color = self.block_highlight_text_color
> ```
> and the default value was None or False. This way it can be left and would yield the original result, which was not colouring the text by whether it is on screen, only by active or inactive. (Sorry for being awkward but I liked it the old way!)

Oh, I didn't realize this broke the old behavior. Can you send a patch
to fix it?

**Comment by m-col** [comment]
Done #1586.

**Pull request closed without merging**
