### PR TITLE
show/hide bar on all screens

### PR DESCRIPTION
**Pull request by elParaguayo**
PR to merge @tych0 branch with some nice code for hiding/showing multiple bars at once.

tych0: hope you don't mind this. You previously posted the code but never submitted the PR. However, users on Discord are keen to see this one merged.

We probably want to add a test for this too.

### CODE REVIEW

**Comment by jwijenbergh** [comment]
Can we add a test?

**Comment by tych0** [comment]
Ha, I don't mind and totally forgot about it :). Thanks for resurrecting! Feel free to merge at will.

**Comment by elParaguayo** [comment]
@tych0 Not sure I can push to your fork.

Here are the tests for this PR:
```diff
diff --git a/libqtile/core/manager.py b/libqtile/core/manager.py
index 90c5d3e7..01295293 100644
--- a/libqtile/core/manager.py
+++ b/libqtile/core/manager.py
@@ -1765,7 +1765,7 @@ class Qtile(CommandObject):
         position :
             one of: "top", "bottom", "left", "right", or "all" (default: "all")
         screen :
-            one of: "current", "all" (default: "all")
+            one of: "current", "all" (default: "current")
         """
         to_mod = [self.current_screen]
         if screen == "all":
diff --git a/test/test_bar.py b/test/test_bar.py
index 7e17b2b8..55e436fc 100644
--- a/test/test_bar.py
+++ b/test/test_bar.py
@@ -34,6 +34,7 @@ import libqtile.confreader
 import libqtile.layout
 import libqtile.widget
 from libqtile.command.base import CommandError
+from test.conftest import dualmonitor
 from test.helpers import BareConfig, Retry


@@ -497,6 +498,131 @@ def test_bar_hide_show_with_margin(manager_nospawn):
     assert manager_nospawn.c.windows()[0]["y"] == 22


+@pytest.mark.parametrize(
+    "position,dimensions",
+    [
+        ("all", (0, 0, 800, 600)),
+        ("top", (10, 0, 800 - (2 * 10), 600 - 10)),
+        ("bottom", (10, 10, 800 - (2 * 10), 600 - 10)),
+        ("left", (0, 10, 800 - 10, 600 - (2 * 10))),
+        ("right", (10, 10, 800 - 10, 600 - (2 * 10))),
+    ],
+)
+def test_bar_hide_show_single_screen(manager_nospawn, position, dimensions):
+    conf = GeomConf
+    conf.layouts = [libqtile.layout.Max()]
+    manager_nospawn.start(conf)
+
+    # Dimensions of window with all 4 bars visible
+    default_dimensions = (10, 10, 800 - 2 * 10, 600 - 2 * 10)
+
+    def assert_dimensions(d=default_dimensions):
+        win_info = manager_nospawn.c.window.info()
+        win_x = win_info["x"]
+        win_y = win_info["y"]
+        win_w = win_info["width"]
+        win_h = win_info["height"]
+        assert (win_x, win_y, win_w, win_h) == d
+
+    manager_nospawn.test_window("one")
+    assert_dimensions()
+
+    # Hide bar
+    manager_nospawn.c.hide_show_bar(position=position)
+    assert_dimensions(dimensions)
+
+    # Show bar
+    manager_nospawn.c.hide_show_bar(position=position)
+    assert_dimensions()
+
+
+@dualmonitor
+@pytest.mark.parametrize(
+    "position,dimensions",
+    [
+        ("all", (0, 0, 800, 600)),
+        ("top", (10, 0, 800 - (2 * 10), 600 - 10)),
+        ("bottom", (10, 10, 800 - (2 * 10), 600 - 10)),
+        ("left", (0, 10, 800 - 10, 600 - (2 * 10))),
+        ("right", (10, 10, 800 - 10, 600 - (2 * 10))),
+    ],
+)
+def test_bar_hide_show_dual_screen(manager_nospawn, position, dimensions):
+    conf = GeomConf
+    conf.layouts = [libqtile.layout.Max()]
+    conf.screens = [
+        libqtile.config.Screen(
+            top=libqtile.bar.Bar([], 10),
+            bottom=libqtile.bar.Bar([], 10),
+            left=libqtile.bar.Bar([], 10),
+            right=libqtile.bar.Bar([], 10),
+        ),
+        libqtile.config.Screen(
+            top=libqtile.bar.Bar([], 10),
+            bottom=libqtile.bar.Bar([], 10),
+            left=libqtile.bar.Bar([], 10),
+            right=libqtile.bar.Bar([], 10),
+        ),
+    ]
+    manager_nospawn.start(conf)
+
+    # Dimensions of window with all 4 bars visible
+    default_dimensions = (10, 10, 800 - 2 * 10, 600 - 2 * 10)
+
+    def assert_dimensions(screen=0, d=default_dimensions):
+        win_info = manager_nospawn.c.screen[screen].window.info()
+        win_x = win_info["x"]
+        win_y = win_info["y"]
+        win_w = win_info["width"]
+        win_h = win_info["height"]
+        # Second screen is 600x480 @ x=800,y=0
+        # Adjust dimensions for this
+        if screen == 1:
+            d = (d[0] + 800, d[1], d[2] - (800 - 640), d[3] - (600 - 480))
+        assert (win_x, win_y, win_w, win_h) == d
+
+    manager_nospawn.test_window("one")
+    manager_nospawn.c.to_screen(1)
+    manager_nospawn.test_window("two")
+    assert_dimensions(screen=0)
+    assert_dimensions(screen=1)
+
+    # Test current screen
+    # Screen 0 - hidden, Screen 1 - shown
+    manager_nospawn.c.to_screen(0)
+    manager_nospawn.c.hide_show_bar(position=position)
+    assert_dimensions(screen=0, d=dimensions)
+    assert_dimensions(screen=1)
+
+    # Screen 0 - hidden, Screen 1 - hidden
+    manager_nospawn.c.to_screen(1)
+    manager_nospawn.c.hide_show_bar(position=position)
+    assert_dimensions(screen=0, d=dimensions)
+    assert_dimensions(screen=1, d=dimensions)
+
+    # Screen 0 - hidden, Screen 1 - shown
+    manager_nospawn.c.hide_show_bar(position=position)
+    assert_dimensions(screen=0, d=dimensions)
+    assert_dimensions(screen=1)
+
+    # Screen 0 - shown, Screen 1 - shown
+    manager_nospawn.c.to_screen(0)
+    manager_nospawn.c.hide_show_bar(position=position)
+    assert_dimensions(screen=0)
+    assert_dimensions(screen=1)
+
+    # Test all screens
+    # Screen 0 - hidden, Screen 1 - hidden
+    manager_nospawn.c.hide_show_bar(position=position, screen="all")
+    assert_dimensions(screen=0, d=dimensions)
+    assert_dimensions(screen=1, d=dimensions)
+
+    # Screen 0 - shown, Screen 1 - shown
+    manager_nospawn.c.hide_show_bar(position=position, screen="all")
+    assert_dimensions(screen=0)
+    assert_dimensions(screen=1)
+
+
 def test_bar_border_horizontal(manager_nospawn):
     config = GeomConf
```

**Comment by tych0** [comment]
Huh, I wonder if it's because you made the PR? I thought maintainers could push to PRs at least, but maybe you can't authorize that from someone else's repo. Anyway, I pushed with you as the author, thanks for the test!

**Comment by elParaguayo** [comment]
Hmm. Those tests passed locally. I'll push to a local branch and do some more testing.

**Comment by elParaguayo** [comment]
Failure is due to multiple tests in that file changing some class attributes. Easiest fix is this:
```diff
diff --git a/test/test_bar.py b/test/test_bar.py
index 55e436fc..9f01f9e1 100644
--- a/test/test_bar.py
+++ b/test/test_bar.py
@@ -511,6 +511,14 @@ def test_bar_hide_show_with_margin(manager_nospawn):
 def test_bar_hide_show_single_screen(manager_nospawn, position, dimensions):
     conf = GeomConf
     conf.layouts = [libqtile.layout.Max()]
+    conf.screens = [
+        libqtile.config.Screen(
+            top=libqtile.bar.Bar([], 10),
+            bottom=libqtile.bar.Bar([], 10),
+            left=libqtile.bar.Bar([], 10),
+            right=libqtile.bar.Bar([], 10),
+        )
+    ]
     manager_nospawn.start(conf)

     # Dimensions of window with all 4 bars visible
```

**Pull request merged**
