### PR TITLE
Note that the example autostart.sh script should be executable

### PR DESCRIPTION
**Pull request by m-col**
Also removes `feh` because I want people to use our internal wallpaper setting :)

### CODE REVIEW

**Comment by elParaguayo** [comment]
Looks good to me and also looks like a good candidate for my first merge!

**Comment by elParaguayo** [comment]
Should I have merged this differently? Changed the title? Also, why doesn't it say you "authored" this one?

**Comment by tych0** [comment]
I try to use fast-forward (aka rebase) merges instead of actual merge commits, since it keeps the history slightly cleaner. Looks like

0c049edd96069a7030c4895e9832711c07bb0bfa

is your merge commit and

e65aa66c4efba30f8ecab42ffbff1b5bfe2aa00a

is the actual commit in the PR from m-col. So the authorship is as I would expect, the only difference between how we usually do it is the merge commit. It's not the end of the world though :)

**Comment by elParaguayo** [comment]
Thanks. Will get it right next time!

**Pull request merged**
