### PR TITLE
Automate screenshots

### PR DESCRIPTION
**Pull request by pawamoy**
For issue #1405.

### CODE REVIEW

**Comment by pawamoy** [comment]
### TODO

- [ ] Add "no commands" calls to `take` for simple layout screenshots
- [ ] Space optimization: remove PNG files if we only use GIFs in the docs
- [ ] Space/time optimization: don't duplicate screenshots, especially initial ones.
  Write them to a hash of layout + commands + commands_before + windows,
  then symlink fake screenshots to these files (don't run `scrot`)
- [ ] Finish writing list of `take` calls
- [ ] Optional: layout introspection to dynamically take screenshots for all commands?

**Comment by pawamoy** [comment]
Here is a detailed explanation on how to use the newly added scripts.

### Four files were added
- the first one is the main, most-automated entry point to take all the screenshots at once: `scripts/take-screenshots.sh`.

  It is (almost completely) platform/system/machine independent as it uses Xephyr to take the screenshots in a nested X server.

  I usually run it with the following command: `SCREEN_SIZE=1920x1080 PYTHON=venv/bin/python scripts/take-screenshots.sh`.

  When trying things out, pass it the `-i` or `--interactive` flag. You'll be able to play around with windows with the keybindings defined in `docs/screenshots/config.py` (which could be improved/extended).

  This script, `script/take-screenshots.sh` calls by default a second file: `docs/screenshots/take_all.py`.

- `docs/screenshots/take_all.py` is the main Python script that will, for each layout, run commands and take screenshots.

  This is where all the possible screenshots are automated with a `take` function. A typical example of calling `ŧake` is `take("bsp", ["shuffle_right"])`. It's as simple as that. This one line will switch to the BSP layout, spawn a default number of xterm windows, each colored differently, take an initial screenshot and another one after each command is ran. It will also animate the screenshots at the end into a GIF, and optionally delete the PNG screenshots to free space.

  All this functionality is made possible thanks to the third file: `docs/screenshots/screenshot.py`.

- `docs/screenshots/screenshot.py` is a small high-level library, making use of the `libqtile` functionality to ease the taking of screenshots. This is where the colors and the layout methods are defined.

  It provides a `get_client` function that returns a wrapped Qtile client with methods like `switch_to_group`, `prepare_layout`, `spawn_window` or `run_layout_command`.

  It also provides a `Screenshooter` class that is responsible for the taking of screenshots and animating them into GIFs. It uses `scrot` and `convert` for this.

  The `docs/screenshots/screenshot.py` script can also be called directly. It has an argument parser:
  ```
  usage: screenshot.py [-h] [-c COMMENT] [-b COMMANDS_BEFORE] [-w WINDOWS]
                       [-d DELAY] [-g SCREENSHOT_GROUP] [-G GEOMETRY]
                       [-o OUTPUT_DIR]
                       {bsp,columns,matrix,monadtall,monadwide,ratiotile,stack,tile,treetab,verticaltile,zoomy}
                       commands [commands ...]

  positional arguments:
    {bsp,columns,matrix,monadtall,monadwide,ratiotile,stack,tile,treetab,verticaltile,zoomy}
                          Layout to use.
    commands              Commands to run and take screenshots for.

  optional arguments:
    -h, --help            show this help message and exit
    -c COMMENT, --comment COMMENT
                          Comment to add at the end of the screenshot filenames.
    -b COMMANDS_BEFORE, --commands-before COMMANDS_BEFORE
                          Commands to run before starting to take screenshots.
    -w WINDOWS, --windows WINDOWS
                          Number of windows to spawn.
    -d DELAY, --delay DELAY
                          Delay between each frame of the animated GIF in
                          seconds.
    -g SCREENSHOT_GROUP, --screenshot-group SCREENSHOT_GROUP
                          Group to switch to to take screenshots.
    -G GEOMETRY, --geometry GEOMETRY
                          The size of the generated screenshots (WIDTHxHEIGHT).
    -o OUTPUT_DIR, --output-dir OUTPUT_DIR
                          Directory in which to write the screenshot files.
  ```

  This is useful to try things out. You'll call it like this: `PYTHONPATH=$PWD venv/bin/python docs/screenshots/screenshot.py ARGS`.

- Finally, the last file added is a special configuration file dedicated to the taking of screenshots. It simply defines the layouts with big, red focused borders and some keybindings.

### Generated GIFs/PNGs
The generated files will be organized in subdirectories of the selected output dir, which is by default `docs/screenshots/layout`. For example, BSP screenshots will land in `docs/screenshots/layout/bsp`.

A screenshot/animation file name will be formed by the commands run (if any) or the layout name, followed by a comment (if any). The example given above, `take("bsp", ["shuffle_right"])`, will generate the file `docs/screenshots/layout/bsp/shuffle_right.gif`. `take("bsp", [], comment="2-windows", windows=2)` will generate the file `docs/screenshots/layout/bsp/bsp-2-windows.png` (it has no commands, so it's only one screenshot, not an animation).

**Comment by pawamoy** [comment]
I'll finish writing the `take_all.py` commands, post an archive with the generated files, and then would like some feedback! On colors (that I would like to be readable by color-impaired persons), on the files dimensions, on their size and if it's a problem, and on the way to add these screenshots in the docs. I guess we'll need to do #1360 as well, before or in the same PR.

**Comment by pawamoy** [comment]
Build timeout on pypy3 again! :confused:

**Comment by pawamoy** [comment]
That's it!

[screenshots.tar.gz](https://github.com/qtile/qtile/files/3627683/screenshots.tar.gz)

It weighs 1.1M (1056K) uncompressed, for 139 files (GIFs and PNGs). I think I can bring it down to ~630K with `pngcrush`.

 Some commands have no screenshots
- because they didn't work (ratiotile's ratio increase/decrease)
- because they require arguments (stack's `client_to_stack`, etc.)
- because their layout is kinda bugged (slice, treetab, see notes in `take_all.py`)
- because they are not listed in the docs, or not clearly visible in the source code (inheritance/composition?)

Overall it's a good starting point.

Some of the screenshots might not be of value, like the repetitive left, up, right and down commands, or their shuffle equivalent. Sometimes they are, because they differ from one layout to another.

Anyway, I'm waiting for some feedback (about anything) :smile_cat:

**Comment by zordsdavini** [comment]
Incredible work. I use Qtile for a 5 years and stick to max and monadtall layouts. Looked at your gifs and found that there is a lot layouts what are quite similar and even have more functionality. Visualization gives better possibility to see how it works. And it gives thoughts what we have a lot of similar layouts and maybe some of them should be deprecated in favor of other. Will be happy to see gives in documentation. Next step could be to gather functionalities in table to compare. Thanks @pawamoy for your work :)

**Comment by zordsdavini** [comment]
feedback (for what I use) :)
- For monadtall maximize-main wrong window is selected. Should be green selected
- For monadtall normalize-from-main wrong window is selected. Should be green selected. Because right side should preserve proportion but green window should take half of screen
- maybe we should have Max and Floating (this I never use) png, too? Mybe just one to show that it has only one window and for floating to see one window on all

**Comment by pawamoy** [comment]
Thank you @zordsdavini !!

> For monadtall maximize-main wrong window is selected. Should be green selected
For monadtall normalize-from-main wrong window is selected. Should be green selected. Because right side should preserve proportion but green window should take half of screen

Thanks, I will update the code. Sometimes it's hard because some commands change the state of the layout, so I have to change it back after the animation, otherwise it messes up the next animations :smile: 

> maybe we should have Max and Floating (this I never use) png, too? Mybe just one to show that it has only one window and for floating to see one window on all

Indeed, I completely skipped those two. I'll do the simple Max one, and see if I can do the Floating one as well (it might behave differently and need some code updates).

> I use Qtile for a 5 years and stick to max and monadtall layouts. Looked at your gifs and found that there is a lot layouts what are quite similar and even have more functionality. Visualization gives better possibility to see how it works.

I myself am using Qtile since about a month, and immediately went with BSP and Max, but I now look at Monad/Stack/Column layout with great interest! So I definitely agree that the GIFs help seeing how they work and what they can do :slightly_smiling_face:

**Comment by pawamoy** [comment]
`maximize-main` is now fixed. `normalize-from-main` is correct as well, though maybe unintuitive. It normalizes only the secondary panes, not the main one, and this is what I wanted to show with this animation. Maybe this is not expected behavior and should be fixed in the layout code itself.

**Comment by pawamoy** [comment]
Layout `Max`: OK. Layout `Floating`: same issue as `TreeTab`. They contain clients from all groups/layouts, effectively breaking our cleaning method, `kill_group_windows`, blocking the script until manually switching back to original group (with a click).

**Comment by pawamoy** [comment]
Here is how the docs would look with such screenshots.

screenshots_docs_demo

I think we could reduce even more their size.

If we worry about the loading time of the page (which contains all layouts in one page), we could split it in multiple pages, one for each layout. We could also, as stated above, reduce the size of the images, and further compress them with `pngcrush`.

We could also add a level of indentation in the sidebar to display the available commands and the links to their anchors to improve navigability (though I'm not sure it's possible with Sphinx).

What do you think?

I'm even willing to write the missing docs for all the layouts commands :wink:

By the way, here is how I wrote the docstrings:
```python
def cmd_flip_left(self):
    """
    Swap the position of the focused windows' node with its left neighbor.

    .. image:: /screenshots/layout/bsp/flip_left.gif
        :alt: Swap node position to the left
    """
```

**Comment by zordsdavini** [comment]
You did big job. It is time to have it live :) It will attract more people to Qtile

**Comment by pawamoy** [comment]
I think I'd prefer to go this way:

1. merge this PR. Some screenshots are not ready, but they can be added later when problematic layouts are fixed. **I'd recommend squashing all the commits**, because a lot of refactor happened, and it's just noise in the git logs.
2. decide on how to add the screenshots to the repo. Classic or LFS? Uploaded somewhere?
3. start a new PR that will link the screenshots in the docs (and maybe some docs tweaks/improvements)

**Comment by pawamoy** [comment]
Hi @ramnes, @flacjacket!

Any chance you'd review this :stuck_out_tongue:? I know it is volunteer work you're doing here, so first, thank you very much, and second, it's perfectly understandable if you don't have the free time to do so! I'm totally OK with that!

But maybe there's something I could do to help? Maybe write a better summary of the PR? I'm also open to chat with you on GItter or else or even have a video call + screen sharing to explain things if this is something you prefer :slightly_smiling_face: 

Anyway, thanks again and have a good day :smile:

**Comment by ramnes** [comment]
Usually when I don't say anything on such a big PR, it's because I don't have an strong opinion on the subject, so I'll wait for @flacjacket thoughts! :smile:

**Comment by pawamoy** [comment]
@flacjacket is there anything I can do to help merge this PR? Maybe add a tox job that creates and checks the screenshots, and add it in the travis config?

If you worry about the added maintenance work, please note that this code will rarely be used (only when changing layouts or adding/changing screenshots), and I also can offer my time to take care of any screenshots related issue that would arise from it 🙂

**Comment by tych0** [comment]
This is cool, I'm going to merge it :)

**Pull request merged**
