### PR TITLE
simplify base widget call_process method

### PR DESCRIPTION
**Pull request by yobleck**
removes unnecessary temp variable and method call
see issue https://github.com/qtile/qtile/issues/2607

### CODE REVIEW

**Comment by m-col** [comment]
This kinda makes the `check_output` method redundant. Maybe we should just remove it altogether?

**Comment by yobleck** [comment]
> This kinda makes the `check_output` method redundant. Maybe we should just remove it altogether?

I don't understand. Redundant to what? call_process is used by a bunch of widgets and I can't find any other method that accomplishes the same thing.

**Comment by m-col** [comment]
> I can't find any other method that accomplishes the same thing.

`subprocess.check_output` :)

**Comment by yobleck** [comment]
So you mean we just get rid of call_process() in the base widget class and manually implement subprocess.check_output() in every widget that needs it? That seems like it could lead to fragmentation among how the widgets work.

**Comment by ramnes** [comment]
Let's not debate on this, both work. :)

Thanks for the PR!

**Pull request merged**
