### PR TITLE
_SimpleLayoutBase: Pass client_position to _ClientList

### PR DESCRIPTION
**Pull request by jwijenbergh**
I noticed this while creating a custom layout with `_SimpleLayoutBase`. As I see it, `_SimpleLayoutBase` is just a wrapper around `_ClientList` so it should support the `client_position` argument too.

### CODE REVIEW

**Comment by elParaguayo** [comment]
Thanks. Seems reasonable to me.

Can we add a test for this?

**Comment by elParaguayo** [comment]
Also, what's your custom layout? We'd happily look at a PR if you think it's something worth sharing.

**Comment by jwijenbergh** [comment]
> Thanks. Seems reasonable to me.
> 
> Can we add a test for this?

No problem :+1:  I will add one later

**Comment by jwijenbergh** [comment]
> Also, what's your custom layout? We'd happily look at a PR if you think it's something worth sharing.

It's a bit niche so I'm not sure it would work inside Qtile. It's essentially recreating [exwm](https://github.com/ch11ng/exwm/wiki/Screenshots) in Qtile:

- The layout starts a maximized emacs instance
- Every window that is created is embedded into the emacs window
- The window positions are obtained from emacs itself
- Essentially windows are now just emacs buffers, it uses emacs lisp code to interact with qtile

**Comment by jwijenbergh** [comment]
I have added some position tests to a new file called `tests_base.py` in layouts tests. I didn't want to duplicate a ton of tests of the position tests already done in the xmonad tests so these two should do for a simple change like this.

**Comment by elParaguayo** [comment]
> I'm not completely sure what you expected tests of (as `_ClientList` positions is already tested with e.g. xmonad test code), but...
> 
> I have added some position tests to a new file called `tests_base.py` in layouts tests. I didn't want to duplicate a ton of tests of the position tests already done in the xmonad tests so these two should hopefully do for a simple change like this.

You've exposed an extra argument in `_SimpleLayoutBase.add` so I'd like to see that method being tested successfully.

Would expect it to be a very short test!

**Comment by jwijenbergh** [comment]
> > I'm not completely sure what you expected tests of (as `_ClientList` positions is already tested with e.g. xmonad test code), but...
> > I have added some position tests to a new file called `tests_base.py` in layouts tests. I didn't want to duplicate a ton of tests of the position tests already done in the xmonad tests so these two should hopefully do for a simple change like this.
> 
> You've exposed an extra argument in `_SimpleLayoutBase.add` so I'd like to see that method being tested successfully.
> 
> Would expect it to be a very short test!

Is that not covered now by the test I added? 😅

**Comment by elParaguayo** [comment]
Yes, it is - and it looks good.

I was going to ask you to rebase on to latest master to ensure all tests are run but you've done that too!

**Comment by jwijenbergh** [comment]
Ah okay good. I was just making sure I wrote the correct tests here haha. Thanks for the merge.

**Pull request merged**
