### PR TITLE
Respond to SIGUSR1 and SIGUSR2

### LINKED ISSUE #1005: Reload configuration on SIGHUP
I have a shell script that is executed on a uevent from udev. In this script, I have to restart Qtile. At the moment I'm accomplishing this with the following:

`echo restart | qshell -s /home/matt/.cache/qtile/qtilesocket.\:0.0 &> /dev/null`

This isn't ideal due to the hard coded qtilesocket path. Would it be ok to add the ability to either restart Qtile or reload the configuration file when Qtile receives a SIGHUP, adhering to the Unix convention?

### PR DESCRIPTION
**Pull request by m-col**
The spiritual successor of #2114.

SIGUSR1 for reloading config.
SIGUSR2 for a full restart.

Closes #1005

### CODE REVIEW

**Review by elParaguayo — APPROVED** [review]
LGTM

**Comment by elParaguayo** [comment]
Any downsides to this that you can think of?

**Comment by m-col** [comment]
I don't think so - seems to work well for me

**Comment by elParaguayo** [comment]
Works well for me too.

**Pull request merged**
