### PR TITLE
fix commands not in subcommands

### PR DESCRIPTION
**Pull request by DorianGray**
```
14:39 < mcol> looks like qtile --version is broken
14:40 < mcol> perhaps we should test all the new commands :)
```

### CODE REVIEW

**Comment by m-col** [comment]
LGTM! Probably best for @tych0 for go over this one as he put together this arg parsing recently.

**Comment by tych0** [comment]
Derp derp, thanks!

**Comment by tych0** [comment]
One point of note -- in the future can you put stuff like that IRC discussion in the commit message?

**Comment by DorianGray** [comment]
Absolutely

**Pull request merged**
