### PR TITLE
PulseVolume: remove FFI dependency

### PR DESCRIPTION
**Pull request by elParaguayo**
This PR rewrites the `PulseVolume` widget to rely on an external library, `pulsectl_asyncio`. The advantage of this is that we can remove our FFI bindings which will, in turn, simplify building and packaging.

### CODE REVIEW

**Review by ramnes — APPROVED** [review]
Can confirm that it works very well, even better than the previous version (handles sink changes). Only one little regression: when updating the volume, the bar flickers. That's particularly visible with the scroll wheel. I really don't think that's a blocker though.

**Comment by elParaguayo** [comment]
Let me check that. I suspect we're getting multiple callbacks from the server, triggering a draw on each one whereas we only need one.

**Review by tych0 — APPROVED** [review]
Thanks for handling this!

**Comment by elParaguayo** [comment]
@ramnes I have _hopefully_ fixed the flickering (only calling `bar.draw()` if the length of the widget has changed.

**Comment by ramnes** [comment]
Can confirm, that works!

**Pull request merged**
