### PR TITLE
run-cmd -f didn't float window

### PR DESCRIPTION
**Pull request by LamprosPitsillos**
fix for #2806 , thanks to @elParaguayo

### CODE REVIEW

**Review by elParaguayo — APPROVED** [review]
LGTM. 

The CI failures are not related to this but we just need to fix those CI issues and then we can re-run the tests on this.

**Comment by LamprosPitsillos** [comment]
> LGTM.
> 
> The CI failures are not related to this but we just need to fix those CI issues and then we can re-run the tests on this.

I tried understanding what the issue was but no luck there.. Is there anything i can do?

**Comment by m-col** [comment]
The CI failed early due to warnings that are unrelated. I ran the tests on my branch for this PR ignoring the warnings, and it looks like it's all good: https://github.com/qtile/qtile/compare/master...m-col:2808

**Comment by elParaguayo** [comment]
@LamprosPitsillos we've merged the bugfix which should fix the CI issues. Can you rebase this branch onto the latest master and push it again so we can confirm CI is ok.

**Comment by LamprosPitsillos** [comment]
> @LamprosPitsillos we've merged the bugfix which should fix the CI issues. Can you rebase this branch onto the latest master and push it again so we can confirm CI is ok.

I've never done it again but i think i did it. Let's see...

**Pull request merged**
