### PR TITLE
drop various python < 3.7 version tests

### PR DESCRIPTION
**Pull request by tych0**
Now that we only support >= 3.7, let's drop a bunch of version tests.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>

### CODE REVIEW

**Comment by tych0** [comment]
Not quite clear to me why this fails, I tried the latest version of mypy and no luck.

**Comment by tych0** [comment]
When I pass an explicit `--python-version 3.7` to mypy, it works just fine. But all the docs say I shouldn't have to do that...

**Comment by flacjacket** [comment]
We set the minimum Python version that mypy uses for checking in `setup.cfg`, should just need to update that.

**Comment by tych0** [comment]
Ah ha, derp derp. Thanks :)

**Pull request merged**
