### PR TITLE
fix qtile randomly not able to start

### PR DESCRIPTION
**Pull request by fdev31**
corrupted pickle prevents startup
leading to a core dump

### CODE REVIEW

**Comment by tych0** [comment]
Can you post the exact stack trace? I'm curious what this error is, it really "shouldn't" happen...

**Comment by fdev31** [comment]
I run my qtile in the background, mate-session is my DE, and I'm used to kill my X with Ctrl+Alt+Bkspace, maybe that provides more context to understand how that happens...
I guess some pickle saving function runs partially & get killed.
If you tell me which file I can corrupt (I don't know what this state file is) I'll reproduce the bug quickly.
Else I would have to run without my patch & wait for it to happen...

**Comment by tych0** [comment]
There is no file that this particular state is saved to; it's passed on the command line when running with --with-state as you note as a literal argument.

Can you show the argument that's breaking, maybe? This seems like an underlying bug somehow, maybe with argparse or something.

**Comment by fdev31** [comment]
I'm confused, since I wasn't using this argument as far as I remember... at some point I tried adding it since the error was about some state and this unpickle line and I got similar stack trace using:
`with-state=/tmp/foo`
But when this happened I had no arguments passed...

**Comment by tych0** [comment]
Right, generally there's no need to manually use this argument. If you weren't restarting and you got this stack trace, then something went *really* wrong, and we should try and figure that out.

**Comment by tych0** [comment]
I'm going to close this for now; we should figure out whatever the underlying pickling error was and fix that.

**Pull request closed without merging**
