### PR TITLE
[DO NOT MERGE] Testing RTD webhook for pull requests

### PR DESCRIPTION
**Pull request by elParaguayo**
Just trying to see if I can get our ReadTheDocs webhook working on pull requests.

EDIT: Boom!

### CODE REVIEW

**Comment by m-col** [comment]
nothing makes me want to merge more than "DO NOT MERGE"

**Comment by elParaguayo** [comment]
> nothing makes me want to merge more than "DO NOT MERGE"

Ha. Did you check the diff for this one too?

**Comment by m-col** [comment]
Lol yes, that is my dream

**Comment by elParaguayo** [comment]
Cool. This works. Can we remove `docs` test from our CI (although, it may still be worth keeping it in `tox.ini` as that will allow people to run `tox -e docs` locally)?

**Comment by m-col** [comment]
This is very cool.

>  Can we remove docs test from our CI (although, it may still be worth keeping it in tox.ini as that will allow people to run tox -e docs locally)?

Makes sense!

**Pull request closed without merging**
