### PR TITLE
broken window list extension fix

### PR DESCRIPTION
**Pull request by zordsdavini**
ah, I've braked window list extension (all dmenu stuff that goes vertically). This is fix

### CODE REVIEW

**Comment by ramnes** [comment]
Can you explain what is wrong without the cast?

**Comment by zordsdavini** [comment]
Searching min between str and int.

**Comment by ramnes** [comment]
@zordsdavini but why is `self.dmenu_lines` a string in the first place? I think this is the real problem.

**Comment by zordsdavini** [comment]
> @zordsdavini but why is `self.dmenu_lines` a string in the first place? I think this is the real problem.

this is because I couldn't save default as int (0) in Dmenu class. Lint problems

**Comment by ramnes** [comment]
I don't understand: the default is `None`, and `None` isn't a string (and also, `int(None)` is not something that works). What default are you talking about? What line?

**Comment by zordsdavini** [comment]
this was from https://github.com/qtile/qtile/pull/1231#issuecomment-462592874 . Maybe I resolved it in wrong way

**Comment by zordsdavini** [comment]
this fixed my issue in command set extension https://github.com/qtile/qtile/pull/1231/commits/1196b9c3db4140d38ffae47329e7010f88ac6ce5 but because of that I got this

**Comment by flacjacket** [comment]
Is this still needed? It looks like it needs a rebase.

**Comment by zordsdavini** [comment]
Will try latest version. If issue still exiats will rebase. But from
discussion earlier I'm not sure have I fixed it in right way. Maybe I
should try to fix typehints and set default value to integer

2019 m. kov. 16 d., št 18:41, Sean Vig <notifications@github.com> rašė:

**Comment by zordsdavini** [comment]
Had the last testings - still can't get window lists. My given patch fixes the issue

**Comment by flacjacket** [comment]
Thanks!

**Pull request merged**
