### PR TITLE
Fix floating size hints

### PR DESCRIPTION
**Pull request by tych0**
Here's some patches that possibly fix our floating size hints. Note that I don't use any of the applications people are having problems with, but maybe people can test?

#1140 #1518

### CODE REVIEW

**Comment by Miziak** [comment]
@tych0 for me it completly screw up modals and crash entire wm log:
```
Traceback (most recent call last):
  File "/home/pmizio/.local/lib/python3.7/site-packages/libqtile/backend/x11/xcore.py", line 248, in _xpoll
    ret = target(event)
  File "/home/pmizio/.local/lib/python3.7/site-packages/libqtile/backend/x11/xcore.py", line 508, in handle_ButtonPress
    button_code, state, event.event_x, event.event_y, event
  File "/home/pmizio/.local/lib/python3.7/site-packages/libqtile/core/manager.py", line 759, in process_button_click
    self.cmd_focus_by_click(event)
  File "/home/pmizio/.local/lib/python3.7/site-packages/libqtile/core/manager.py", line 734, in cmd_focus_by_click
    self.current_group.focus(self.windows_map.get(wnd), False)
  File "/home/pmizio/.local/lib/python3.7/site-packages/libqtile/group.py", line 233, in focus
    layout.focus(win)
  File "/home/pmizio/.local/lib/python3.7/site-packages/libqtile/layout/base.py", line 604, in focus
    self.group.layout_all()
  File "/home/pmizio/.local/lib/python3.7/site-packages/libqtile/group.py", line 164, in layout_all
    self.floating_layout.layout(floating, screen)
  File "/home/pmizio/.local/lib/python3.7/site-packages/libqtile/layout/base.py", line 57, in layout
    self.configure(i, screen)
  File "/home/pmizio/.local/lib/python3.7/site-packages/libqtile/layout/floating.py", line 248, in configure
    self.compute_client_position(client, screen)
  File "/home/pmizio/.local/lib/python3.7/site-packages/libqtile/layout/floating.py", line 184, in compute_client_position
    if self.no_reposition_match or self.no_reposition_match.compare(client):
AttributeError: 'NoneType' object has no attribute 'compare'
```

**Comment by tych0** [comment]
Can you pull again? I think I fixed that.

**Comment by Miziak** [comment]
after pull, popups not blow up manager but teams notifications are still at the center of screen

**Comment by zordsdavini** [comment]
But there banner should be? Now I got some and I see that it sometimes appears in the middle, sometimes in the corrner. I don't
like these banners completelly but no other way to get notifications...

**Comment by tych0** [comment]
Ok, so is it fair to say this works "sometimes"? Can you add some logging and see if sometimes it's got the UPosition flag set and sometimes it doesn't? Or maybe it's that the geometry is invalid sometimes?

If it's the former, I can work on cleaning up this code to get it merged, since I think it's an improvement. If it's the latter, we probably need to figure out how to get the geometry in a more reliable way.

**Comment by tych0** [comment]
Ok, I think my code was still wrong. Can someone try it now? :)

**Comment by tych0** [comment]
Travis failure is fixed as an additional patch in #1716

**Comment by Miziak** [comment]
> Ok, I think my code was still wrong. Can someone try it now? :)

I'm able to check it at monday, i use teams only @ work ;)

**Comment by Miziak** [comment]
@tych0 ok teams banners look ok but on first start of wm i get:
```
2020-05-11 09:39:29,564 ERROR libqtile qtile.py:main():L153 Qtile crashed
Traceback (most recent call last):
  File "/home/pmizio/.local/lib/python3.8/site-packages/libqtile/scripts/qtile.py", line 151, in main
    q.loop()
  File "/home/pmizio/.local/lib/python3.8/site-packages/libqtile/core/session_manager.py", line 48, in loop
    self.qtile.loop()
  File "/home/pmizio/.local/lib/python3.8/site-packages/libqtile/ipc.py", line 242, in __exit__
    self.close()
  File "/home/pmizio/.local/lib/python3.8/site-packages/libqtile/ipc.py", line 252, in close
    loop.run_until_complete(self.async_close())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 591, in run_until_complete
    self._check_closed()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```
and after restart(super+ctrl+r) all back to work. Idk it is related but in previous iteration error not exist.

**Comment by tych0** [comment]
I think that's a different bug, related to https://github.com/qtile/qtile/issues/1346

Glad to hear it's working :)

**Comment by tych0** [comment]
I think the current test failure is legit, and I'm trying to understand why. But if more people can test this with other floating applications, that would be handy.

**Comment by tych0** [comment]
Ok, I think this is finally good to go.

**Comment by ramnes** [comment]
@Miziak does it work for you?

**Comment by Miziak** [comment]
@ramnes I will be able to check it tomorrow @ work ;)

**Comment by Miziak** [comment]
@ramnes it's working for me ;)

**Pull request merged**
