### PR TITLE
docs: Add missing requirement for Wlan widget

### PR DESCRIPTION
**Pull request by pawamoy**
For issue #1398 

What do you think of this (english is not my main language, so I kept it short)?

### CODE REVIEW

**Comment by ramnes** [comment]
LGTM, waiting to see what others think

**Comment by ramnes** [comment]
Okay, let's go ahead.

Could you please take the opportunity to remove all the `pythonwifi` stuff, here or in another PR? The library isn't maintained and we don't support Python 2.7 anymore, so let's get this out.

**Comment by pawamoy** [comment]
Of course, I'll do that in another PR since this one is aimed at the docs.

**Comment by ramnes** [comment]
Alrighty, thanks!

**Pull request merged**
