### PR TITLE
Ignore mouse wheel in GroupBox if desired

### PR DESCRIPTION
**Pull request by Etn40ff**
This PR adds the ability to disable wheel scrolling in GroupBox if desired via the flag ignore_mouse_wheel. This feature can be handy when scrolling with two fingers on a touchpad.

### CODE REVIEW

**Comment by ramnes** [comment]
Wouldn't it be more logical to have a `mouse_wheel` parameter that's `True` by default rather than the opposite? :innocent:

**Comment by Etn40ff** [comment]
Either way should be fine, I guess it is more a question of what is the behaviour on similar flags across qtile. I have no idea on this though. Feel free to change this in case.

PS: maybe `use_mouse_wheel` ?

**Comment by ramnes** [comment]
Yeah, fair enough! :+1:

**Comment by flacjacket** [comment]
@Etn40ff if you change to `use_mouse_wheel`, I'd be happy to merge this

**Comment by Etn40ff** [comment]
Done

**Comment by flacjacket** [comment]
Great, thanks for the fix!

**Pull request merged**
