### PR TITLE
Fix Clock Widget Respecting LC_TIME

### PR DESCRIPTION
**Pull request by parham-dev27**
Check Issue #4353 and fixed a little typo

### CODE REVIEW

**Comment by elParaguayo** [comment]
We actually set the locale during `qtile start`: 
https://github.com/qtile/qtile/blob/142dc80aae835afc1767d327560311f3ba648a58/libqtile/scripts/start.py#L83

Should we add `LC_TIME` here?

**Comment by parham-dev27** [comment]
The problem is `locale.getdefaultlocale()` returns the LANG variable from /etc/locale.conf. So the problem occurs here. 
` locale.setlocale(locale.LC_ALL, locale.getdefaultlocale())` would also fix it, if the LC_TIME variable is returned and not the LANG variable. 

For example if someone lives in Germany and has LC_TIME set to de_DE but has the system language (LANG) set to en_US, the problems occur because everything is going to be set to en_US. 

The only way to fix this is by getting the environment variable using  `os.getenv("LC_TIME")` and only setting the LC_TIME to the returned value.

**Comment by elParaguayo** [comment]
What I meant was adding the line to set LC_TIME in the same place,  rather than in the widget.

**Comment by parham-dev27** [comment]
My bad for not understanding what you meant. We can do that. 

Additionally we can set all other locals that the python locale module supports so no other problems occurs because of the wrong locale.

Supported locale categories by the python-locale module: 
LC_ALL
LC_COLLATE
LC_CTYPE
LC_MESSAGES
LC_MONETARY
LC_NUMERIC
LC_TIME 


P.S. Working on a PR, if you have any suggestions let me know :)

**Comment by parham-dev27** [comment]
@elParaguayo Closing in favor of #4356

**Pull request closed without merging**
