### PR TITLE
fixed margin xmonad layout

### PR DESCRIPTION
**Pull request by Ippolo**
the margin between the main pane and secondary panes was double

### CODE REVIEW

**Comment by flacjacket** [comment]
Isn't it supposed to have double the margin between windows? Looking at the other layouts, the use of the `margin` kwarg is used in this way. Note that you also have double the margin vertically between secondary windows when you have >=3 windows open.

**Comment by flacjacket** [comment]
Though it looks like Tree might specify different types of margins (left vs right, etc)

**Comment by Ippolo** [comment]
"This layout attempts to emulate the behavior of XMonad's default tiling scheme."
XMonad's default layout does not have double margin =)

**Comment by flacjacket** [comment]
Ah, well you got us there. I see no harm in this, especially since the default is `margin=0`, I'll merge this in, if anyone complains, we can start bikeshedding it.

**Pull request merged**
