### PR TITLE
[#4457] Introduce guess_browser() function

### PR DESCRIPTION
**Pull request by nikitabugrovsky**
Implement `guess_browser()` function

### CODE REVIEW

**Comment by m-col** [comment]
Hey, thanks for this. I think this is a bit out of scope as the slippery slope is that we do the same for every kind of app. The difference with a terminal is that, without out, new users can get stuck not knowing how to do anything, and it gives them an escape hatch through which they can edit their config, open other apps from the terminal etc to help them out of that situation. @elParaguayo @jwijenbergh thoughts?

**Comment by jwijenbergh** [comment]
> Hey, thanks for this. I think this is a bit out of scope as the slippery slope is that we do the same for every kind of app. The difference with a terminal is that, without out, new users can get stuck not knowing how to do anything, and it gives them an escape hatch through which they can edit their config, open other apps from the terminal etc to help them out of that situation. @elParaguayo @jwijenbergh thoughts?

I was about to comment the same thing. I think a terminal makes sense because it's really essential in just navigating with a tiling window manager, a browser less. So I prefer to not have this in core, maybe [qtile-examples](https://github.com/qtile/qtile-examples/)?

**Comment by m-col** [comment]
> I prefer to not have this in core, maybe [qtile-examples](https://github.com/qtile/qtile-examples/)?

Sounds good :)

**Comment by m-col** [comment]
@nikitabugrovsky if you'd be happy submitting it to qtile-examples, it would make a cool addition there :)

**Pull request closed without merging**
