### PR TITLE
Implemented stop qtile hook

### PR DESCRIPTION
**Pull request by tamis-laan**
A hook that get's triggered when stopping qtile.

### CODE REVIEW

**Comment by ramnes** [comment]
Let's call it "shutdown" and also implement "shutdown_once", as opposed to the existing "startup" and "startup_once". What do you think?

Also, what's your usecase behind this?

**Comment by tamis-laan** [comment]
On IRC there was a need for it, also there is a startup hook so why not a stop or shutdown hook. 

I chose the name stop instead of shutdown because the hook should also be triggered when restarting qtile, not just on shutdown. We can always change the name to shutdown if that is what you prefer.

**Comment by tych0** [comment]
I'm fine with adding this, but I agree we probably need two: one that runs on restart and one that doesn't. The _once mnemonic is what we have for startup, so it seems reasonable to use this nomenclature.

**Comment by tamis-laan** [comment]
What would shutdown_once look like? Is this a case that gets triggered on shutdown but not on restart?

**Comment by tych0** [comment]
shutdown_once would only trigger when not `self._restart is not None`, i.e. when we're not passing `--with-state` and the user has asked qtile to fully shut down, instead of just restarting to reload a new config.

**Comment by tych0** [comment]
I could also be convinced to call it `hook.restart` and `hook.shutdown`

**Comment by tamis-laan** [comment]
hm... yeah I don't know `shutdown_once` sounds rather confusing and isn't very obvious. However `restart` and `shutdown` breaks the already established convention. They are way more descriptive however.

**Comment by tamis-laan** [comment]
I have implemented the startup and shutdown hooks however when I `SIGTERM` qtile the shutdown routine is not called? Not sure how qtile deals with signals???

**Comment by tych0** [comment]
If you can squash all these into one commit, lgtm, thanks!

**Pull request closed without merging**
