### PR TITLE
Choose column for new windows in Columns layout

### PR DESCRIPTION
**Pull request by elParaguayo**
Adds ability to set which column receives new windows in `Columns` layout.

Based on this post: https://www.reddit.com/r/qtile/comments/17bice5/is_there_a_way_to_get_layouts_for_lefties/

### CODE REVIEW

**Comment by ramnes** [comment]
Why specify a column number in particular rather than keeping consistent with Monad layouts and using an `align` parameter to give a direction? It seems to me that the latter would be give a better experience, especially when `num_columns` is more than 2.

**Comment by elParaguayo** [comment]
How would that work if you had, say, 4 columns and wanted to add windows to the second one? It's a stupid example but I don't think align addresses it.

Happy to be proved wrong.

**Comment by elParaguayo** [comment]
I guess aligning allows us to do first and last columns which may be enough here.

**Comment by ramnes** [comment]
> How would that work if you had, say, 4 columns and wanted to add windows to the second one? It's a stupid example but I don't think align addresses it.

Why would you want that?

**Comment by elParaguayo** [comment]
> > How would that work if you had, say, 4 columns and wanted to add windows to the second one? It's a stupid example but I don't think align addresses it.
> 
> Why would you want that?

Never underestimate your users :D

Joking aside, it is very unlikely you'd ever want that. I'll switch this to `align`.

**Comment by ramnes** [comment]
Just tried the branch and I think the behavior is... weird?
* Window 1 opens fullscreen
* Window 2 opens on its right and gets focus
* Window 3 opens on the left column, even if the focus is on the right column

If we want a "mirrored" layout, the correct behavior would be that:
* Window 1 opens fullscreen
* Window 2 opens on its left and gets focus
* Window 3 opens on the current column (left)

**Comment by ramnes** [comment]
I think a simpler diff like this works better :)

```diff
@@ -239,7 +254,8 @@ class Columns(Layout):
     def add_client(self, client: Window) -> None:
         c = self.cc
         if len(c) > 0 and len(self.columns) < self.num_columns:
-            c = self.add_column()
+            prepend = (self.align is Columns._left)
+            c = self.add_column(prepend=prepend)
         if self.fair:
             least = min(self.columns, key=len)
             if len(least) < len(c):

```

**Comment by elParaguayo** [comment]
Yes. All makes sense. I'll update when I get a chance.

**Comment by ramnes** [comment]
I can push the changes if you want

**Comment by elParaguayo** [comment]
Sure. Go ahead. I'm traveling today so won't have access to my laptop until tomorrow and I may be too tired at that point as well!

**Pull request merged**
