### PR TITLE
Docs: add Wayland page, use base Window class to list commands, fix main contents formatting issue

### PR DESCRIPTION
**Pull request by m-col**
The title summarises the 3 commits. Please see their individual commit messages for deets.

### CODE REVIEW

**Comment by elParaguayo** [comment]
All looks pretty good.

A few things that will conflict with decorators but should be a quick enough fix for me.

I'll try building docs a bit later to have a check.

**Comment by elParaguayo** [comment]
`core.cmd_info` needs a docstring too.

**Comment by m-col** [comment]
Tests seem to be hanging in CI. When I run them locall with `python -m pytest` they work fine, but if I run them with `tox` then they hang, even locally. Hmm, not really sure what I'm looking at here.

**Comment by m-col** [comment]
Finally passing tests!

**Pull request merged**
