### PR TITLE
WIP: atomically apply window state changes

### PR DESCRIPTION
**Pull request by m-col**
This is a work in progress draft for some collaborative work with @jwijenbergh.

There are two main changes across these 5 commits:
 - a refactor of `Window.place()` and its use within the codebase. This becomes the single, exclusive point of entry for making geometric state changes on windows. `Window.{x,y,width,height}` are no longer intended to be used as direct setters, though they will continue to work (logging deprecation warnings). To reduce code duplication, all of its arguments have become kwargs so you can do e.g. `window.place(borderwidth=4)`, and that would be the canonical way to change borderwidth. This makes it much easier to control state changes on windows and group them for...
 - atomic state changes on windows and groups of windows. Higher-level operations such as changing groups are performed within the `Core.masked()` context manager so that configure requests sent to windows can be saved in a pending queue, and only when the final window is acked are the state changes applied simultaneously on all involved windows.

The (intended) effect is that every frame is rendered perfectly, addressing https://github.com/qtile/qtile/issues/2544. Noticably this means windows will not appear with the wrong geometry for a frame before fixing themselves, and adding/removing windows from a tiled layout results in the tiled layout changing atomically without any windows lagging their geomtry change for very short (but noticable) amount of time.

Current issues that need resolving:
 - when changing to a group, it seems as though the old buffer is being rendered for windows on the now-current group. This is the most noticable in terminals which might only commit new buffers when things are printed, so until a key is pressed or they are clicked, they render old content.
 - even before these changes, firefox displays a single pixel window before fixing itself (that's their doing, I believe). Since https://github.com/qtile/qtile/pull/2903 was merged, it doesn't seemt to fix itself with this patch also applied.

### CODE REVIEW

**Comment by jwijenbergh** [comment]
> This is a work in progress draft for some collaborative work with @jwijenbergh.
> 
> There are two main changes across these 5 commits:
> 
>     * a refactor of `Window.place()` and its use within the codebase. This becomes the single, exclusive point of entry for making geometric state changes on windows. `Window.{x,y,width,height}` are no longer intended to be used as direct setters, though they will continue to work (logging deprecation warnings). To reduce code duplication, all of its arguments have become kwargs so you can do e.g. `window.place(borderwidth=4)`, and that would be the canonical way to change borderwidth. This makes it much easier to control state changes on windows and group them for...
> 
>     * atomic state changes on windows and groups of windows. Higher-level operations such as changing groups are performed within the `Core.masked()` context manager so that configure requests sent to windows can be saved in a pending queue, and only when the final window is acked are the state changes applied simultaneously on all involved windows.
> 
> 
> The (intended) effect is that every frame is rendered perfectly, addressing #2544. Noticably this means windows will not appear with the wrong geometry for a frame before fixing themselves, and adding/removing windows from a tiled layout results in the tiled layout changing atomically without any windows lagging their geomtry change for very short (but noticable) amount of time.
> 

Thanks for the detailed pr! I am currently running this and it's really nice to see my terminals not have the dimension 'flicker'. 

> Current issues that need resolving:
> 
>     * when changing to a group, it seems as though the old buffer is being rendered for windows on the now-current group. This is the most noticable in terminals which might only commit new buffers when things are printed, so until a key is pressed or they are clicked, they render old content.

Could you give me a reliably way to reproduce this (if there is one). I am currently trying it out and I can't seem to get in this state

>     * even before these changes, firefox displays a single pixel window before fixing itself (that's their doing, I believe). Since [WL: Set tiled edge xdg_surface state when mapping #2903](https://github.com/qtile/qtile/pull/2903) was merged, it doesn't seemt to fix itself with this patch also applied.

Firefox works for me. I observe that firefox still goes to a default dimension for a second (like half my screen) and then goes to the whole screen in a layout with it as the only window. Is this something you observer or is firefox completely broken for you now?
The same holds with emacs for me. If I run emacs with emacsclient (making startup very fast as compared to normal emacs) it still happens but it goes to the correct dimension much quicker.
I will see if I can correct this behaviour.

**Comment by jwijenbergh** [comment]
> Here is a video of it happening. Note the firefox window opens on a different group from the current, and it is launched via a keybinding. Then I change to that group, show the small window highlighted by some double borders, and then when I open a foot window firefox fixes itself. Now, the interesting thing is that it only happens to this firefox profile, and if I launch firefox with a different profile it works fine! No clue what is up with that, or if it's their or our bug.

Now that is really weird indeed. I do not seem to have this issue :(. I've had weird firefox profiles before. Does it work with that profile on e.g. sway?

> I am getting occasional problems with dragging floating windows around, and also sometimes segfaults that crash Qtile back to TTY. Nothing reliable yet though so not much else to report.

Hmmmmmm, this is funny because I just had a segfault suddenly when reading that and opening a foot terminal, are you hacking me :eyes:

> The problem with this is that it doesn't seem very reliable, so I will play around with things to see if I can find a pattern. The 200ms cut-off thing is literally a race so maybe it happens when foot is too slow or something. Here is another video showing this. Note the block cursor at the bottom left corner of the window. When changing group goes fine, it's filled (foot is correctly responding to the activated state), but sometimes it is empty. Near the end of the video I type a key, and foot receives this correctly and the next rendered buffer has this key and the block cursor, so it does have keyboard focus correctly.

Interesting thanks, I hope I can get to the bottom of this. I will do some debugging and try various things this week and I will report back when I have some news.

**Comment by m-col** [comment]
Something that we do not do at all, which we could if it helps, is to remove listeners when unmapping and return them again upon mapping, rather than just setting them up at the first map event and then leaving them.

**Comment by jwijenbergh** [comment]
Sorry for taking so long on this. I have actually been making a toy wayland compositor in c++ in my free time as I want to more thoroughly understand wayland. I will get back to this when I have a good understanding of what the best way to do this is

**Comment by m-col** [comment]
No worries at all :smile: sounds great!

**Comment by m-col** [comment]
Another relevant issue: https://github.com/qtile/qtile/pull/2911

**Comment by jwijenbergh** [comment]
> This PR is stale because it has been open 90 days with no activity. Remove stale label or comment or this will be closed in 30 days.

go away bot, I want to pick this up eventually :D

**Comment by jwijenbergh** [comment]
@m-col should we close this or do you think we can rebase this on top of 0.16 pr?

**Pull request closed without merging**
