### PR TITLE
Add SwayNC widget

### PR DESCRIPTION
**Pull request by elParaguayo**
Adds a basic widget for interacting with the Sway Notification Centre.

Draft for now as we get comments/feedback from users.

### CODE REVIEW

**Comment by tych0** [comment]
Code looks reasonable to me, not that I know anything about sway's NC :). How is this different than libnotify?

**Comment by elParaguayo** [comment]
> Code looks reasonable to me, not that I know anything about sway's NC :). How is this different than libnotify?

This does not display the notifications itself. It provides a counter showing how many notifications there are. `swaync` provides the notification server but also provides a side panel with media info etc. This widget can also toggle displaying that panel.

**Comment by tych0** [comment]
I see, ok thanks!

**Review by arjan-s — APPROVED** [review]
This works exactly as I hoped! Thank you so much!

**Comment by elParaguayo** [comment]
> This works exactly as I hoped! Thank you so much!

Thanks. I'll tidy up the commits, fix the test failure and get this merged.

**Pull request merged**
