### PR TITLE
Experiment bring to front

### PR DESCRIPTION
**Pull request by senthilbaboo**
This is not for review, but only to show, how I think we can implement the window stack handling. I have not even tested it completely, but this will give a basic idea, i hope.

### CODE REVIEW

**Comment by tcld** [comment]
Thank you very much for the example. I'm not sure I'll find the time this weekend to rework #2029, next week is more likely. One detail I would like to improve upon is that you are just checking windows within the current group - ideally that would work by checking a screen region instead (i.e. usually a full screen, but we do have the concept of fake screens, too).

On a sidenote: Are you just insterested in the topic or do you actually want to implement it yourself?

**Comment by senthilbaboo** [comment]
> Thank you very much for the example. I'm not sure I'll find the time this weekend to rework #2029, next week is more likely. One detail I would like to improve upon is that you are just checking windows within the current group - ideally that would work by checking a screen region instead (i.e. usually a full screen, but we do have the concept of fake screens, too).

Looking into screen region for overlaps seems overkill to me and adds unnecessary complexity. As far as the fake screens are concerned, I believe we still would have only one active group. So I don't think, we need any special handling for that.

Things we may have to add is actually handling EWMH hints like above, below, dock, panel, sticky etc. and probably handler codes to check when they change. 

Hence functionality like pinning or sticking windows is just about changing those hints. 

> 
> On a sidenote: Are you just insterested in the topic or do you actually want to implement it yourself?

We can always share work here. There will be a lot of things to do here. And in this example, I could probably push some basic implementations and then we can start gluing things together. 

I just want to understand the general consensus and the opinions on the approach here before I spend more time.

I also have a lot of other ideas but we have to get this stacking right for most of those other things to work, like popup windows, semi transparent sticky windows, built in key logger etc.

**Comment by tcld** [comment]
> Looking into screen region for overlaps seems overkill to me and adds unnecessary complexity. As far as the fake screens are concerned, I believe we still would have only one active group. So I don't think, we need any special handling for that.

No, every (fake-)screen has it's own group. On top of that floating windows can technically exist outside of their groups screen. The latter case can probably ignored, but the former I consider important.

> We can always share work here. There will be a lot of things to do here.

I think there should be a basic implementation that can be merged in a reasonable amount of time, with further refinements being left for future PRs. I could create a draft-PR in the next few days and, hopefully, you can take a look, maybe add your own commits to it - how das that sound?

> Hence functionality like pinning or sticking windows is just about changing those hints.

I really hope so, that would make it a lot easier to handle.

> I just want to understand the general consensus and the opinions on the approach here before I spend more time.

I believe the consensus will be "less code is better" and "leveraging X is better".^^ About those further ideas you might have, there is probably a chance for a more balanced discussion. :)

**Comment by senthilbaboo** [comment]
> > Looking into screen region for overlaps seems overkill to me and adds unnecessary complexity. As far as the fake screens are concerned, I believe we still would have only one active group. So I don't think, we need any special handling for that.
> 
> No, every (fake-)screen has it's own group. On top of that floating windows can technically exist outside of their groups screen. The latter case can probably ignored, but the former I consider important.
> 
In this case, instead of just looking into windows or current screen or group, we could just look into all the windows that are currently visible on any of the screen. I think that should be fairly easy to implement as well. 

> > We can always share work here. There will be a lot of things to do here.
> 
> I think there should be a basic implementation that can be merged in a reasonable amount of time, with further refinements being left for future PRs. I could create a draft-PR in the next few days and, hopefully, you can take a look, maybe add your own commits to it - how das that sound?
> 
Sounds good. 
> > Hence functionality like pinning or sticking windows is just about changing those hints.
> 
> I really hope so, that would make it a lot easier to handle.
> 
> > I just want to understand the general consensus and the opinions on the approach here before I spend more time.
> 
> I believe the consensus will be "less code is better" and "leveraging X is better".^^ About those further ideas you might have, there is probably a chance for a more balanced discussion. :)
👍

**Pull request closed without merging**
