### PR TITLE
fix caption

### PR DESCRIPTION
**Pull request by zordsdavini**
still getting error in docs generation:
```
(qtile)  arnas@zordmachine  ~/out/qtile/docs   patch-6  make html
sphinx-build -E -W -b html -d _build/doctrees   . _build/html
Running Sphinx v3.0.1
Unmet dependencies for optional Widget: '.widget.pulse_volume.PulseVolume', No module named '_cffi_backend'
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 46 source files that are out of date
updating environment: [new config] 46 added, 0 changed, 0 removed
reading sources... [100%] qtile/lib/python3.8/site-packages/sphinx/ext/autosummary/templates/autosummary/module

Warning, treated as error:
/home/arnas/out/qtile/docs/qtile/lib/python3.8/site-packages/sphinx/ext/autosummary/templates/autosummary/base.rst:3:Error in "currentmodule" directive:
maximum 1 argument(s) allowed, 3 supplied.

.. currentmodule:: {{ module }}
make: *** [Makefile:46: html] Error 2
```

### CODE REVIEW

**Comment by tych0** [comment]
What version of sphinx? I don't get this, oddly.

**Comment by zordsdavini** [comment]
3.0.1. I run it manually. Removed caption at all, because didn't know how to add it nicely

**Comment by zordsdavini** [comment]
I suggest to merge this diff, because http://docs.qtile.org/en/latest/manual/config/without-dm.html looks with error

**Comment by tych0** [comment]
Can you squash it to one? LGTM otherwise

**Comment by zordsdavini** [comment]
squashed :)

**Comment by ramnes** [comment]
Thanks!

**Pull request merged**
