### PR TITLE
Fixes #394

### LINKED ISSUE #394: layout.Tile border_focus gives NameError if modified
When setting `layout.Tile` with `border_focus` argument, i.e. with:
```python
layout.Tile(ratio=0.5, border_focus="ffffff") 
```
Qtile crashes and says:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/libqtile/manager.py", line 585, in _xpoll
    r = h(e)
  File "/usr/lib/python2.7/dist-packages/libqtile/manager.py", line 892, in handle_UnmapNotify
    self.unmanage(e.window)
  File "/usr/lib/python2.7/dist-packages/libqtile/manager.py", line 406, in unmanage
    c.group.remove(c)
  File "/usr/lib/python2.7/dist-packages/libqtile/group.py", line 215, in remove
    self.focus(nextfocus, True)
  File "/usr/lib/python2.7/dist-packages/libqtile/group.py", line 156, in focus
    l.focus(win)
  File "/usr/lib/python2.7/dist-packages/libqtile/layout/max.py", line 46, in focus
    self.group.layoutAll()
  File "/usr/lib/python2.7/dist-packages/libqtile/group.py", line 92, in layoutAll
    self.layout.layout(normal, screen)
  File "/usr/lib/python2.7/dist-packages/libqtile/layout/base.py", line 54, in layout
    self.configure(i, screen)
  File "/usr/lib/python2.7/dist-packages/libqtile/layout/tile.py", line 189, in configure
    bc = self.group.qtile.colorPixel(self.border_focus)
  File "/usr/lib/python2.7/dist-packages/libqtile/utils.py", line 99, in wrap
    ret = f(self, *args)
  File "/usr/lib/python2.7/dist-packages/libqtile/manager.py", line 364, in colorPixel
    return self.conn.screens[0].default_colormap.alloc_color(name).pixel
  File "/usr/lib/python2.7/dist-packages/libqtile/xcbq.py", line 288, in alloc_color
    self.cid, len(color), color
BadName: <xcb.xproto.NameError object at 0x319c908>
```

### PR DESCRIPTION
**Pull request by aniruddhkanojia**

### CODE REVIEW

**Comment by aniruddhkanojia** [comment]
The build should be run again with corrected tests

**Comment by kynikos** [comment]
If you rebase and repush this branch on your other recently merged commit, the build will be rerun automatically.

**Comment by aniruddhkanojia** [comment]
I accidentally closed and reopened it.
Seems it did the job.
 :stuck_out_tongue:

**Comment by kynikos** [comment]
Well, but if you don't rebase it on the test fix, I predict it's going to fail ^^'

**Comment by aniruddhkanojia** [comment]
I see your point :disappointed:

**Comment by aniruddhkanojia** [comment]
It worked :smile:

**Comment by tych0** [comment]
Awesome thanks! Merged as 77a3f181ebc0df19a8f9fcbe9f4b7984c3df2830

**Pull request closed without merging**
