### PR TITLE
Dmenu wrapper for #851

### PR DESCRIPTION
**Pull request by zordsdavini**
still in progress
issue: https://github.com/qtile/qtile/issues/851

### CODE REVIEW

**Comment by zordsdavini** [comment]
08:41 < zordsdavini> could someone help a little bit with coding?
08:42 < zordsdavini> I wanted to add dmenu wrapper and add some extention like window list and run commands through dmenu
08:43 < zordsdavini> the thing is I set config from config.py, then adding some stuff and another call to extention will have this added stuff. I don't want that
08:43 < zordsdavini> at first I used configurable
08:44 < zordsdavini> later removed and added simple dict
08:44 < zordsdavini> but this added stuff still exist
08:45 < zordsdavini> I deleting Dmenu class and each time creating new config for separate extention

**Comment by zordsdavini** [comment]
config.py should have something like:

    from libqtile import extention
    mod = 'mod4'
    keys = [
        ...
        Key([mod], 'l', lazy.run_extention(extention.WindowList)),
        Key([mod], 'r', lazy.run_extention(extention.DmenuRun)),
        ...
    ]
    extentions = {
        'dmenu': {
            'prompt': "→",
            'font' : "Andika-8",
            'background' : "#15181a",
            'foreground' : "#00ff00",
            'selected_background' : "#079822",
            'selected_foreground' : "#fff",
            'height' : 24,
        }
    }

**Comment by zordsdavini** [comment]
still work in progress. Needs to be done:
* python2 support (when we will drop that support?)
* glitch in window list extension

**Comment by flacjacket** [comment]
You can add `  # noqa` to the end of the lines to avoid those sorts of problems with flake8

**Comment by flacjacket** [comment]
Thanks for this, I think it looks good! If you are able to add some docs for this, that would be great!

**Pull request closed without merging**
