### PR TITLE
Draft: ThreeCol layout

### PR DESCRIPTION
**Pull request by tim-kilian**
Hej, 

I used xmonad before, where there was I layout called [XMonad.Layout.ThreeColumns](https://hackage.haskell.org/package/xmonad-contrib-0.17.0/docs/XMonad-Layout-ThreeColumns.html). It's a layout similar to tall but with three columns. Mainly the ThreeColMid layout interest me, because the other one is somewhat achievable with the column layout. 

The spawning is a bit different from the one of Xmonad: 
```
|-----|-------|-----|
|  3  |       |  2  | 
|     |       |-----|
|-----|   1   |  4  | 
|  5  |       |-----|
|     |       |  6  | 
|-----|-------|-----|
```

For me it is more intuitive. 

Todo:
- [x] Layout configuration
- [x] Layout icon
- [ ] Add commands for window management
- [ ] Add tests
- [ ] Maybe increase count of main windows?

### CODE REVIEW

**Comment by jwijenbergh** [comment]
I like this layout a lot, good work. Did you see https://github.com/qtile/qtile/pull/2606 though? I believe that is the same layout

**Comment by tim-kilian** [comment]
Hej @jwijenbergh, 
no I have not seen that. Thanks for the reference. I believe it is the same intention! I've tested it and it works just like my draft. I also thought that the new_client_position should be configurable tho. Because I do not like the default xmonad spawning.

**Comment by tim-kilian** [comment]
I thought about this again. And maybe my implementation is more like the qtile [Columns](https://docs.qtile.org/en/latest/manual/ref/layouts.html#columns) layout and not the xmonad [ThreeColumns](https://docs.qtile.org/en/latest/manual/ref/layouts.html#columns). I'll rework this to fit as a extension of the Columns layout. Like I said, the current Columns layout does not fit my needs. The main window is not centered there. You can move the windows around, so it is correct, but that is too much work and the orientation should be automated.

**Comment by zys5945** [comment]
Workflow failing at unrelated changes:
`libqtile/layout/three.py:117:34: BLK100 Black would make changes.`

This PR is ready for review / merge

**Comment by elParaguayo** [comment]
Not sure if any work is still happening on this one but, if it is, we may need a new icon as the one in the PR is very like the icon that we've got for `MonadThreeCol`. 

It there's no active work on this then should we close the PR?

**Pull request closed without merging**
