### PR TITLE
Fix and test issue #2198

### PR DESCRIPTION
**Pull request by Tokariew**
Fix for issue #2198 

Test is passed. I tested for two cases which I described in issue.

### CODE REVIEW

**Comment by tych0** [comment]
Looks like there's a pep8 error in here, but the patch itself looks good to me.

Can you also include your writeup from the issue in your commit message?

Thanks!

**Comment by Tokariew** [comment]
Not sure exactly how should I do it?
Ammending message to commit will require force push?

**Comment by tych0** [comment]
Yep, force pushing to this branch would be totally fine, thanks!

**Comment by Tokariew** [comment]
Done, I will close my issue.

**Comment by tych0** [comment]
Looks like there's still a pep8 failure,

>   test/layouts/test_tile.py:158:5: E265 block comment should start with '# '

**Comment by tych0** [comment]
Great, thanks!

**Pull request merged**
