### PR TITLE
Adds the option for WindowName widget to use class instead of name as addressed in #2154

### PR DESCRIPTION
**Pull request by Masacaai**
This is my first PR, so do let me know if I'm supposed to do something differently. Really thankful to @mbenford  for helping me out!

### CODE REVIEW

**Comment by Masacaai** [comment]
I'm sorry if the code feels a bit newbie-ish. If there's a better way to do what I did, please let me know!

**Comment by elParaguayo** [comment]
Could we do this by letting the user define the output format as a parameter? By using python's string formatting, we could limit long strings. You could make the `state`, `window.name` and `w.window.get_wm_class()[0]` values available to the formatter for the user to use as they wish.

e.g. `"{state}{name:.20}"` to only show max 20 characters of the window name.

That way you have much more flexibility over the display.

**Comment by elParaguayo** [comment]
Don't think you need to close this! Was just suggesting an alternative approach.

**Comment by Masacaai** [comment]
Oh, I know! I just felt that your method was better. I'm going to see if there's a way to implement what you suggested and reopen my pull request

**Comment by elParaguayo** [comment]
Great.

Have a look at the [memory widget](https://github.com/qtile/qtile/blob/master/libqtile/widget/memory.py). It's a good example of how the user can specify a format string.

**Comment by mbenford** [comment]
If I may weigh in, I tried to truncate and show ellipsis by using only Python's string formatting, but I failed (not a Python expert myself, so it could totally be my own fault). Perhaps `format` could be either a string or a function so one could freely decide the final value for the widget to show, but that would be the case for all widgets, not only `WindowName`.

**Comment by elParaguayo** [comment]
Not your fault - I'm pretty sure python's string format doesn't have the ability to put in an ellipsis. However, the `TextLayout` used by Qtile to display text will add an ellipse if the text is longer than the size of the layout (and not set to wrap) so, if you set a max size for a task item, you should get your ellipse.

https://github.com/qtile/qtile/blob/c355e2c8fe419f00ae7284dcdbe7032a9728d5fe/libqtile/drawer.py#L48

**Comment by Masacaai** [comment]
I've opened up a new PR with a format attribute for the WindowName widget.  Check #2178

**Pull request closed without merging**
