### PR TITLE
Fix 'extension' spelling; expand documentation

### PR DESCRIPTION
**Pull request by kynikos**
b788942: I have renamed the `extention` subpackage to `extension` (correct spelling), temporarily preserving backwards compatibility.

be4f532: I have listed all the supported variables in the documentation, although still with TODO descriptions.

3daba53: I have initialised the documentation of extensions.

### CODE REVIEW

**Comment by zordsdavini** [comment]
I never had time to start with documentation :( Nice.

**Comment by kynikos** [comment]
@zordsdavini I wish I had more time to contribute too ^^ Anyway apparently there's something wrong with the indentation in `dmenu.Dmenu`'s docstring that breaks the build of the docs, I'll have a better look at it tomorrow...

**Comment by flacjacket** [comment]
Great, thanks for this, looking forward to it!

**Comment by kynikos** [comment]
Yay, I've made it compile, and also added a warning about `-h` which is unsupported by the original dmenu (for example it's supported by dmenu2). I don't think I'll further expand the TODO items in this PR, hopefully seeing them in the docs will encourage somebody else to contribute, if you still agree to merge it of course.

**Comment by zordsdavini** [comment]
@kynikos you did grate job. 
@flacjacket please merge it

**Comment by flacjacket** [comment]
Great, thanks for the fixes

**Pull request merged**
