### PR TITLE
RFC: Revert layout serialization

### PR DESCRIPTION
**Pull request by flacjacket**
While having layout serialization is nice, the current implementation has been a bit buggy and introduced some bugs of its own on restarts (potentially #764, in addition to unreported issues noted on IRC). Some of the coding practice in this always worried me a bit and it may be good to roll this code back until it can be properly vetted and implemented. Let me know what you guys think about this, ping @tych0 @Roger @dequis (and I think @ramnes was also reporting having restart problems on IRC).

### CODE REVIEW

**Comment by dequis** [comment]
Is this really all of it? What about stuff like `test/test_restart.py` or commits like 6f64d135f63d16c51a6fa30a8bd7eb15fea1a171 (with a very vague commit message and a very suspicious looking fix).

These diffs are too noisy... it looked somewhat ok in the pull request diffs but didn't realize until now that it meant a bunch of small commits doing weird looking stuff and then reverting it.

**Comment by flacjacket** [comment]
Relevant PRs #672, #711, #725, #736, #740. I didn't really realize how much stuff was touched, I'll go and try to clear it out.

**Comment by flacjacket** [comment]
Things I've left in:

From manager.py: `Qtile.cmd_get_state`, `Qtile.cmd_get_info`

test/test_serialize.py: This test isn't the greatest, it didn't catch all serialization problems, but I cleaned this up a bit from `test/test_restart.py`, and it's a decent starting point to fixing the serialization problems that the PR's "fixed"

**Comment by flacjacket** [comment]
Actually, test/test_serialize relies on things that should be taken out, so I'm pulling that, too.

**Comment by flacjacket** [comment]
I know where dx stands on this, does anyone else have an opinion?

**Comment by tych0** [comment]
On Thu, Oct 01, 2015 at 02:44:25PM -0700, Sean Vig wrote:
> I know where dx stands on this, does anyone else have an opinion?

I abstain, since I dropped the ball as well :)

**Comment by Roger** [comment]
well, i guess it's the best to revert this until we have a proper implementation.. actually, i'm suffering this issues too

**Comment by flacjacket** [comment]
Reverted.

**Pull request closed without merging**
