### PR TITLE
Fix default update_interval in ThreadPoolText

### PR DESCRIPTION
**Pull request by elParaguayo**
Previous default of "None" caused widgets to constantly update
resulting in high CPU usage. New default is update interval of
1 minute.

### CODE REVIEW

**Comment by tych0** [comment]
I think the previous default was 600, any reason to diverge from that?

**Comment by elParaguayo** [comment]
10 mins seemed long to me but, if that's the case, I'm free to change it as a user! 

Have changed to old number.

**Review by ramnes — APPROVED** [review]

**Comment by elParaguayo** [comment]
Just thinking about this - let me check the old widgets that used `ThreadPoolText` to make sure this change doesn't break them. I think it's sensible to have a default timer as opposed to None to prevent the CPU issue but some of the widgets may not have that problem.

**Comment by elParaguayo** [comment]
All ok. 5 widgets used `ThreadPoolText` before change and all of these set a default `update_interval` so nothing to change.

**Comment by tych0** [comment]
Great, thanks!

**Pull request merged**
