### PR TITLE
some quick fixes

### PR DESCRIPTION
**Pull request by w1ndy**

### CODE REVIEW

**Comment by w1ndy** [comment]
Could someone review these patches please? qtile/qtile#626 can be solved with these patches as mentioned in qtile/qtile#658.

**Comment by tych0** [comment]
Yep, I'll review when I have time.

**Comment by dequis** [comment]
I skimmed it a while ago, my reaction was basically "oh god these aren't quick fixes what the fuck is all this stuff". I guess it would make more sense to review commit per commit.

**Comment by w1ndy** [comment]
The only major modification that might affect other components is 'synchronization fix', which adds a delegated free mechanism before the event loop is closed. Others are just plain simple bug fixes as described in each commit....

**Comment by tych0** [comment]
I've left a few comments. Most of the early commits look good, although I'm not sure about the synchronization stuff. If you want, I can cherry pick what I like (pending answers to my questions) and we can talk about the rest.

Sorry for the delay, last few weeks have been exceptionally busy for me.

**Comment by w1ndy** [comment]
Just do whatever you like ;). I've been quite occupied with my school project lately but I'm sure I'll find some time looking into those problems as soon as possible.


 

-------- 原始邮件 --------
发件人：Tycho Andersen <notifications@github.com>
时间：周六 5月16日 07:15
收件人：qtile/qtile <qtile@noreply.github.com>
抄送：Charles Weng <mystery.wd@gmail.com>
主题：Re: [qtile] some quick fixes (#660)

**Comment by tych0** [comment]
On Fri, May 15, 2015 at 04:28:10PM -0700, Charles Weng wrote:
> Just do whatever you like ;). I've been quite occupied with my school project lately but I'm sure I'll find some time looking into those problems as soon as possible.

Ok, sounds good. Thanks for the patches :)

**Comment by tych0** [comment]
Ok, I've picked a few of these that I like, go ahead and re-open with what else you want merged when you have time to discuss. Thanks again!

**Pull request closed without merging**
