### PR TITLE
Fix issue #2089

### PR DESCRIPTION
**Pull request by DorianGray**
issue caused in https://github.com/qtile/qtile/pull/2084
simple logic error, fixes https://github.com/qtile/qtile/issues/2089

### CODE REVIEW

**Comment by m-col** [comment]
Cool thanks. Any chance we could get a test so it won't break again?

**Comment by DorianGray** [comment]
As soon as I can get the tests running locally, absolutely!

**Comment by ramnes** [comment]
Let's make @dequis happy and merge this as is. A test in another PR would still be welcome. :)

**Comment by dequis** [comment]
<3

**Comment by DorianGray** [comment]
I think there are more bugs in this code. I have additional commits related on my local including tests! Should be ready soonish

**Pull request merged**
