### PR TITLE
feature: kill window via tasklist widget by using middle mouse click

### PR DESCRIPTION
**Pull request by graves501**
Hi, 

since I'm fairly new to qtile and not that experienced in Python, I couldn't figure out how to kill a window via the tasklist widget without directly changing the `tasklist.py` file itself.

I'm using the middle mouse button to kill the clicked window, since I was able to implement that quite easily in AwesomeWM.

Thanks for your efforts, so far I'm really liking qtile!

### CODE REVIEW

**Comment by ramnes** [comment]
Hey there,

This PR is not needed for what you want to achieve, you can give `mouse_callbacks={...}` to any widget. :)

Thanks for the kind words!

**Comment by graves501** [comment]
@ramnes

Hi, thanks for the response.

I am aware of the `mouse_callbacks`, but without changing the widget's implementation, how are you supposed to pass the clicked element of the widget to the callback? 

If you look into the code, I did pass a function to the `mouse_callbacks`, but from within the `tasklist` widget.

Why?

`get_clicked` is NOT exposed. 

In the callback function passed to the widget I would need to be able to do something like:

```python
c = CommandClient()
clicked = c.navigate("widget", "tasklist").call("get_clicked")
clicked.kill()
```

E.g. I want to close the Chromium window, but the focused window is Firefox.

image

There is even a [Pull Request](https://github.com/qtile/qtile/issues/856) from 2016 regarding these click events, here it was about using `window.toggle_minimize()`, in my case it would simply be `window.kill()`. 

The solution for the 2016 issue was to modify the internals of `tasklist`.

**Comment by elParaguayo** [comment]
```python
def tasklist_kill(widget):
    window = widget.clicked
    if window is not None:
        window.kill()

# Then add this to your mouse callbacks:
mouse_callbacks =  {"Button2": lazy.widget["tasklist"].function(tasklist_kill)}
```

**Comment by graves501** [comment]
@elParaguayo 

Thank you so much for taking the time to reply! Very much appreciated.

I agree, it doesn't make sense to make this kind of behaviour the default, since this is just my personal preference.

I apologize for opening this "discussion" - this should've been a question on Discord/IRC instead. I did try to find a solution in the documentation, but clearly failed - I'm still new to the whole qtile "eco-system".

Thanks once again - at least there is a chance that this PR might serve/help someone in the future.

**Comment by elParaguayo** [comment]
No need to apologise. Thanks for taking the time to learn and want to make qtile better. 

Feel free to keep asking questions etc as needed.

**Pull request closed without merging**
