### PR TITLE
Store windows in list instead of set

### LINKED ISSUE #1541: How are the tasks in TaskList sorted?
It seems that the task in the TaskList are sorted differently than what the `lazy.layout.next()` thinks. As  when I use the `lazy.layout.next()` the focus in the TaskList jumps around but seldom on the task I would expect...

### PR DESCRIPTION
**Pull request by kapilpokhrel**
Since set is unordered, output of TaskList like widget was unpredictable.
So, keeping windows in list keeps them in order by which they are created.

Output of TaskList Before the fix:
window 4 | window 1 | window 3|  window 2 |
After the fix:
window 1 | window 2 | window 3 | window 4 |

Fixes #1541

### CODE REVIEW

**Comment by tych0** [comment]
Can you add a test for window ordering so we preserve this property?

**Comment by kapilpokhrel** [comment]
> Can you add a test for window ordering so we preserve this property?

Sorry, i don't think i can do this

**Comment by tych0** [comment]
Why not?

**Comment by kapilpokhrel** [comment]
I am not quite familiar with it enough yet.
Sorry, once again.

**Comment by tych0** [comment]
That's fine, we can hold this PR until you are familiar with it. Generally I don't like to merge bug fixes without tests, since we have nothing preventing us from breaking this code again. Thanks for looking at it!

**Comment by kapilpokhrel** [comment]
Ok, thanks

**Comment by kapilpokhrel** [comment]
> Can you add a test for window ordering so we preserve this property?

You mean, i need to write a test to check weather the windows are stored in correct order by which they are created?

**Comment by tych0** [comment]
Yes, whatever ordering you're trying to enforce with this PR, which I think is creation order.

**Comment by kapilpokhrel** [comment]
Yes, ok

**Comment by kapilpokhrel** [comment]
```
def test_window_order(manager):
	windows_name = ["one","two","three","four","five","six","seven","eight","nine","ten"] # windows to add
	windows = {}	
	# Add windows one by one
	for win in windows_name:
		windows[win] = manager.test_window(win)

	# Windows must be sotred in the same order as they were created
	assert windows_name == manager.c.group.info()["windows"]

	# Randomly remove 5 windows and see if orders remains persistant
	for i in range(5):
		win_to_remove = random.choice(windows_name)
		windows_name.remove(win_to_remove)
		manager.kill_window(windows[win_to_remove])
		del windows[win_to_remove]
		assert windows_name == manager.c.group.info()["windows"]
```
Is this ok?

**Comment by tych0** [comment]
Looks good to me!

On Sun, Aug 29, 2021, at 2:06 AM, Kapil Pokhrel wrote:
> 
> 
> `def test_window_order(manager):
> 	windows_name = ["one","two","three","four","five","six","seven","eight","nine","ten"] # windows to add
> 	windows = {}	
> 	# Add windows one by one
> 	for win in windows_name:
> 		windows[win] = manager.test_window(win)
> 
> 	# Windows must be sotred in the same order as they were created
> 	assert windows_name == manager.c.group.info()["windows"]
> 
> 	# Randomly remove 5 windows and see if orders remains persistant
> 	for i in range(5):
> 		win_to_remove = random.choice(windows_name)
> 		windows_name.remove(win_to_remove)
> 		manager.kill_window(windows[win_to_remove])
> 		del windows[win_to_remove]
> 		assert windows_name == manager.c.group.info()["windows"]
`

**Comment by tych0** [comment]
LGTM, I just squashed the CI fixes into their respective commits, and when this passes CI it's good to go. Thanks!

**Pull request merged**
