### PR TITLE
Added support for single_border_width for Columns layout

### PR DESCRIPTION
**Pull request by matthewsia98**
Added single_border_width key for Columns layout.
Old ```border_on_single``` key is still respected so new key only takes effect if ```border_on_single = True```

### CODE REVIEW

**Comment by m-col** [comment]
LGTM, thanks! I've resolved a conflict and enabled auto-merge, it will get merged if/when the tests pass :)

**Comment by matthewsia98** [comment]
fixed isort violation

**Comment by matthewsia98** [comment]
@m-col sorry for ping

**Comment by m-col** [comment]
Thanks!

**Pull request merged**
