### PR TITLE
follow maximizing window

### PR DESCRIPTION
**Pull request by zordsdavini**
Added option "follow_max": False. If it is set to True - if there are only two windows then cmd_maximized will follow maximized window
https://github.com/qtile/qtile/issues/594

### CODE REVIEW

**Comment by tych0** [comment]
I'm confused; isn't there logic to do this directly above (i.e. the if len(self.clients) < 3 bit)? It seems as though that is broken?

**Comment by zordsdavini** [comment]
if I add all logic to < 3 then it would be triggered and for == 1. Sure it will not crash qtile, because cmd_next will give same client. I rewrited to separate logic to other function and with monadtall flow (ratio, _med_ratio, focused)

**Comment by zordsdavini** [comment]
buggy explaination about what it does https://www.youtube.com/watch?v=gJKbDxShyUU (follow focused window)

**Comment by zordsdavini** [comment]
I found video about monadTall https://www.youtube.com/watch?v=NE6IQdwjzso
1st 8 seconds shows how maximization works and here sees how toggling leaves focus in small window. In this case focus should follow bigger window.

**Comment by zordsdavini** [comment]
I did rebase for newer code

**Comment by tych0** [comment]
Sorry, I'm confused. It looks like some other commits got in here twice?

**Comment by tych0** [comment]
Ok, I watched the second video, and it seems to me the behavior in the video is correct. Why should it switch focus if all that is being toggled is the maximized flag?

You could implement this in your config with something like:

```python
def mymaximize(qtile):
    qtile.currentLayout.maximize
    if ...:
        qtile.currentLayout.focus_next()
```

And leave the default behavior the same in core, since it seems like quite a special case.

**Comment by zordsdavini** [comment]
this following is additional help to make everything easier. Your config doesn't work for me. I'll try to find some more examples in qtile-examples. But I don't think it is my special case, this is maximization with additional functionality, what can be switched on by config

**Comment by zordsdavini** [comment]
ok, I created it in local config, so I close it and sugest to save it in examples
https://github.com/qtile/qtile-examples/pull/26

**Pull request closed without merging**
