### PR TITLE
Add window margins for different directions

### PR DESCRIPTION
**Pull request by arczan2**
Changed window margins behavior in place() method. Now it can also be passed as list of ints [N E S W] like Bar margins.
I think It might be helpful when creating some complex Layouts.

### CODE REVIEW

**Comment by tych0** [comment]
Do you have a sample layout that would benefit from this? Right now I think this would be dead code in the tree.

**Comment by arczan2** [comment]
> Do you have a sample layout that would benefit from this? Right now I think this would be dead code in the tree.

I got this idea when I was modifying the Columns layout. I wanted to get different gaps between columns and rows:
`layout.Columns(row_margin=10, col_margin=2, border_focus='#777777'),`

**Comment by tych0** [comment]
Ok, I'd like to see some in-tree code that uses this before we land it, and ideally some tests as well.

**Comment by arczan2** [comment]
I've used this margins in xmonad layouts. In my opinion It is more readable now

**Review by ramnes — APPROVED** [review]
LGTM! Maybe we could go a step further and modify all layouts that take a `margin` argument so that they accept such a list? It can be done in another PR. :)

**Comment by tych0** [comment]
Can you show an example of how you've used it in the commit message?

**Comment by arczan2** [comment]
> Can you show an example of how you've used it in the commit message?

Do you want me to create a new empty commit with massage: "Make xmonad layout use list of window margins instead of calculating x, y, width and height values"?
Did I understand you correctly?

**Comment by arczan2** [comment]
> LGTM! Maybe we could go a step further and modify all layouts that take a `margin` argument so that they accept such a list? It can be done in another PR. :)

I can take care of it :)

**Comment by arczan2** [comment]
So I've checked all layouts. Most of them work with margins list without any code changes :) The only thing I would do is to update the documentation:
`("margin", 0, "Margin of the layout(int or list of ints [N E S W])")`

The only one that need special attention is xmonad (Tall and Wide). The problem is that this layout does not add margin from one side of main window, to avoid "double gap"  in the middle. This can be solved by adding new parameter `main_margin` but I don't know if it is a good idea. That will lead us to the situation where xmonad layout will have parameters: `single_margin, margin, main_margin`.`

**Comment by ramnes** [comment]
Cool! Can you edit the docstrings then? Let's ignore the Monad layouts for now. :)

**Comment by arczan2** [comment]
> Cool! Can you edit the docstrings then? Let's ignore the Monad layouts for now. :)

Done! 
It looks like failure is unrelated :(

**Comment by ramnes** [comment]
Merged! Thank you @arczan2. :)

**Pull request merged**
