### PR TITLE
Add keybinding images generator for FR-BE keyboards

### PR DESCRIPTION
**Pull request by gaelj**
no_modifier

### CODE REVIEW

**Comment by elParaguayo** [comment]
How much of this is duplicated from `gen-keybinding-img`

It feels like we should really have a single script with the main methods in it and the ability to specify a keyboard layout as an option.

**Comment by gaelj** [comment]
There are 2 kinds of modifications : key locations and key geometries. I will look into it

**Comment by gaelj** [comment]
Layout country is now a script argument, with only 1 script handling default en-US and the new fr-BE

**Comment by gaelj** [comment]
@elParaguayo what do you think about the latest changes ? Anything more to improve ?

**Comment by elParaguayo** [comment]
Sorry - been looking at lots of different things, will try to get to this one soon. Will take a bit more time as it's a part of the code that I'm less familiar with.

**Comment by m-col** [comment]
Sorry for letting this get stale, I've re-opened it!

**Comment by m-col** [comment]
@zordsdavini would you happy to take a look at this?

**Pull request closed without merging**
