### PR TITLE
Improve CheckUpdates docs

### PR DESCRIPTION
**Pull request by elParaguayo**
This PR includes the available configuration options in the docs so users can see which option to use without looking at the source code.

### CODE REVIEW

**Comment by m-col** [comment]
Perhaps we should move the dictionary to out of the class (or to a class attribute) and use its data to complete the docstring. This way, future changes to the dictionary will definitely propagate to the docs.

**Comment by elParaguayo** [comment]
> Perhaps we should move the dictionary to out of the class (or to a class attribute) and use its data to complete the docstring. This way, future changes to the dictionary will definitely propagate to the docs.

Yes. That would be nice.

See also #3789

**Comment by m-col** [comment]
I wasn't sure if this was ready for review but LGTM :)

**Comment by Neo-29** [comment]
I might be off topic but... Is there a way to update the information ( number of updates) after having updated?
The only way to.. I found is re spawn ( mod shift R) to update the widget.
If any tips... I'm all ears 😊. Tks.

**Comment by elParaguayo** [comment]
How are you triggering the update? If you do it by setting the `execute` parameter and then clicking on the widget, the widget will update after the update process is complete.

If not, you could run `qtile cmd-obj -o widget checkupdates -f force_update`.

**Comment by Neo-29** [comment]
> How are you triggering the update? If you do it by setting the `execute` parameter and then clicking on the widget, the widget will update after the update process is complete.
> 
> If not, you could run `qtile cmd-obj -o widget checkupdates -f force_update`.
Tks for the answer, 
Where should I put this command? ( sorry I'm quite new on qtile)

**Comment by elParaguayo** [comment]
You can just run it in a terminal.

**Comment by Neo-29** [comment]
> You can just run it in a terminal.

So can be used in `execute` command?

**Comment by elParaguayo** [comment]
No. The idea of the execute command is to put in the command that actually runs the system update for you. After that has run, the widget would update the text.

**Comment by Neo-29** [comment]
> No. The idea of the execute command is to put in the command that actually runs the system update for you. After that has run, the widget would update the text.

So.... How can I use this command?
Spawn?

**Comment by Neo-29** [comment]
> No. The idea of the execute command is to put in the command that actually runs the system update for you. After that has run, the widget would update the text.

So.... How can I use this command?
Spawn?

**Comment by elParaguayo** [comment]
You've got plenty of options:
- If you've opened a terminal to update your system, type that command into the terminal when you're finished.
- Bind a key to `lazy.widget["checkupdates"].force_update()`
- Use the `execute` command as it's intended and use the widget to run the system update command. That way you don't need a separate command to update the widget, it's done automatically.

**Pull request merged**
