### PR TITLE
Add spotify widget 

### PR DESCRIPTION
**Pull request by ThanosApollo**
### It ain't much but it's honest work, hope I didn't mess anything up
- Created a spotify widget which I've been using the past week, *inspired by the moc widget*
- I tried to make it using dbus_next *but* I was only able to create bugs, so i settled with dbus-python, hope its good enough
- "Buttons" are using **spotify-control** [AUR](https://aur.archlinux.org/packages/spotify-control) [Github](https://github.com/J00LZ/spotify-control)
  - I was already using it so I thought it was good enough, and there was no need to recreate play/pause etc. functions 
    - +Easy to install via the AUR 
    - +Less code to maintain
- I'm new here so any comments/fixes are welcomed.

### CODE REVIEW

**Comment by elParaguayo** [comment]
Hi there. Thanks for wanting to contribute to qtile. 

What does this add over the Mpris2 widget? I think that can do everything that this widget seems to do.

**Comment by ThanosApollo** [comment]
> Hi there. Thanks for wanting to contribute to qtile.
> 
> What does this add over the Mpris2 widget? I think that can do everything that this widget seems to do.

Hello! 
- I was using Mpris2 widget but if I'd open a second media player(with spotify paused) such as vlc it would crush or give "No metadata for current track"(I guess it was picking metadata from vlc, where i usually watch movies or stream youtube videos).
- I just wanted a widget that picks metadata **only** from spotify, so it will be easy to jump on and off listening to music. Without my widget crushing or pick metadata from other programs/apps. Similar functionality to moc widget, but for spotify.

**Comment by elParaguayo** [comment]
You can do that with the Mpris2 widget. Just set `objname="org.mpris.MediaPlayer2.spotify"` when configuring the widget and it will only listen to Spotify messages. If that doesn't work then it's a bug that should be fixed!

**Comment by ThanosApollo** [comment]
- I tried to recreate some errors and post screenshots [here](https://github.com/ThanosApollo/dotfiles/tree/master/Pictures/Screenshots) I will delete them tomorrow tho
  - Not picking metadata etc. Hope it helps
- One easy to recreate annoying bug is that it "crushes" if you reload qtile while using spotify, 
- Spotify is quite popular, so having a dedicated widget for it wouldn't be a bad idea, since we have for other music playerst. 
- Mpris2 is an amazing widget, but it's frustrating when something goes wrong that 5% of the time.
Anyways, there is not much else to it. Thanks for looking at my pull request that fast tho xD!

**Comment by ThanosApollo** [comment]
Open spotify, reload qtile, the widget disappears

**Comment by elParaguayo** [comment]
> Open spotify, reload qtile, the widget disappears

Ah ok. So it doesn't query a player when it first starts. Presumably if you change track the text appears?

**Comment by elParaguayo** [comment]
I've got a fix for the lost metadata on reload.

As for your screenshots, this widget is relying on signals being broadcast over dbus. The advantage of this was that we're not constantly polling the player. However, if these are missing then we get those messages that you see. We could add a secondary polling method that runs on a larger interval so that it can tidy up those issues but I wouldn't have it as the primary method of getting metadata.

Thoughts?

**Comment by ThanosApollo** [comment]
I like it, I'd also suggest that it displays somekind of message when it's "missing" metadata signals, such as "No metadata to display" at least,  + a straight forward explanation on the docs on how to configure Mpris2 with spotify, if someone is not familiar with dbus he probably will have a hard time understanding the docs, some basic examples would be a nice addition.
Personally, I will be using the custom widget I've made cause it's simpler and more straight forward with dbus-python and I don't get the errors I do with mpris2.

**Comment by elParaguayo** [comment]
I think there's a general theme about making the docs more user friendly as they do assume a certain amount of knowledge which can make configuration harder for newer users.

As for using your own widget - makes perfect sense. One of the things that I really like about qtile is how easy it is to make your own widgets etc to fit your own needs.

**Comment by ThanosApollo** [comment]
Yeah, you and the rest of the team have done an amazing job!

**Pull request closed without merging**
