### PR TITLE
fix TaskList icons' vertical centering issue

### PR DESCRIPTION
**Pull request by ezntek**
One line fix that tries to address #1714 and #3873, as the fixes still do not work on my local system running on the main dev branch ([described here](https://github.com/qtile/qtile/issues/1714#issuecomment-1627198379)).

### CODE REVIEW

**Comment by elParaguayo** [comment]
Thanks for this.

I'm not convinced your solution is the correct one, however. If the icon's size was equal to `icon_size` then the existing code should work so there must be something going wrong elsewhere.

I suspect the issue is with the icon resizing code. Let me take a look.

**Comment by elParaguayo** [comment]
Yeah - I removed similar code in `CurrentLayoutIcon` to fix a similar issue (#4008) so I would think the same should be done here.

So, you could either change this or close it and I'll do it.

**Comment by ezntek** [comment]
I guess I'll leave it up to you, then.

**Comment by ezntek** [comment]
not to rush you or anything, but any progress @elParaguayo?

**Comment by elParaguayo** [comment]
@ezntek See #4349

**Pull request closed without merging**
