### PR TITLE
Nix: Run make update-flake

### PR DESCRIPTION
**Pull request by jwijenbergh**

### CODE REVIEW

**Comment by jwijenbergh** [comment]
this test failure is odd @elParaguayo. Does it have to do with the image decoding changes?

**Comment by elParaguayo** [comment]
Looks like we've lost svg support. That's not due to the image decoding change as svg files would have been handled the same way. I think, in the past, we've told users to make sure they've got `librsvg` installed. So you may need to add that (or whatever it's called in ubuntu) to our build environment.

**Comment by tych0** [comment]
No luck with librsvg2 :(

**Comment by elParaguayo** [comment]
It would have been weird to suddenly need a new dependency.

Has something happened to the SVG files?

**Comment by tych0** [comment]
I agree... and nothing has changed in tree. :ghost:

**Comment by jwijenbergh** [comment]
Maybe this flake.lock is cursed even though the CI doesn't use it 😂

**Comment by elParaguayo** [comment]
This is failing on other PRs so it's not related to this PR.

**Pull request merged**
