### PR TITLE
Just test hangs

### PR DESCRIPTION
**Pull request by tych0**
This is two of the patches from #2107 that just address the test hangs; looks like parallel tests etc. don't quite work yet, and we'd really like to have reliable CI. I've fixed up a couple of typos in one of the patches.

### CODE REVIEW

**Comment by DorianGray** [comment]
looks like tox.ini changes for installing multiprocess didn't make it into this.

**Comment by DorianGray** [comment]
also I had already pulled out the first commit into https://github.com/qtile/qtile/pull/2184

**Comment by tych0** [comment]
> looks like tox.ini changes for installing multiprocess didn't make it into this.

yeah, these are the kinds of rebase issues I was talking about, looks like I forgot about them too :)

> also I had already pulled out the first commit into #2184

thanks, merged.

**Comment by DorianGray** [comment]
\o/

**Pull request merged**
