### PR TITLE
Launchbar widget improvement

### PR DESCRIPTION
**Pull request by jrazik**
Improvement of the launchbar widget:
- when an icon is not found print text instead,
- icons are displayed in the order used in the list parameter.

### CODE REVIEW

**Comment by tych0** [comment]
Hi, thanks for the patch. Is it possible for you to rebase these commits on top of develop?

**Comment by jrazik** [comment]
hmm. I've played with rebase and may be broke everything ...

**Comment by tych0** [comment]
It looks like you've previously PR'd the launchbar widget, we already have the base. As near as I can tell, only the last one is relevant. I've cherry picked it to develop here: https://github.com/tych0/qtile/tree/launchbar-rebase; do you mind testing it to see if it works as you expect? You can get my branch with:

```
git remote add https://github.com/tych0/qtile
git fetch tych0
git checkout launchbar-rebase
# do your testing
```

Thanks!

**Comment by jrazik** [comment]
Looks good !
Thanks

**Comment by tych0** [comment]
Cool, thanks!

**Pull request closed without merging**
