### PR TITLE
Fix volume clickable event not working

### PR DESCRIPTION
**Pull request by shyguyCreate**
Solves comment https://github.com/qtile/qtile/pull/4779#issuecomment-2140295077

### CODE REVIEW

**Comment by shyguyCreate** [comment]
Help, how can I make the test pass? I am getting this error message `/bin/sh: 1: amixer: not found` in the checks.

**Comment by tych0** [comment]
the test environment needs amixer, you'll have to add it to the packages list in `.github/workflows/ci.yaml`

**Comment by shyguyCreate** [comment]
Thanks, just wanted to know if added a new dependency was okay.

**Comment by elParaguayo** [comment]
I would assume that the CI environment doesn't have any sound devices so this would probably fail. I'd be inclined to monkeypatch `subprocess.call` and store the command that's called.

**Comment by shyguyCreate** [comment]
Like this `monkeypatch.setattr(vol, "mute", "amixer -q sset Master toggle")`? (first time with monkeypatch)

**Comment by elParaguayo** [comment]
Not quite. I can write a test later for this so don't worry about it for now.

However, I've also noticed that `PulseVolume` has the same issue with the name clashes (that was my fault!) - could you fix that too?

**Comment by elParaguayo** [comment]
Thanks for this. Seems to work fine.

**Pull request merged**
