### PR TITLE
Some fixes and improvements + fix ##619 for Max layout

### LINKED ISSUE #619: TreeTab and Zoomy layouts: changing a window to floating should also show the previous tiled window
EDIT: This bug was originally reported for the Max layout, but it was later discovered to affect other layouts too.

Steps to reproduce:
1. Open 2 windows in a group with Max layout.
2. Change the focused window to floating: the other window is not shown below it.

The expected behavior would be to also show the previous tiled window when one is changed to floating.

### PR DESCRIPTION
**Pull request by kynikos**
The commit messages and diffs should speak for themselves.
75be78388dddbaf7518c9f68848070cbbe1226ed fixes #619 for the Max layout.

### CODE REVIEW

**Comment by kynikos** [comment]
There's something in the title or commit messages that wants to close #619 automatically if this PR is merged (very smart, GitHub... :P), what can we do?

**Comment by tych0** [comment]
I suppose it's the string "addresses #619". Sorry I haven't taken a closer look at this yet, I've got a max focus bug that I want to look at as well, I suspect it's related to 30d88be2b30013668135ff5b2ced9b4ad9e9dbbd, so I'd like to try and understand all of these changes at the same time.

**Comment by tych0** [comment]
Derp. Shouldn't have closed it.

**Comment by tych0** [comment]
Looks good, thanks! This also fixed my focus bug that I was experiencing too :)

**Comment by kynikos** [comment]
Fantastic! Can you reopen #619? Also TreeTab and Zoomy are affected.

**Pull request merged**
