### PR TITLE
ci: coveralls master -> main

### PR DESCRIPTION
**Pull request by tych0**
It looks like the coveralls action  went from master -> main here, do the same in our actions code.

### CODE REVIEW

**Comment by elParaguayo** [comment]
Nice.

Could you do pre_commit.yml too?

**Comment by tych0** [comment]
Happy to do it, but I'm not sure I understand what you mean?

**Comment by elParaguayo** [comment]
There were some similar messages on that workflow too.

Screenshot_20240216_223356_Chrome

**Comment by tych0** [comment]
Ok... I don't understand how to fix these last two, so I'll leave them for now.

**Pull request merged**
