### PR TITLE
Respect max size

### PR DESCRIPTION
**Pull request by ramnes**

### CODE REVIEW

**Comment by tych0** [comment]
A test for this would be nice :)

**Comment by ramnes** [comment]
Yeah, and for #2159 as well. I tried to modify `tests/scripts/window.py` to spawn a window with such hints but couldn't find how to do that with xcffib. Can you help? Or I can add gnome-screenshot as a dependency for both tests. :)

**Comment by tych0** [comment]
See stuff like test_only_one_focus(), it sets WM_HINTS like you want here.

**Comment by ramnes** [comment]
test added :)

**Pull request merged**
