### PR TITLE
TaskList: don't leave empty space if there's no icon

### PR DESCRIPTION
**Pull request by dequis**
Might be a slightly opinionated change, but tasklist items have variable space right now so why not.

Definitely not for 0.9.1

### CODE REVIEW

**Comment by Roger** [comment]
My idea for this was to add a default icon, but never did

**Comment by tych0** [comment]
Seems like python 2.6 doesn't like this change?

**Comment by dequis** [comment]
Uhhhh... how can i tell those errors apart from the usual "our test suite isn't deterministic"?

**Comment by tych0** [comment]
On Fri, Feb 13, 2015 at 07:37:28AM -0800, dx wrote:
> Uhhhh... how can i tell those errors apart from the usual "our test suite isn't deterministic"?

I've never seen these before :)

**Comment by dequis** [comment]
Re-ran the test and it passed. I also checked the patch for anything specific to python2.7, but the only thing that came close is the ternary operator was introduced in 2.5.

**Comment by tych0** [comment]
Argh. We need to spend some time to figure that crap out. Looks reasonable to me, @Roger any other thoughts?

**Comment by Roger** [comment]
I have no hope of me doing the default icon stuff, so this looks good :)

**Comment by kynikos** [comment]
If you guys are interested in having a default icon, maybe optionally, I've pushed kynikos@f00e066878504744eaef13a8e18f1a647cde80be on top of this patch, although it should be expanded, but I think the biggest part would be done.

**Comment by Roger** [comment]
@kynikos where did you get those icons, and what's the license?

**Comment by kynikos** [comment]
Sorry, I've added it to the comment after saving it, so you haven't received in the email: the SVG file is from http://tango.freedesktop.org/Tango_Desktop_Project released under Public Domain; the PNGs are simply Inkscape exports that I've saved.

**Comment by tych0** [comment]
Ok, so should I take this patch and then wait for the default icon one?

**Comment by kynikos** [comment]
Given your answer I assume you would indeed merge a complete patch for a default icon, so as far as I'm concerned you can merge this patch and I'll finish mine and open another PR for it when ready.

**Comment by tych0** [comment]
On Sun, Feb 15, 2015 at 06:39:02AM -0800, Dario Giovannetti wrote:
> Given your answer I assume you would indeed merge a complete patch for a default icon, so as far as I'm concerned you can merge this patch and I'll finish mine and open another PR for it when ready.

Ok. Can you please add a bit about the licensing to the header of the
svg? This will make it easier for us to package.

**Comment by kynikos** [comment]
I certainly will, I've taken note of that. Don't expect anything soon though, there are other features I'd like to work on first :)

**Pull request closed without merging**
