### PR TITLE
stop accepting sponsorships

### PR DESCRIPTION
**Pull request by m-col**
Unfortunately I've had limited time to commit to Qtile lately so I'm going to take my name down from the sponsor button.

### CODE REVIEW

**Comment by elParaguayo** [comment]
Ridiculous. I'm not in favour of this.

**Comment by m-col** [comment]
It's only fair, there are other maintainers (yourself included) more deserving, and really it's been a few months since I've made any substantial contribution. But eventually I'll get back on the horse :)

**Comment by elParaguayo** [comment]
There are so many people benefiting from the efforts you put in. The fact that you're currently less active now is irrelevant.

**Comment by m-col** [comment]
Hmm. Maybe you're right. I have some guilt about accepting money when I'm not contributing, but the code I made is still there and still working. At least let me buy you a fancy cheese or something :)

**Pull request closed without merging**
