### PR TITLE
Add Guix to check updates widget

### PR DESCRIPTION
**Pull request by jgarte**
Hi,

This PR adds [Guix](https://guix.gnu.org/) to the `CheckUpdates` widget.

### CODE REVIEW

**Comment by elParaguayo** [comment]
Thanks for submitting this.

I have mixed feelings about this one. On the one hand, it's easy enough to add. On the other hand, I'm just wondering if we need it. 

I don't know how popular Guix is as a distro (e.g. it's not in the top 100 on Distrowatch) and it's easy enough for users to add custom commands to the widget via their config files, without the need for a PR.

**Comment by jwijenbergh** [comment]
@jgarte Thanks for the pr. I'm not that familiar with guix, does this always guarantee that the latest package definitions are fetched? I assume this would only  tell you that you're out of date after a guix pull? Not saying this is a problem just want to understand it before we potentially merge this. Got some info here https://systemcrafters.cc/craft-your-system-with-guix/everyday-package-management/#upgrading-packages

**Comment by jgarte** [comment]
Hi give me till this weekend. I'm going to add a few screenshots of the widget working for you to see. Just busy atm with work. 

>  I assume this would only tell you that you're out of date after a guix pull?

Here's an example of what `guix upgrade --dry-run` would show:

```
$ guix upgrade --dry-run
The following packages would be upgraded:
   firefox     111.0.1 → 112.0.1
   git         (dependencies or package changed)
   go          (dependencies or package changed)
   keepassxc   (dependencies or package changed)
   pulseaudio  (dependencies or package changed)
   pulsemixer  (dependencies or package changed)
   python-rich (dependencies or package changed)
   ripgrep     (dependencies or package changed)
   timidity++  (dependencies or package changed)
```
Here's an example of what `guix pull --dry-run` would show:

```sh
$ guix pull --dry-run
Updating channel 'guixrus' from Git repository at 'https://git.sr.ht/~whereiseveryone/guixrus'...
Updating channel 'rde' from Git repository at 'https://git.sr.ht/~abcdw/rde'...
Authenticating channel 'rde', commits 257cebd to 7738b7e (6 new commits)...
Updating channel 'nonguix' from Git repository at 'https://gitlab.com/nonguix/nonguix'...
Updating channel 'guix' from Git repository at 'https://git.savannah.gnu.org/git/guix.git'...
Authenticating channel 'guix', commits 9edb3f6 to 960647f (80 new commits)...
Building from these channels:
  guix      https://git.savannah.gnu.org/git/guix.git	960647f
  nonguix   https://gitlab.com/nonguix/nonguix	7a9b3ca
  rde       https://git.sr.ht/~abcdw/rde	7738b7e
  guixrus   https://git.sr.ht/~whereiseveryone/guixrus	5a13f41
```

**Comment by jwijenbergh** [comment]
We discussed this on discord, it's fine to merge. Thanks!

**Pull request merged**
